### ISSUE TITLE
LTTextLine?

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#1]
This is more of a question than an issue: do you plan to make PDFMiner's LTTextLine and LTTextBox objects / hierarchy available through pdfplumber? Or is the point of this to make only the raw character positions available so that one can roll one's own layout analysis without PDFMiner getting in the way at all?

**Comment by jsvine** [comment]
Thanks, Jacob! Nice opportunity to explain some of the thinking behind pdfplumber.

> This is more of a question than an issue: do you plan to make PDFMiner's LTTextLine and LTTextBox objects / hierarchy available through pdfplumber?

The earliest prototypes for pdfplumber did, in fact, provide access to `LTTextLine` and `LTTextBox`, but I ended up ditching them, for a few reasons:

1. I found that, when it came to extracting structured data (rather than, say, plain ol' lines of text), the results of the  `LTTextLine` and `LTTextBox` algorithms almost never returned what I needed. It'd seem promising at first, but then I'd end up having to reconstruct everything from the raw chars, lines, and rects. 

2.  `LTTextLine` and `LTTextBox` are already available through PDFMiner's `pdf2txt` utility, with the `-t xml` flag.

3. Removing PDFMiner's layout analysis routines speeds things up slightly.

> Or is the point of this to make only the raw character positions available so that one can roll one's own layout analysis without PDFMiner getting in the way at all?

Yep, that's pretty much it!

All that said, I'm open to being persuaded otherwise. What do you think?

**Comment by jsfenfen** [comment]
Cool, thanks so much for this explanation! I'm agnostic as to whether LTTextLines are worth including here, just more curious about what you're aiming at. I definitely think more work could go into layout analysis--I've hacked a bit on this for OCR'ed stuff--but can harass you further offline.

**Comment by ubmarco** [comment]
I'm commenting on this after 4 years. Is there a pdfplumber equivalent to LTTextBox?
I'm after paragraphs which pdfminer seems to extract pretty well - at least in my initial experiments. Maybe the feature was improved? Any advice on how to reach the same with pdfplumber?

**Comment by jsvine** [comment]
Hi @ubmarco, and thanks for your interest! Right now, there is not an equivalent in pdfplumber. It's an interesting idea, though.

You might be able to achieve something similar by iterating through all the chars, and assigning them to groups/clusters based on their x/y distance from the previous. E.g., if the a char is more than X points below or Y points right/left than previously-seen chars in the current text-box, start a new text-box with the current char as its first member.

It feels like this approach could work in many circumstances, but might also have a lot of edge-cases. But if you find that this approach (or another of your own creation) works well across a wide variety of PDF layouts, I'd consider adding this functionality to the library.

**Comment by ubmarco** [comment]
Thanks for the feedback.
I actually find the pdfminer.six results pretty good. There are some corner cases that I see (e.g. getting text from tables are a mess). But with pure text or multi column layout, it does a decent job.

Not to reinvent the wheel I'm currently using an hybrid approach of pdfplumber and pdfminer.six:
```
from pdfminer.layout import LTTextBox
from pdfminer.pdfpage import PDFPage

import pdfplumber

laparams = {
    'line_overlap': 0.5,
    'char_margin': 2.0,
    'line_margin': 0.5,
    'word_margin': 0.1,
    'boxes_flow': 0.5,
    'detect_vertical': False,
    'all_texts': False
}  # default values from pdfminer for layout analysis parameters

with pdfplumber.open(pdf_path, laparams=laparams) as pdf:
    page_textboxes = {}
    for page in enumerate(PDFPage.create_pages(pdf.doc)):
        pdf.interpreter.process_page(page)
        result = pdf.device.get_result()
        textboxes = [obj for obj in result if isinstance(obj, LTTextBox)]
        page_textboxes[idx_page] = textboxes
```
I then get the coordinates of the LTTextBox instances and remove all that are part of tables/figures detected by pdfplumber. By doing so I get the benefit of the pdfplumber's table extraction and the layout analysis capabilities of pdfminer.six.

Any further thoughts on this?

**Comment by ubmarco** [comment]
Hmm, when running above code, I see some strange items in all `pdf.pages[].objects['anno']`:
![Screenshot_2020-03-30_22-17-02](https://user-images.githubusercontent.com/839934/77957864-70d71b00-72d4-11ea-925a-f94614abea81.png)
I don't get that when I don't pass `laparams`. These items lack x0 etc. coordinates which leads to exceptions later. Do you have an idea where that could come from?
Thanks a lot for your time and for helping out.

**Comment by jsvine** [comment]
Thanks for sharing! My responses to your questions:

> Any further thoughts on this?

It's definitely an interesting approach! Right now, `pdfplumber` is focused on extracting low-level information about text characters, lines, rects, etc., and then determining larger concepts (words, tables, etc.) from those. I'm also slightly wary of building in too much dependency on `pdfminer.six`; it could be neat in the future to be able to swap out that dependency for a newer/better one (if there eventually is one) with minimal fuss.

That said, I'm totally open to someone adding `LTTextBox`-like functionality to `pdfplumber`; I'd just want it to start from `char` objects.

> Hmm, when running above code, I see some strange items in all `pdf.pages[].objects['anno']`

Interesting! That's the first I've seen of that. Have you found any related `pdfminer.six` issues?

**Comment by ubmarco** [comment]
Thanks a lot again for your reply, that is of high value to me.

> Interesting! That's the first I've seen of that. Have you found any related pdfminer.six issues?

No, I looked already through the issues for pdfminer and pdfminer.six. I also don't know what `objects['anno']` is supposed to be on `pdf` and `page`. What's the difference between annotation-text character and text-character as per the README.md?

Let's dig into the multiple anno-like objects:
* `pdf.annos` list, always empty for me
* `pdf.objects['anno']` list, commonly not existing unless I pass `laparams`; gets source data from `pdf.pages[idx].objects['anno']` lists
* `pdf.pages[idx].annos` list, always empty for me
* `pdf.pages[idx].objects['anno']` list, source of `pdf.objects['anno']`
* `pdf.pages[idx].page_obj.annots` list, this is where I get real PDF annotations (link sources with bbox data); this however is a PDFPage pdfminer class instance, I'm confused why pdfplumber does not expose that to its own API as it's the most relevant of above list

Only the last element in above list makes sense to me, for the others I just fight so they don't stand in my way. pdfplumber actually uses `pdf.pages[idx].objects['anno']` to determine the content of cropped pages. With the strange population I get by the pdfminer layout analysis, pdfplumber throws an exception looking for the coordinate keys (like x0). My current workaround is to just delete the key:
```
for page in pdf.pages:
    del page.objects['anno']
```
This fixes it for me. I don't know if there are side effects deleting the key. I'm lost at debugging this any further :/

**Comment by jsvine** [comment]
Hi @ubmarco, and thank you for flagging this. I must admit: I haven't focused very much on annotations while developing PDFPlumber. I'm sorry for any confusion this has caused you. I've been a bit busy, but I hope to take a closer look at this soon and hopefully fix any relevant bugs.

**Comment by ubmarco** [comment]
No need to be sorry because I don't expect perfection and completion. I mean it's a free and great library that you developed, presumably mainly in your free time. I just wanna understand the motivation behind the annotation-text character and how elements of the underlying pdfminer library are exposed.
