### ISSUE TITLE
Password protected and check extractable for pdf

### ISSUE THREAD

**Issue by nikhilbhawsinka** [jsvine/pdfplumber#101]
Hi,
Can you please explain how to pass a password for a protected pdf file. Also, how to do check_extractable as false for pdfs. Both these functionalities are available in pdfminer, but i cant seem to get them working in pdfplumber.
I am using "pdfplumber.open(path)" to access a file, so i am assuming this is the function which should be taking these parameters but cant get it to work.

Thanks

**Comment by jsvine** [comment]
Sure thing; added in https://github.com/jsvine/pdfplumber/commit/6f70d0937ac3f22df2265d197349b52ff4f9d9d5 and now available in `v0.5.12`. You can now call `pdfplumber.open(path, password = 'password')`.
