### ISSUE TITLE
Possibility to extract table of contents

### ISSUE THREAD

**Issue by Alssndr0** [jsvine/pdfplumber#1018]
I couldn't find any documentation on this. Is it possible to extract the table of contents? 
This would be a very nice to have.

**Comment by jsvine** [comment]
Hi @Alssndr0, does this get you want you want?: https://github.com/jsvine/pdfplumber/discussions/456#discussioncomment-947380

**Comment by Alssndr0** [comment]
Amazing, that's exactly what I was looking for. 
Thank you!
