### ISSUE TITLE
ValueError: Cannot convert <PDFObjRef:55> to Decimal

### ISSUE THREAD

**Issue by OisinMoran** [jsvine/pdfplumber#102]
This seems similar to Issue https://github.com/jsvine/pdfplumber/issues/41. I have tried that PDF and it works fine, yet I have encountered two more PDFs (let's call them 55 and 8) that give effectively the same error.

## 55
For the first one I get `ValueError: Cannot convert <PDFObjRef:55> to Decimal.` and this object 55 is referenced in the PDF by `/Rotate 55 0 R` as seen here:
```
<</Contents 53 0 R/CropBox[0 0 612 792]/MediaBox[0 0 612 792]/Parent 46 0 R/Resources<</ProcSet[/PDF/ImageC]/XObject<</Im0 54 0 R>>>>/Rotate 55 0 R/Type/Page>>
```

and is defined as:
```
55 0 obj
0
endobj
```

## 8
For the second file I get `ValueError: Cannot convert <PDFObjRef:8> to Decimal.` and this object 8 is referenced in the PDF by `/Rotate 8 0 R` as seen here:
```
<</Type/Page/MediaBox[0 0 595 842]/Rotate 8 0 R/Contents 6 0 R/Resources 7 0 R/Parent 4 0 R>>
```

and is defined as:
```
8 0 obj
0
endobj
```

## Issue 41 File
These are in contrast with the file given in Issue https://github.com/jsvine/pdfplumber/issues/41, where we can see that object 4 (the one that was causing an issue before the fix) is referenced in the PDF by:

```
/CropBox 4 0 R 
```
and is defined as:
```
4 0 obj 
[ 0 0 792 612 ] 
endobj 
```

So it would seem that the common theme between the problematic examples is something like trying to Decimalize an object that represents a rotation of 0. I also just noticed that both of these document were produced by `EPSON Scan`.

## Previous versions
Trying previous versions shows this _exact_ error only appears in the latest version, `0.5.11` but still breaks until we go all the way back to version `0.4.5`:

Version(s)|Error 
-|-
`v0.5.11` | ValueError: Cannot convert <PDFObjRef:55> to Decimal.
`v0.5.10-v0.4.6` | TypeError: unsupported operand type(s) for %: 'PDFObjRef' and 'int'
`v0.4.5` and previous | No error

## Workaround
The issue can be fixed by changing line 19 in  `page.py` from:
```python3
_rotation = self.decimalize(self.page_obj.attrs.get("Rotate", 0))
```
to:
```python3
try:
    _rotation = self.decimalize(self.page_obj.attrs.get("Rotate", 0))
except:
    _rotation = 0
```
This seems to solve the issue and fit roughly with the behavior intended by `get()` (namely that it defaults to zero). However, there is probably a nicer fix more akin to how the previous issues with this were fixed. Would love to hear your thoughts on this.

**Comment by jsvine** [comment]
Many thanks for filing this detailed report, @OisinMoran! I think we can probably fix this by taking the same approach as in #41: wrapping the `Rotate` attribute in `resolve_all(...)`, so that `PDFObjRef`s are resolved before we try decimalizing them. (Cf. [here](https://github.com/jsvine/pdfplumber/pull/42/files#diff-5ef7c728187b8d32b8429c6f70c5982b).)

I'd like to be able to write a test for this issue, to make sure the fix really works. Are you able to supply one of the currently-failing PDFs?

**Comment by OisinMoran** [comment]
Hey, @jsvine sorry for the delay. Unfortunately I can't share these files as they are confidential but I can check any fixes and let you know if they solve the problem. I know it's not the ideal situation, but if I come across a non-confidential one that causes the same issue I'll send it on.

**Comment by yoeldk** [comment]
Hi,
Any idea whether this issue is fixed in version 0.5.20?

**Comment by eran-pinhas** [comment]
Seems that it does, @OisinMoran can you confirm?

**Comment by OisinMoran** [comment]
Yep, this is fixed.
