### ISSUE TITLE
Possible to output to new pdf

### ISSUE THREAD

**Issue by yezhengli-Mr9** [jsvine/pdfplumber#1021]
Please describe, in as much detail as possible, your proposal and how it would improve your experience with pdfplumber.
Possible to output to new pdf? For example, raw pdf was disallowed to "copy" texts but expect to 
```python
with pdfplumber.open(pdf_file_path) as pdf:
    for page_number in range(len(pdf.pages)):
        page = pdf.pages[page_number]
```
then output new pdf that allow to "copy" texts.

**Comment by jsvine** [comment]
Hi @yezhengli-Mr9; `pdfplumber` does not perform PDF generation. You might be interested in the other libraries mentioned here, some of which do support PDF generation: https://github.com/jsvine/pdfplumber#comparison-to-other-libraries
