### ISSUE TITLE
pdfplumber characters missing ( for Chinese character )

### ISSUE THREAD

**Issue by mosescha** [jsvine/pdfplumber#1022]
## Describe the bug

*A clear and concise description of what the bug is.*
I fail to extract Chinese characters from PDF 
Here is the error case 
  株式會社 大韓航空  ==> 大 空

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

*Please try running your code with `pdfplumber.open(..., repair=True)` before submitting a bug report.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

import pdfplumber

pdf_path = "c:\\temp\\202010200090007270.pdf"
with pdfplumber.open(pdf_path) as pdf:
    for page in pdf.pages:
        page_text = page.extract_text()
        print(page_text)

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.10.2]
- Python version: [e.g., 3.9.13]
- OS: [Windows 10.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by mosescha** [comment]
[202010200090007270.pdf](https://github.com/jsvine/pdfplumber/files/13146076/202010200090007270.pdf)
the pdf file is attached

**Comment by mosescha** [comment]
fitz module doesn't have same problem about missing character

**Comment by cmdlineluser** [comment]
Hi @mosescha 

> Here is the error case
> 株式會社 大韓航空 ==> 大 空

Perhaps some page_number info / screenshots could help? 

It's probably a little difficult to locate for non-native speakers.

Is it this item on Page 1?

<blockquote>

<img width="951" alt="Screen Shot 2023-10-25 at 16 42 13" src="https://github.com/jsvine/pdfplumber/assets/99486669/c8adfc7a-9f26-482b-b52c-e0434de1d0f4">

</blockquote>

`pdfplumber` uses `pdfminer.six` to read the PDF, so it could possibly be a pdfminer issue.

**Comment by jsvine** [comment]
Thanks, @cmdlineluser. It does look like that's the place @mosescha is flagging, based on some exploration I just did. On my computer, if you select that text and then copy-paste it into Mac's TextEdit program, I get get this:

<img width="258" alt="Screenshot 2023-10-25 at 5 24 24 PM" src="https://github.com/jsvine/pdfplumber/assets/534702/b64c9527-9d24-4994-bb59-04f71ea3c077">

So it seems to be a font / character-encoding issue. If `fitz` translates the characters correctly, per @mosescha, perhaps it's something `pdfminer.six` could solve. But this seems outside the realm of what can be fixed in `pdfplumber` itself.

**Comment by mosescha** [comment]
> Hi @mosescha 
> 
> > Here is the error case
> > 株式會社 大韓航空 ==> 大 空
> 
> Perhaps some page_number info / screenshots could help? 
> 
> It's probably a little difficult to locate for non-native speakers.
> 
> Is it this item on Page 1? 
Right
> 
> <blockquote>
> 
> <img width="951" alt="Screen Shot 2023-10-25 at 16 42 13" src="https://github.com/jsvine/pdfplumber/assets/99486669/c8adfc7a-9f26-482b-b52c-e0434de1d0f4">
> 
> </blockquote>
> 
> `pdfplumber` uses `pdfminer.six` to read the PDF, so it could possibly be a pdfminer issue.
>

**Comment by cmdlineluser** [comment]
@jsvine Ah, interesting.

`fitz` doesn't seem to handle it on my end.

<img width="250" alt="Screen Shot 2023-10-26 at 00 26 30" src="https://github.com/jsvine/pdfplumber/assets/99486669/27bbabd5-7b12-413e-b430-72fec59ce5c6">

<br/>
<br/>

`pypdfium2` seems to do a bit better:

<img width="388" alt="Screen Shot 2023-10-26 at 00 27 14" src="https://github.com/jsvine/pdfplumber/assets/99486669/7bfdabd3-7a0f-45b8-b883-41c1c9dc0302">

<br/>
<br/>

pdfminer gives me those `cid:` codes.
```python
상  호  (cid:35128)(cid:33835)(cid:36204)(cid:33383)
```

There seem to be quite a few issues related to that. https://github.com/pdfminer/pdfminer.six/issues?q=cid

**Comment by mosescha** [comment]
![image](https://github.com/jsvine/pdfplumber/assets/8922071/b91f12fe-a02d-44c7-98af-76dda01985ce)
Here is screenshot for fitz

As if you see, It has no problem with missing Chinese character

**Comment by jsvine** [comment]
Hmm, perhaps the difference @mosescha and @cmdlineluser are seeing re. `fitz` is related to the operating system (which ones are you on?) or `fitz` version?

In any case, this seems like an issue better/best resolved in the [`pdfminer.six` codebase](https://github.com/pdfminer/pdfminer.six). For that reason, I'm closing this comment, but feel free to continue the discussion.

**Comment by cmdlineluser** [comment]
@mosescha You should have `pypdfium2` installed, you could attempt to use that to parse the text: https://github.com/jsvine/pdfplumber/discussions/962#discussioncomment-6700337 to see if it does a better job.
