### ISSUE TITLE
Getting delegate error while using to_image method

### ISSUE THREAD

**Issue by bailixuance** [jsvine/pdfplumber#104]
I am using "to_image" with following code.
`import pdfplumber
import pandas as pd

pdf = pdfplumber.open("./pdf/29876713.pdf")
p0 = pdf.pages[0]
im = p0.to_image()`

But when I use "to_image()" function to use pdfplumber's visual-debugging tools,the following exception is being raised
`DelegateError: FailedToExecuteCommand `"D:/Program Files (x86)/gs/gs9.26/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 "-sOutputFile=C:/Users/L/AppData/Local/Temp/magick-8436YHuAhmM-yef7%d" "-fC:/Users/L/AppData/Local/Temp/magick-84368scpfv880pPg" "-fC:/Users/L/AppData/Local/Temp/magick-8436OndZPUFRlzRd"' (-1073741819) @ error/delegate.c/ExternalDelegateCommand/462`

My pdfplumber version is 0.5.11 and python version is 3.6.
I still installed ImageMagic(version 6.9.9-37 Q8(64-bit)) and Ghostscript for 9.26 for Windows(32 bit) on my windows(win 10,64 bit).

What should I do to make "to_image()" function work well?

**Comment by bailixuance** [comment]
When using sample files in the folder of "pdfplumber/examples/notebooks" for testing, when testing "extract-table-nics.ipynb",it works properly.But when it comes to "extract-table-ca-warn-report.ipynb",when using "to_image()" functions,the following exception is being raised
```
DelegateError: FailedToExecuteCommand `"D:/Program Files (x86)/gs/gs9.26/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 "-sOutputFile=C:/Users/L/AppData/Local/Temp/magick-11052wsrXpbsN61c7%d" "-fC:/Users/L/AppData/Local/Temp/magick-11052NBDXSMWYHmD7" "-fC:/Users/L/AppData/Local/Temp/magick-110529YB2ntvCcDMX"' (-1073741819) @ error/delegate.c/ExternalDelegateCommand/462
![1553220672(1)](https://user-images.githubusercontent.com/37102511/54796354-e30d2c80-4c8a-11e9-9003-6403ca576182.jpg)
![1553220672(1)](https://user-images.githubusercontent.com/37102511/54796370-f4563900-4c8a-11e9-9444-42e8cda802b4.jpg)


```

**Comment by bailixuance** [comment]
![image](https://user-images.githubusercontent.com/37102511/54796397-0df78080-4c8b-11e9-86c0-fd06d62e74af.png)

**Comment by jsvine** [comment]
This seems to be an issue either with ImageMagick or Ghostscript. Unfortunately, I'm not very familiar with troubleshooting those on Windows. Has anyone else watching this repository encountered a similar problem? Figured out how to solve it?

**Comment by filipetavares** [comment]
You need to define a env var "MAGICK_GHOSTSCRIPT_PATH" that points to the ghostscript bin folder

**Comment by OisinMoran** [comment]
Another possible solution could be to downgrade to Ghostscript 9.22. I think I've encountered a similar-looking error but this was on Ubuntu.

**Comment by royshil** [comment]
After some digging I figured `-dMaxBitmap=500000000` is the culprit, and when I manually ran cmd line with `-dMaxBitmap=5000000` it worked fine, any higher value resulted in a segfault of `gs`.

**Comment by djoguns** [comment]
> I am using "to_image" with following code.
> `import pdfplumber
> import pandas as pd
> 
> pdf = pdfplumber.open("./pdf/29876713.pdf")
> p0 = pdf.pages[0]
> im = p0.to_image()`
> 
> But when I use "to_image()" function to use pdfplumber's visual-debugging tools,the following exception is being raised
> `DelegateError: FailedToExecuteCommand `"D:/Program Files (x86)/gs/gs9.26/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 "-sOutputFile=C:/Users/L/AppData/Local/Temp/magick-8436YHuAhmM-yef7%d" "-fC:/Users/L/AppData/Local/Temp/magick-84368scpfv880pPg" "-fC:/Users/L/AppData/Local/Temp/magick-8436OndZPUFRlzRd"' (-1073741819) @ error/delegate.c/ExternalDelegateCommand/462`
> 
> My pdfplumber version is 0.5.11 and python version is 3.6.
> I still installed ImageMagic(version 6.9.9-37 Q8(64-bit)) and Ghostscript for 9.26 for Windows(32 bit) on my windows(win 10,64 bit).
> 
> What should I do to make "to_image()" function work well?

I believe you need to install the additional Visual debugging tools
1. ImageMagick
2. ghostscript
if you install only ImageMagick, you will get this error.
Cheers.

**Comment by jsvine** [comment]
Thank you, all! Closing for now, but feel free to reopen if the issue persists for you @bailixuance.
