### ISSUE TITLE
alway convert patterns 'ti' to number 5 when extecting text, like question to ques5on, solution to solu5on. 

### ISSUE THREAD

**Issue by rucwangw** [jsvine/pdfplumber#1043]
Source PDF:
<img width="797" alt="图片" src="https://github.com/jsvine/pdfplumber/assets/16409681/7c364e13-1052-4b2e-bec1-2d945059b32d">

The extracted text as following:
<img width="574" alt="图片" src="https://github.com/jsvine/pdfplumber/assets/16409681/5508e7c0-0f55-4ac6-887d-7b9dce95ab11">

**Comment by jsvine** [comment]
This seems likely to be an issue with the PDF itself, and how it encodes text. One way to test this yourself is to open the PDF in a standard PDF reader, select some of the text, and paste it into a text editor. Do you also see the `5`s either? If not, could you provide the PDF?

**Comment by rucwangw** [comment]
thanks for your response. It's the PDF issue.
