### ISSUE TITLE
Offset in bounding boxes for every pdf passed

### ISSUE THREAD

**Issue by yashsandansing** [jsvine/pdfplumber#1049]
## Describe the bug
I passed PDFs to the `im.draw_rects(first_page.extract_text_lines())` function, and I'm getting an offset in different directions for each PDF I have passed.

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

Yes, I've tried repairing the PDFs with `gs` as well as with `pdfplumber` but gotten little to negligible difference

## Code to reproduce the problem

```
import pdfplumber

repaired = pdfplumber.repair("/content/iebe102.pdf", outfile="/content/repaired2.pdf")
pdf = pdfplumber.open("/content/repaired2.pdf")
first_page = pdf.pages[0]
im=first_page.to_image()

# Run either one from below
# im.outline_words()
im.draw_rects(first_page.extract_text_lines())
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

[iebe102.pdf](https://github.com/jsvine/pdfplumber/files/13487511/iebe102.pdf)
[iemh101.pdf](https://github.com/jsvine/pdfplumber/files/13487515/iemh101.pdf)

## Expected behavior

Boxes should have been detected with their text

## Actual behavior

Offset in multiple directions like this:
![Screenshot 2023-11-28 172104](https://github.com/jsvine/pdfplumber/assets/48054260/b8afc704-fa65-4d9a-9ce8-9ef0e4a0c102)
![Screenshot 2023-11-28 171441](https://github.com/jsvine/pdfplumber/assets/48054260/03e82734-cf64-4897-a04a-545329a84dd6)

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context
I've tried resizing the PDF, and setting the resolution, height, width, etc. but nothing seems to work

**Comment by Pk13055** [comment]
Dropping this here in case it helps you. I noticed certain PDFs have an offset to the page's actual bbox, so adjusting (as follows), helps crop/extract the right region
```python
import pdfplumber
pdf = pdfplumber.open('/path/to/pdf')
# box_offset = 2
for annot in pdf.annots:
    pg_number = annot['page_number']
    if pg_number in table_counter:
        table_counter[pg_number] += 1
    else:
        table_counter[pg_number] = 1
    page = annot_pdf.pages[pg_number - 1]
    px0, py0, px1, py1 = page.bbox
    bbox = [annot['x0'], annot['top'] + 2 * py0, annot['x1'], annot['bottom'] + 2 * py0]
    xt, yt, xb, yb = bbox
    # bbox = [xt + box_offset, yt + box_offset, xb - box_offset, yb - box_offset]
    roi = page.crop(bbox, relative=False, strict=False)
    roi.to_image(resolution=500, antialias=True).save(f"p{pg_number}_t{table_counter[pg_number]}.png")
```

**Comment by jsvine** [comment]
Hi @yashsandansing, and thanks for flagging. With  https://github.com/jsvine/pdfplumber/commit/07d9997ee587723c32e2178be65eea584102bf58 (now available in `develop`), this should now be fixed (showing `page.to_image().outline_words()`:

![image](https://github.com/jsvine/pdfplumber/assets/534702/a7334f21-4809-4a45-b254-9561b55191fc)

![image](https://github.com/jsvine/pdfplumber/assets/534702/b4d1807f-8695-4ddf-b00d-0bed1e46d9c4)
