### ISSUE TITLE
[Feature]  Add `Column` object(s) to `find_table()`

### ISSUE THREAD

**Issue by Pk13055** [jsvine/pdfplumber#1050]
Currently, `find_table` returns a table object that contains two props, viz. `.cells: list[tuple(float, float, float, float]]` and  `.rows: Row object`,  which in turn contains `.cells`. It would be great if, similar to `.rows`, a `.columns` property is also added, since intersections of bboxes can be calculated and thereby external OCR can be applied on a per-cell basis.

**Comment by jsvine** [comment]
Thanks for the suggestion, @Pk13055. The idea seems reasonable; I'll investigate how this might be added.

**Comment by jsvine** [comment]
Hi @Pk13055, and thanks again for the suggestion. Now added in https://github.com/jsvine/pdfplumber/commit/d39302fa2ce5976f92276f60d10c127167f94d26 and available on the `develop` branch.
