### ISSUE TITLE
can not step over the function 'nexttoken' in psparser.py

### ISSUE THREAD

**Issue by ldhsight** [jsvine/pdfplumber#106]

**Comment by ldhsight** [comment]
[http://static.cninfo.com.cn/finalpage/2018-08-29/1205360001.PDF](url)
As I showed above, this url links to a pdf file, when I tried to run my codes to parse the file, my program got into an endless loop in function 'nexttoken'. The bug may locate in section 
`        elif c == b'(':
            self._curtoken = b''
            self.paren = 1
            self._parse1 = self._parse_string
` 
of method 'def _parse_main(self, s, i)' in class 'PSBaseParser' of psparser.py

And this is my code block - - 
`import pdfplumber as pp

file = 'report.pdf'
pdf = pp.open(file)
for page in range(len(pdf.pages)):
    print(page)
    sheet = pdf.pages[page]
    sheet.extract_text()`

**Comment by jsvine** [comment]
Hi @ldhsight. `PSBaseParser` is part of `pdfminer.six`, which `pdfplumber` uses as a library. Your issue is likely better addressed there: https://github.com/pdfminer/pdfminer.six
