### ISSUE TITLE
debug_tablefinder is weirdly offset

### ISSUE THREAD

**Issue by px-xp** [jsvine/pdfplumber#1078]
## Describe the bug

When I run `debug_tablefinder` on a PDF the offset of the overview is weird.

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

Yes

## Code to reproduce the problem

```python
p: pdfplumber.PDF
pdf: pdfplumber.PDF = pdfplumber.open("./buggy.pdf")

p0 = pdf.pages[0]
im = p0.to_image(resolution=150)
im.reset().debug_tablefinder({
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines"
})
print(len(p0.find_tables()))
im.draw_rects(p0.chars)
im.show()
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

[buggy.pdf](https://github.com/jsvine/pdfplumber/files/13866493/buggy.pdf)

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

Debug view should line up correctly.

## Actual behavior

Debug view is offset.

## Screenshots 

![image](https://github.com/jsvine/pdfplumber/assets/154856678/0354ab48-460e-4a41-a4dd-7f6253958003)

Would expect this to line up nicely like other PDFs but it doesn't.

## Environment

- pdfplumber version: 0.10.3
- Python version: 3.9.1
- OS: Mac

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hi @px-xp, thank you for the clear bug report. Luckily, a fix for this has already been made (https://github.com/jsvine/pdfplumber/commit/07d9997ee587723c32e2178be65eea584102bf58) and is available on `develop`. To install that version before it's part of the next release, you can run `pip install -U git+https://github.com/jsvine/pdfplumber@develop`

Here is the result of `im.reset().debug_tablefinder()`:

![image](https://github.com/jsvine/pdfplumber/assets/534702/b14f0c2f-7250-49e4-835f-60b1fd314dab)

**Comment by px-xp** [comment]
Thank you @jsvine. This is a really cool tool!
