### ISSUE TITLE
Extracting devnagiri text.

### ISSUE THREAD

**Issue by aumungray** [jsvine/pdfplumber#1083]
Hello,
Thanks for the amazing library. I see that text extraction is inherited from [pdfminer](https://github.com/pdfminer/pdfminer.six). I have pdfs in different language - Marathi (script is same as Hindi). When I use the following pdf and extract text, it gives gibberish response.
[17 jany 2024.pdf](https://github.com/jsvine/pdfplumber/files/13998932/17.jany.2024.pdf)

The script  - 
```

import pdfplumber

with pdfplumber.open('17 jany 2024.pdf') as pdf:
    # Access individual pages
    for page in pdf.pages:
        # Extract text from the page
        text = page.extract_text()
        # Process the extracted text as needed
        print(text)
```

The output 

`OmJV¥
jagrutloknetajsp@gmail.com
Volume : 21 Issue: 78 Pages : 6 Date Wednesday 17 January 2024 Price : 2 Rs. RNI No.-MAHMAR/2004/16973 Postal Reg.No.-KLR-245/2022-2024
A§H$ 78 nmZo 6 ~wYdma 17 OmZodmar 2024 qH$‘V-2 ê$n¶o
ñd.nr.~r. nmQ>rb ¶m§Mo {d{dY joÌmVrb ¶moJXmZ àoaUmXm¶r : ‘mOr H|$Ðr¶‘§Ìr eaX ndma
O¶qgJnay /à{V{ZYr-
{Z‘{eaJmd ¶Wo o ñdmVÍ§ ¶gZo mZr nr.~r. nmQ>rb gdo m gmgo m¶Q>rM o Zm‘H$aU; ~hCþ Ôeo r¶ g^mJh¥ mMr nm¶mIXw mB©
AmnU ñdVÌ§ ^maVmM oZmJ[aH$
AmhmVo , ¶mM ol¶o ñdmVÍ§¶ gZo mZtÀ¶m
Ë¶mJmbm Amh.o nr.~r. nmQ>rb ¶mZ§ r
‘hmË‘m JmY§ r ¶mÀ§ ¶m {dMmamMm
pñdH$ma H$éZ ñdmVÍ§¶ bT>çmV ^mJ
KoVbm. ñdmV§Í¶mZ§Va H$mX§~ar,
H${dVm {b{hë¶m. dÎ¥mnÌmV H$m‘
H$ob.o Ë¶mZ§ r {d{dY jÌo mV {Xbbo o
¶moJXmZ àoaUmXm¶r Amho, Ago
à{VnmXZ ‘mOr H$|Ðr¶ H$¥fr‘Ì§ r eaX
ndma ¶mZ§ r H$ob.o`

I am guessing it has has to do something with encoding. I found a similar issue in [pdfminer](https://github.com/pdfminer/pdfminer.six/issues/260), but here atleast the response was there in same font. Unlike my response.

Please help.

**Comment by jsvine** [comment]
Hi @aumungray, and thanks for your kind words about `pdfplumber`. The issue you're encountering appears, unfortunately, appears to be deeper than `pdfplumber` or `pdfminer.six`. I say this because when I select some text from the PDF in a standard PDF viewer, copy it, and then paste into a plain text editor, it results in the same kind of gibberish. Does the same occur for you on your computer?

Closing this issue for now, because it seems unlikely that it can be resolved via `pdfplumber`, but feel free to continue the conversation here.

**Comment by aumungray** [comment]
Hi @jsvine . Yes, same occurs on my end. I also found out the root cause. It is due to a custom font used in the pdf. When I copy pasted the gibberish text [here](https://fontsindia.com/fonts/shree-dev7-0701-regular), I got the text back. Is there any method to specify custom font in extract_text function.?

**Comment by jsvine** [comment]
Thanks for the additional detail. Unfortunately, there is not such a feature, and I can't think of how we'd be able to add it to `pdfplumber`. You might have some luck, though, looking for tools that would let you add the font as a resource to the *original* PDF file.
