### ISSUE TITLE
The position of numbers and punctuation marks is incorrect

### ISSUE THREAD

**Issue by lbeing** [jsvine/pdfplumber#1098]
## Describe the bug

*The position of numbers and punctuation marks is incorrect*

## Code to reproduce the problem
pages = pdfplumber.open(filepath).pages
image4 = pages[4].to_image(resolution=150)
image4.draw_rects(page.extract_words())
image4.save("test4.png")

## PDF file

[重型货车新技术与故障诊断_第2版-1-5.pdf](https://github.com/jsvine/pdfplumber/files/14368130/_.2.-1-5.pdf)

## Screenshots
![test4](https://github.com/jsvine/pdfplumber/assets/4525832/3c048c80-1637-4ec0-811c-2d8910e8d9f5)

## Environment

- pdfplumber version:0.10.3
- Python version:3.8.18
- OS: Linux,

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
This looks like it might be an issue with the non-Chinese font definition(s). Have you tried repairing the PDF? (Instructions are in the bug issue template.)

**Comment by jsvine** [comment]
Although repairing the PDF does not seem to fix the issue, I have now taken a closer look and determined that the positioning is unfortunately out of `pdfplumber`'s control. The issue might be with the PDF's font definitions or with how [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six) interprets them.
