### ISSUE TITLE
Do this process pdf columns wise

### ISSUE THREAD

**Issue by yash9999** [jsvine/pdfplumber#110]
If page is divided into 3 part, 
First | second
——————
Third 

How it will read? 
Will it firstly  complete the first section then move to second and then third 

Suggestion will be appreciated 
Thanks in advance

**Comment by jsvine** [comment]
It will depend on the specifics of the PDF, but it will likely parse as:

```python
[
  [ "First", "Second" ],
  [ "Third", None ]
]
```
