### ISSUE TITLE
bottom-to-top text in cell rendered in wrong location in extract_text()

### ISSUE THREAD

**Issue by stef** [jsvine/pdfplumber#1102]
## Describe the bug

A table heading that is written bottom-to-top is being "rendered" in the wrong location when calling extract_text().

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

Yes, the problem persists.

## Code to reproduce the problem

```python
#!/usr/bin/env python

import pdfplumber

# download https://www.europarl.europa.eu/doceo/document/ENVI-AM-751554_EN.pdf into the current directory

with pdfplumber.open('ENVI-AM-751554_EN.pdf') as pdf:
    print(pdf.pages[95].extract_text(layout=True, x_density=3, y_density=13.8, y_tolerance=6.9, keep_blank_chars=True))
```

## PDF file

The test-case in question is on page 96 of https://www.europarl.europa.eu/doceo/document/ENVI-AM-751554_EN.pdf

(pls excuse me, but it seems i am unable to attach files to issues, i tried using the file chooser to attach it, and it didn't report any error, but i fail to see any attached files, thus the link above)

## Expected behavior

The heading is in the right location.

## Actual behavior

The table heading "Sub- groups sg" is rendered at the very bottom of the "page" - reversed. This is the last few lines of output:

```
         EN
                           -buS
                                gs spuorg
```
Only the `EN` is correct, this line should be the last one.

## Environment

- pdfplumber version: 0.10.3
- Python version: 3.11
- OS: Linux

**Comment by jsvine** [comment]
Hi @stef, and thanks for your interest in `pdfplumber`, and for providing both the PDF and the code you used, which really helps. 

The reversed issue can be resolved via `.extract_text(..., vertical_ttb=False)`, telling `pdfplumber` to read non-horizontal text from bottom-to-top instead of top-to-bottom (`_ttb`). When I do that, I get this:

```
        EN                                                                                                                                                                                           
                           Sub-                                                                                                                                                                       
                                groups sg                                                                           
```

That said, yes, the positioning on the page seems incorrect. I'm working on some related updates that should improve this, and I'll use the example you've provided to test it.

**Comment by stef** [comment]
Hey, @jsvine thanks for your kind attention to this issue. i think pdfplumber is a great project, we're migrating to it in our project https://parltrack.eu/. and yes, `vertical_ttb=False` sounds like an excellent tip. For me it is more important that the text is in the correct location, than the text being correctly ordered, but having both of these things being correct is of course the best outcome, so i am very happy and looking forward to any solutions of this issue. btw if you look for some more f-ed up test-cases for pdfs, the european parliament is truly a gold mine :) kudos and thanks!

**Comment by jsvine** [comment]
ParlTrack looks very neat, thanks for sharing! The positional fix is now available in `v0.11.0`, although you'll also get a messages that `vertical_ttb` is being deprecated, in favor of more fine-grained control. Instead, try `char_dir_rotated="btt"`.

The relevant section of the output:

<img width="645" alt="Screenshot" src="https://github.com/jsvine/pdfplumber/assets/534702/8c93e248-e540-46aa-8d25-87fc3050547d">

**Comment by stef** [comment]
i can confirm v0.11 fixes this issue. very impressed by the speed this was handled! thank you very much. this will increase the quality of the data we liberate from the EP. thank you very much. data<3

**Comment by stef** [comment]
one comment, if i may. this `char_dir_rotated="btt"` thingy, with other pdf tools (like GUI viewers) these chars are always in the right position and orientation, without external hand-holding which direction to render them, right? so the thing with the EP pdfs is that they're like pdfs pounded out by a million monkeys, and thus i cannot set this `char_dir_rotated` to any value that will always be correct. is there no automatic way to detect the position and orientation correctly?

anyway, this is very low prio to me, as there is so many other issues with these pdfs that introduce a lot of data corruption and vertical text is quite rare. so i only thought i mention this if you care and have the bandwidth, but for us this really doesn't matter. i am happy as i can be already with your fine fix. thank you again and sorry for bothering and nitpicking on this irrelevant nothingness.

**Comment by jsvine** [comment]
> is there no automatic way to detect the position and orientation correctly?

In theory, there might be: One could look at the order in which the text was encoded in the PDF, and assume that it corresponds to the reading order. Unfortunately, that's not always the case, which is why `pdfplumber` more generally does not depend on original character order for its text extraction.

That said, I could imagine an opt-in, heuristic feature like `autodetect_direction=True`. Have now opened a feature-request issue, although I can't promise I'll make progress on it soon: https://github.com/jsvine/pdfplumber/issues/1109

> thank you again and sorry for bothering and nitpicking on this irrelevant nothingness.

No need to apologize; you shared a clear, use-based idea.
