### ISSUE TITLE
pickle dump not working with pdfplumber PDF object 

### ISSUE THREAD

**Issue by theharshgupta** [jsvine/pdfplumber#111]
I am trying to dump `<class 'pdfplumber.pdf.PDF'>` object using pickle, however I receive `TypeError: cannot serialize '_io.BufferedReader' object` on execution of    
`pickle.dump(pdfplumber.open("first_page_samples.pdf"), outfile)
`

The EXACT Error is: 

`Traceback (most recent call last):
<module>
    pickle.dump(pdf, outfile)
TypeError: cannot serialize '_io.BufferedReader' object`

I have confirmed that pickle is able to dump other objects - and that generated from PDFs like tabula-py - however it seems to have a problem with dumping the pdfplumber.pdf.PDF object! 

Please help.

**Comment by jsvine** [comment]
Hi, @theharshgupta. Unfortunately, custom classes (such as `pdfplumber.pdf.PDF`) don't automatically support pickling. Instead, that support has to be custom-written. For more information on pickling, see here: https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

If someone would like to work on adding pickle support to `pdfplumber`, let me know and we can discuss some possible ways to approach it.
