### ISSUE TITLE
Chinese encoding problem

### ISSUE THREAD

**Issue by LeohomWang** [jsvine/pdfplumber#112]
I'm using python3.6 and trying to parse this PDF table in Chinese with the code snippet below.
https://lll.ntpc.edu.tw/UpLoad/Bulletin/635776106%E5%B9%B4%E7%AB%8B%E6%A1%88%E7%A8%BD%E6%9F%A5%E5%85%AC%E5%91%8A.pdf
```
with pdfplumber.open("tmp.pdf") as pdf:
    first_page = pdf.pages[0]            
    tables = first_page.extract_tables()
    for table in tables:
        for row in table:
            print(row)
```
However, the output becomes string in byte format. Each element in list is <class 'str'>.
Is there some ways to set the encoding of pdfplumber or ways to convert this list of strings to Chinese?

```
['10601\x07C23', '\x07\u1ac0', '1', '25', '\x06\x05ᓜ', 'ȫ\x06\x05ᙐ\x08ᦻMʟX\x07I', '\x06\x05ᓜA\x06\x0838͡1\x06ஹ38\x041͡2\x06', 'ɑஹ>˔ᯑ\x05͡ஹᦈ\x08ᦈ@\x04̞\u0382\x05ஹʞ4\u173f\x07B\nʠ?\x04ᦟᾍ6\x08\x05ᑛ\x04\x07\u2458\x08ʔஹǴ\x04\x08ᧇ\x07\x08\x08˴\x01ᨵ\x05Y\x08\x08\x01A\x06\x05ᓜA', '▲ʟ7Aᐯᦋᗐ\x043\x05\x08ʔ']
['', '', '', '', '', '', '', '\x06\x0836͡4ஹ5\x06⍟\u0382ɍ4I̴\nʠ?\x04Ȅ\x05ᵭᛇஹ>˔ᯑ\x07\u1ac0\x05͡', '']
['10601\x07C24\n10602\x07C01', '\x07\u1ac0\n\x07\u1ac0', '1\n2', '25\n2', '↞\x06ᓜ\nʥ\x06ᓜ', '7`ᦻᳮMʟX\x07I\n\x05\u175eᦻᳮ\x08ᦻMʟX\x07I', '↞\x06ᓜ\x05‐\x0859͡2\x06\nʥ\x06ᓜᦻᓄ\x081\x06120͡3\x06ஹ3\x06\x041', '\x06\x05ᵭᛇஹȄ\x05ᵭᛇஹ\x07\u1ac0\x08Bஹ\x08ᑖ\x08ஹ\x05˯\x04`ஹᦟᾍ6ȜȆஹ̺\x06\x08ஹǴ', '▲ʟ7Aᐯᦋᗐ\x043\x05\x08ʔ\n▲ʟ7Aᐯᦋᗐ\x043\x05\x08ʔ']
```

Thanks :)))

**Comment by jsvine** [comment]
Hi @LeohomWang, and thanks for raising this issue. I'm not certain whether this is solvable through `pdfplumber`, since it may depend on `pdfminer`, but I'll take a look and see if there's a better way to handle cases like these.

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
