### ISSUE TITLE
Extracting text from PDFs with encodings- Identity-H, Roman fails, gives a blank response.

### ISSUE THREAD

**Issue by nishantkumar21stjul** [jsvine/pdfplumber#1132]
## Describe the bug

Extracting text from PDFs with encodings- Identity-H, Roman fails, gives a blank response instead of giving text from PDF [Sample pdf- 
[5092.CID_Overview.pdf](https://github.com/jsvine/pdfplumber/files/15112630/5092.CID_Overview.pdf)].

Output-
![image](https://github.com/jsvine/pdfplumber/assets/157013672/1f71d527-d4bc-44e4-a881-caa2576b4ed3)

Sample Code-
```
import pdfplumber
def pdfProcessing_AgendaExtraction(pdfPath):
    bold_content = []
    agendaList = []
    with pdfplumber.open(pdfPath) as pdf:
        totalpages = len(pdf.pages)
        #print(totalpages)
        for page in range(0,totalpages-1):
            text = pdf.pages[page]
            #print(pdf.pages[0])
            #print(text)
            clean_text = text.filter(lambda obj: obj["object_type"] == "char" and "Bold" in obj["fontname"])
            #print(clean_text.extract_text())
            bold_content.append(clean_text.extract_text())

    #print(bold_content)
    for item in bold_content:
        #print(item)
        #print("*"*20)
        if item.startswith("Agenda"):
            agendaList.append(item)
        else:
            if item.startswith("Annexure"):
                break
            #continue

    #print("-"*50)
    return agendaList

pdfPath = "C:\\Users\\nkumar34\\Desktop\\demo\\demo\\data\\5092.CID_Overview.pdf"
data = pdfProcessing_AgendaExtraction(pdfPath)
print(data)
```
After troubleshooting and bit of research, found below causes (A similar issue has been reported for a different library [[LINK](https://github.com/LibrePDF/OpenPDF/issues/330)]) -

- Encoding Identity-H, Roman causes issues. The same code has been validated with ASCII encoding and it works fine.

![image](https://github.com/jsvine/pdfplumber/assets/157013672/30efcf46-f7e2-4a87-9449-9a16a8bafade)
![image](https://github.com/jsvine/pdfplumber/assets/157013672/81abaf39-704c-4434-a3d8-49fb1fb60693)

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

Yes, didn't worked.

## Expected behavior

Output should extract all the bold text mentioned in the PDF document

## Actual behavior

Output is an Empty List instead of a list of extracted bold texts.

## Environment

- pdfplumber version: 0.11.0

![image](https://github.com/jsvine/pdfplumber/assets/157013672/fc8bd032-84c2-4806-b893-5f367f55cee3)

- Python version: 3.11.6

![image](https://github.com/jsvine/pdfplumber/assets/157013672/891d89a6-4dfe-4f4b-ad64-f5c6625641ef)

- OS: Windows 10 Enterprise

![image](https://github.com/jsvine/pdfplumber/assets/157013672/2b5ab6c2-886e-46ea-8568-db7f8c4f24ff)

**Comment by jsvine** [comment]
As far as I can tell from the code shared above, the blank result here does not come from a problem with `pdfplumber` but rather the fact that the attached PDF does not contain the phrase "Agenda". If I've misunderstood, please update this issue with a simpler example that demonstrates the bug you're seeing.
