### ISSUE TITLE
Nothing founded from a pdf. No pages, no chars, nothing.

### ISSUE THREAD

**Issue by AppleRabbitDENG** [jsvine/pdfplumber#1135]
[1.pdf](https://github.com/jsvine/pdfplumber/files/15186361/1.pdf)

```
import pdfplumber
pdf = pdfplumber.open(r'1.pdf')
for page in pdf.pages:
    text = page.extract_text()#提取文本
    print(text)
```

**Comment by mkl-public** [comment]
Your PDF file is broken, it's cut off at the end. Some PDF processors can repair it, some cannot. But the issue is with the file, not the processors.

**Comment by AppleRabbitDENG** [comment]
thank you. Could you nicely tell me, how do you find that? How can I detect that?

**Comment by jsvine** [comment]
There are probably several ways to determine this, but one is to open the PDF in a plain-text editor. At the bottom, you'll see something like this abrupt ending:

<img width="295" alt="Screenshot" src="https://github.com/jsvine/pdfplumber/assets/534702/a062a357-bfd3-4aef-a585-bad7580d7052">

(And thanks, @mkl-public for responding early on.)
