### ISSUE TITLE
Cannot Target Left-most Column of Data

### ISSUE THREAD

**Issue by muraii** [jsvine/pdfplumber#114]
Hello! I have read similar issues and this too may be a limitation with PDFMiner more than anything with PDFPlumber. Note that I'm on the following setup:

Ubuntu 18.04 in a Virtualbox vm on Windows 10 host
(Anaconda) Python 3.7.3 in a conda env
pdfplumber 0.5.12
pdfminer-six 20181108

Unfortunately I can't attach any documents as they contain sensitive information.

When reading the PDF and extracting the table, I get all five table column headers but only four columns of data. The left-most column is ignored. It doesn't have a left-edge line which I expect is the issue; the other columns have rendered lines, including the right edge of the table.

I've used `text` and `lines` and `lines_strict` for my `vertical_strategy`. Using `text` returns too-little semantic structure. `lines` gives me almost exactly what I want, with the appropriate structure, but misses that first data column. `lines_strict` raises an `IndexError` that I _feel_ is a consequence of having one more column header than data column.

I've defined some values for `explicit_vertical_lines` but they don't seem to be honored. For instance, it looks as if the left-most data location is at about `x = 16.4` (pulling that from the uncompressed PDF itself). Setting `explicit_vertical_lines(16)` to just use the whole height of the page, or `explicit_vertical_lines({'x': 16, 'top': <value>, 'bottom': <value>})` doesn't convince `pdfplumber` to grab that column.

I have also used `.crop(bounding box)` using what seems like an appropriate geometry, but no luck.

I really don't want to push some PEBKAC into an issue but I can't wrap my head around any other solutions.

**Comment by jsvine** [comment]
Hi @muraii. This sounds interesting and perhaps investigating further, but will be very hard to troubleshoot without a concrete PDF to examine. Is there a way to redact the sensitive PDF contents, or to find a similar-but-not-sensitive PDF with the same problem?

**Comment by muraii** [comment]
Just to close this out for anyone who ends up here, the issue was entirely PEBKAC. I found a working value.
