### ISSUE TITLE
Demonstrations / Examples - links are not available

### ISSUE THREAD

**Issue by koda0601** [jsvine/pdfplumber#1142]
## Describe the bug

There is not a b ug in code, but can you please verify links on 
https://pypi.org/project/pdfplumber/ with examples and demonstrations. It seems do not accessible.

Example:
https://pypi.org/project/pdfplumber/examples/notebooks/extract-table-ca-warn-report.ipynb

Thanks a lot.
Very good product!!!

*A clear and concise description of what the bug is.*

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

*Please try running your code with `pdfplumber.open(..., repair=True)` before submitting a bug report.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by cmdlineluser** [comment]
Just in case you have not found them yet - the examples are here on GitHub:

- https://github.com/jsvine/pdfplumber#demonstrations

- https://github.com/jsvine/pdfplumber/blob/stable/examples/notebooks/extract-table-ca-warn-report.ipynb

**Comment by jsvine** [comment]
Thanks, @cmdlineluser — that's correct. Pypi is just the package host, and does not contain all of the materials from the Github repository, which is the canonical source for `pdfplumber`.
