### ISSUE TITLE
Offset in text bounding boxes when parsing mix language documents

### ISSUE THREAD

**Issue by Yaadon** [jsvine/pdfplumber#1167]
## Describe the bug

When I tried to extract words in a mix language document, there was offset in all the English words, and I am not sure whether it is due to pdfplumber or pdfminer.six.

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

yes.
```python
file = "test_api/chinese.pdf"
pdfplumber.repair("test_api/chinese.pdf", outfile="test_api/chinese_repair.pdf")
```

## Code to reproduce the problem

```python
import pdfplumber

if __name__ == "__main__":
    file = "test_api/chinese.pdf"
    doc = pdfplumber.open(file)
    print(len(doc.pages))
    for i, page in enumerate(doc.pages):
        im = page.to_image().outline_words()
        im.draw_rects(page.extract_words())
        im.save(f"test_api/page{i+1}.png")
```

## PDF file

[chinese.pdf](https://github.com/user-attachments/files/16128506/chinese.pdf)

## Expected behavior

I hope the bbox for English words is as accurate as for Chinese characters.

## Actual behavior

There is offset in y-axis for English words.

## Screenshots

![image](https://github.com/jsvine/pdfplumber/assets/56574998/673440dd-cf7a-43f6-b147-83c2b034c9ad)
![image](https://github.com/jsvine/pdfplumber/assets/56574998/6aad5f37-6186-4d26-ba81-a57ad718eae0)

## Environment

- pdfplumber version: 0.11.1
- Python version: 3.10.14
- OS: Linux

## Additional context

I've tried version 0.11.2
```python
page.to_image().outline_words()
```
but it did not help.

**Comment by jsvine** [comment]
Hi @Yaadon, and thank you for providing this example. `pdfplumber` depends on  `pdfminer.six` for coordinate extraction. Have you compared the coordinates output here to the [those in `pdfminer.six`](https://pdfminersix.readthedocs.io/en/latest/tutorial/extract_pages.html)? Are those also off? If so, better to file an issue there. Or does it appear that `pdfplumber` is introducing errors?

**Comment by hl-gl** [comment]
请问找到原因了吗

**Comment by hl-gl** [comment]
请问找到原因了吗

**Comment by Yaadon** [comment]
I've substituted it with `pdfium`, which works perfect for me, and is much faster since it is based on C libraries.

**Comment by jsvine** [comment]
Thanks for noting, @Yaadon. Closing this issue for now, since character-bounding-box calculations are outside the scope of `pdfplumber` (and are instead calculated by `pdfminer.six`).
