### ISSUE TITLE
The rotation configuration set to IndirectObject, which is preventing the PDF from being uploaded.

### ISSUE THREAD

**Issue by zzhangyun** [jsvine/pdfplumber#1176]
## Describe the bug

The rotation configuration for the PDF file is set to IndirectObject(12, 0, 4419697344). When uploading this file, it reports below error:

2024-07-19 14:40:21,146 - werkzeug - INFO - 10.131.0.1 - - [19/Jul/2024 14:40:21] "POST /api/v1/project/6698c33997df8cbbfd8770c0/document/?collection=6698c40f97df8cbbfd8770c1 HTTP/1.0" 500 -
Traceback (most recent call last):
File "/app/server/service/pdf_svc.py", line 767, in get_doc_pages_raw_data
for num_page_index in range(0, len(pdf.pages)):
File "/usr/local/lib/python3.9/site-packages/pdfplumber/pdf.py", line 142, in pages
p = Page(self, page, page_number=page_number, initial_doctop=doctop)
File "/usr/local/lib/python3.9/site-packages/pdfplumber/page.py", line 226, in __init__
self.rotation = _rotation % 360
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

No

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

[Split_Part_1.pdf.zip](https://github.com/user-attachments/files/16360014/Split_Part_1.pdf.zip)

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hmmmm, as far as I'm aware, `IndirectObject(12, 0, 4419697344)` is not a valid value for a PDF's rotation. Given that the PDF loads without without problems when using `pdfplumber.open(path, repair=True)`, I'm closing this issue, but feel free to continue the discussion here.

**Comment by mkl-public** [comment]
Generally any value in a PDF can be given either by a direct or indirect object with some exceptions explicitly mentioned in the spec. 
For the page rotation no restriction is mentioned in the spec, so it may be indirect.

**Comment by jsvine** [comment]
Thank you, @mkl-public and my apologies @zzhangyun; I misunderstood the issue, thinking that the value was literally set to `IndirectObject(12, 0, 4419697344)`. This should now be fixed in [c20cd3b](https://github.com/jsvine/pdfplumber/commit/c20cd3b6172e53a63ad907b2874a8ef2672a57ee).
