### ISSUE TITLE
An unexpected error occurred: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by exoticaitsolutions** [jsvine/pdfplumber#1182]
## Describe the bug

*A clear and concise description of what the bug is.*

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?

*Please try running your code with `pdfplumber.open(..., repair=True)` before submitting a bug report.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

with pdfplumber.open(main_download_file) as pdf:

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior
![Screenshot from 2024-08-12 17-19-26](https://github.com/user-attachments/assets/7df145ee-3418-4d54-b42a-f5d8beae49cf)

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Thank you for your interest in this library, @exoticaitsolutions. Unfortunately, there is not enough information provided to investigate this. Please fill out the details above.
