### ISSUE TITLE
Memory Issue with CroppedPage.parent_page

### ISSUE THREAD

**Issue by mondaychen** [jsvine/pdfplumber#1189]
## Describe the bug

Consider this use case:

```
import pdfplumber
from pdfplumber.page import CroppedPage
from memory_profiler import profile
import gc

path = "sample.pdf"
sections = [(37.0, 72.0), (82.0, 112.0), (122.0, 137.0), (147.0, 362.0)]

@profile
def main():
    doc = pdfplumber.open(path)
    texts = []
    page_crops = []
    for i in range(20):
        page = doc.pages[i]
        for section in sections:
            y0, y1 = section
            page_crops.append(page.crop((0, y0, page.width, y1)))
    for page_crop in page_crops:
        texts.append(page_crop.extract_text())
        page_crop.close()
    gc.collect()

main()
```

The profile output:

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     9     34.5 MiB     34.5 MiB           1   @profile
    10                                         def main():
    11     34.5 MiB      0.1 MiB           1       doc = pdfplumber.open(path)
    12     34.5 MiB      0.0 MiB           1       texts = []
    13     34.5 MiB      0.0 MiB           1       page_crops = []
    14     37.8 MiB      0.0 MiB          21       for i in range(20):
    15     37.8 MiB      3.2 MiB          20           page = doc.pages[i]
    16     37.8 MiB      0.0 MiB         100           for section in sections:
    17     37.8 MiB      0.0 MiB          80               y0, y1 = section
    18     37.8 MiB      0.1 MiB          80               page_crops.append(page.crop((0, y0, page.width, y1)))
    19    325.8 MiB      0.0 MiB          81       for page_crop in page_crops:
    20    325.8 MiB    289.8 MiB          80           texts.append(page_crop.extract_text())
    21    325.8 MiB     -1.9 MiB          80           page_crop.close()
    22    325.8 MiB      0.0 MiB           1       gc.collect()

```
Even when `page_crop.close()` is called, the memory usage is not released. This is because `page_crop.extract_text()` creates cache on its parent page (mostly `_objects`) and was not cleaned up.

It does not help if you have `page.close()` earlier

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     9     35.3 MiB     35.3 MiB           1   @profile
    10                                         def main():
    11     35.4 MiB      0.1 MiB           1       doc = pdfplumber.open(path)
    12     35.4 MiB      0.0 MiB           1       texts = []
    13     35.4 MiB      0.0 MiB           1       page_crops = []
    14     38.3 MiB      0.0 MiB          21       for i in range(20):
    15     38.3 MiB      2.9 MiB          20           page = doc.pages[i]
    16     38.3 MiB      0.0 MiB         100           for section in sections:
    17     38.3 MiB      0.0 MiB          80               y0, y1 = section
    18     38.3 MiB      0.1 MiB          80               page_crops.append(page.crop((0, y0, page.width, y1)))
    19     38.3 MiB      0.0 MiB          80               page.close()
    20    322.8 MiB     -2.5 MiB          81       for page_crop in page_crops:
    21    322.8 MiB    284.8 MiB          80           texts.append(page_crop.extract_text())
    22    322.8 MiB     -5.4 MiB          80           page_crop.close()
    23    322.8 MiB      0.0 MiB           1       gc.collect()
```

If you cleanup all `parent_page`, the memory is under better control. However, as you can imagine this slows down the process a lot since the objects need to be rebuilt a lot of times.

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     9     34.6 MiB     34.6 MiB           1   @profile
    10                                         def main():
    11     34.7 MiB      0.1 MiB           1       doc = pdfplumber.open(path)
    12     34.7 MiB      0.0 MiB           1       texts = []
    13     34.7 MiB      0.0 MiB           1       page_crops = []
    14     37.6 MiB      0.0 MiB          21       for i in range(20):
    15     37.6 MiB      2.8 MiB          20           page = doc.pages[i]
    16     37.6 MiB      0.0 MiB         100           for section in sections:
    17     37.6 MiB      0.0 MiB          80               y0, y1 = section
    18     37.6 MiB      0.1 MiB          80               page_crops.append(page.crop((0, y0, page.width, y1)))
    19     37.6 MiB      0.0 MiB          80               page.close()
    20     68.5 MiB   -212.5 MiB          81       for page_crop in page_crops:
    21     69.0 MiB   -103.3 MiB          80           texts.append(page_crop.extract_text())
    22     69.0 MiB   -310.7 MiB          80           page_crop.parent_page.close()
    23     68.5 MiB   -280.7 MiB          80           page_crop.close()
    24     62.6 MiB     -5.9 MiB           1       gc.collect()
```

To keep the speed I tried to close the 20 pages used in this test (supposed to be the `parent_page`s?) , but the memory is still not fully released. This I don't understand.

```

Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     9     34.8 MiB     34.8 MiB           1   @profile
    10                                         def main():
    11     35.0 MiB      0.1 MiB           1       doc = pdfplumber.open(path)
    12     35.0 MiB      0.0 MiB           1       texts = []
    13     35.0 MiB      0.0 MiB           1       page_crops = []
    14     38.2 MiB      0.0 MiB          21       for i in range(20):
    15     38.2 MiB      3.1 MiB          20           page = doc.pages[i]
    16     38.2 MiB      0.0 MiB         100           for section in sections:
    17     38.2 MiB      0.0 MiB          80               y0, y1 = section
    18     38.2 MiB      0.1 MiB          80               page_crops.append(page.crop((0, y0, page.width, y1)))
    19    325.8 MiB     -6.9 MiB          81       for page_crop in page_crops:
    20    325.8 MiB    282.6 MiB          80           texts.append(page_crop.extract_text())
    21    325.8 MiB     -8.8 MiB          80           page_crop.close()
    22    327.6 MiB  -1095.2 MiB          21       for i in range(20):
    23    327.6 MiB  -1093.4 MiB          20           doc.pages[i].close()
    24    202.9 MiB   -124.7 MiB           1       doc.close()
    25    200.9 MiB     -2.0 MiB           1       gc.collect()
```

## Expected Behavior 
- Better documentation of `parent_page`
- Better way to handle `.close` on CroppedPage?

## Environment

- pdfplumber version: 0.11.3
- Python version: Python 3.11.5 
- OS: Mac

**Comment by mondaychen** [comment]
To be clear I believe this is a pitfall of failure that the object caching (on both cropped page and parent page) can easily be missed https://github.com/jsvine/pdfplumber/blob/stable/pdfplumber/page.py#L716-L722

**Comment by jsvine** [comment]
Hi @mondaychen, and thanks for sharing this. You touch on a few points above, which I'll try to address in order:

> Even when `page_crop.close()` is called, the memory usage is not released. This is because `page_crop.extract_text()` creates cache on its parent page (mostly `_objects`) and was not cleaned up.

Yes, this is intentional, for a few reasons:

- Extracting the objects is computationally intensive, and so caching those objects is very helpful
- The objects are cached on the parent page, so that they can be used by all derivative `CroppedPage` and `FilteredPage` instances
- The cache is not automatically cleared (but rather only parent page deletion or closure) because `pdfplumber` does not know whether the user plans to use the parent page in the future (directly or via additional derivative pages)

> It does not help if you have `page.close()` earlier

In the example shared above, `page.close()` is run before the objects are extracted (which occurs only on the first time a method is used that requires the objects, e.g., `.extract_text()`); so I would indeed not expect it to make a difference.

To optimize your code, I'd suggest doing something like the following:

```python
def main():
    doc = pdfplumber.open(path)
    texts = []
    for i in range(20):
        page = doc.pages[i]
        for section in sections:
            y0, y1 = section
            cropped = page.crop((0, y0, page.width, y1))
            text = cropped.extract_text()
            texts.append(text)
            cropped.close()
        page.close()
    gc.collect()
    return texts
```

(I'm not quite sure why the cropped pages are stored in a list in the original example, and then looped over again, but perhaps you can explain what I'm overlooking.)

> If you cleanup all `parent_page`, the memory is under better control. However, as you can imagine this slows down the process a lot since the objects need to be rebuilt a lot of times.

Indeed; see notes above.

> To keep the speed I tried to close the 20 pages used in this test (supposed to be the `parent_page`s?) , but the memory is still not fully released. This I don't understand.

There [appears to be an unresolved memory leak in `pdfminer.six`](https://github.com/pdfminer/pdfminer.six/issues/580), `pdfplumber`'s main dependency. Unfortunately, there's not much `pdfplumber` can do at the moment to fix that.

Does the information above help?

**Comment by mondaychen** [comment]
Many thanks! This is very helpful.
I have updated my code like you suggested. Originally I created a a list of cropped pages to be passed around to a few different places to further process. I have changed the method now.

**Comment by mondaychen** [comment]
On a second thought, would you like me to submit a PR to add these details in README around `.crop` method?

**Comment by jsvine** [comment]
Hi @mondaychen, and thank you for offering. Feel free (but not obligated) to suggest some language for the documentation.
