### ISSUE TITLE
non-sequential pageid

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#12]
I processed a 2 page document and was surprised that the pageids were '1' and '20'. Until now they'd always been sequential. Is this expected? Using version 0.4.3 on python 2.7.11 and [this file](http://jacobfenton.s3.amazonaws.com/demos/151201DSP-Fond-581-90D.pdf).

**Comment by jsfenfen** [comment]
Ah, the readme says this is possible. Closing.

**Comment by jsvine** [comment]
Yeah, it's a strange (but expected) thing that occurs with some frequency. Seems to be a quirk of certain PDF generators. When I want to assign sequential ids, I typically do something along the lines of:

```python
for i, page in enumerate(pdf.pages):
   [...]
```

... but it might be worth adding a `.page_order` property to each page (or somesuch). Thoughts on (a) that approach, or (b) the property name?

**Comment by jsfenfen** [comment]
Just having .page_order would do it for me. I just wanna be sure content that spans pages can be correctly captured.

**Comment by jsfenfen** [comment]
Actually, now that I think about it, is there *ever* a time (other than debugging I guess) where you'd prefer the 'pageid' over the actual sequential page number? Would adding it as a kwarg to [page](https://github.com/jsvine/pdfplumber/blob/master/pdfplumber/page.py#L11) work (I see that's how it gets called by the cli stuff, dunno if that would cause problems elsewhere).

**Comment by jsvine** [comment]
That's a great point. For the next release, I'll switch to using sequential page numbers, while retaining optional access to the internal page IDs. Followup question: What do you think of zero-indexed vs. 1-indexed page numbers? Typically, I'd lean toward zero-indexing, but I think that folks are so accustomed to PDFs starting at Page 1 that I might go with that.

**Comment by jsfenfen** [comment]
Good question... I think 1-indexing makes sense, just because that's how people think about docs.

**Comment by jsvine** [comment]
A belated note to say: I went with 1-indexing. So the first page of a PDF has `.page_number == 1`.
