### ISSUE TITLE
Form fields and their values do not appear in pdfplumber command line tool output

### ISSUE THREAD

**Issue by ghing** [jsvine/pdfplumber#120]
I ran the `pdfplumber` command line utility (without any arguments) on a PDF that contains form fields with filled in values. As far as I can tell, none of the form values appear in the output CSV. 

Does pdfplumber support detecting form fields/values?

**Comment by jsfenfen** [comment]
Would think it does? Do you have a pdf example and a CLI command that you can post that shows 'em failing to appear?

**Comment by ghing** [comment]
I can't share the example PDF, but I'll try to make an example that will replicate. FWIW, it looks like you can grab form fields/values using pdfplumber: https://stackoverflow.com/questions/3984003/how-to-extract-pdf-fields-from-a-filled-out-form-in-python

**Comment by ghing** [comment]
Ok, I've attached a mock PDF with a filled-in form as well as the CSV output of the `pdfplumber` command:

```
pdfplumber test_pdf_with_form_filled.pdf > test_pdf_with_form_filled.csv
```

[test_pdf_with_form_filled.pdf](https://github.com/jsvine/pdfplumber/files/3299682/test_pdf_with_form_filled.pdf)

```csv
object_type,page_number,x0,x1,y0,y1,doctop,top,bottom,width,height,adv,fontname,size,text,upright
char,1,43.397,50.801,736.310,752.498,39.502,39.502,55.690,7.404,16.188,7.404,GRLPPP+MinionPro-Regular,16.188,T,1
char,1,50.801,55.901,736.310,752.498,39.502,39.502,55.690,5.100,16.188,5.100,GRLPPP+MinionPro-Regular,16.188,e,1
char,1,55.901,60.305,736.310,752.498,39.502,39.502,55.690,4.404,16.188,4.404,GRLPPP+MinionPro-Regular,16.188,s,1
char,1,60.305,63.965,736.310,752.498,39.502,39.502,55.690,3.660,16.188,3.660,GRLPPP+MinionPro-Regular,16.188,t,1
char,1,63.965,66.689,736.310,752.498,39.502,39.502,55.690,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,66.689,73.445,736.310,752.498,39.502,39.502,55.690,6.756,16.188,6.756,GRLPPP+MinionPro-Regular,16.188,P,1
char,1,73.445,82.265,736.310,752.498,39.502,39.502,55.690,8.820,16.188,8.820,GRLPPP+MinionPro-Regular,16.188,D,1
char,1,82.265,88.613,736.310,752.498,39.502,39.502,55.690,6.348,16.188,6.348,GRLPPP+MinionPro-Regular,16.188,F,1
char,1,88.613,91.337,736.310,752.498,39.502,39.502,55.690,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,91.337,99.557,736.310,752.498,39.502,39.502,55.690,8.220,16.188,8.220,GRLPPP+MinionPro-Regular,16.188,w,1
char,1,99.557,102.773,736.310,752.498,39.502,39.502,55.690,3.216,16.188,3.216,GRLPPP+MinionPro-Regular,16.188,i,1
char,1,102.773,106.433,736.310,752.498,39.502,39.502,55.690,3.660,16.188,3.660,GRLPPP+MinionPro-Regular,16.188,t,1
char,1,106.433,112.841,736.310,752.498,39.502,39.502,55.690,6.408,16.188,6.408,GRLPPP+MinionPro-Regular,16.188,h,1
char,1,112.841,115.565,736.310,752.498,39.502,39.502,55.690,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,115.565,120.833,736.310,752.498,39.502,39.502,55.690,5.268,16.188,5.268,GRLPPP+MinionPro-Regular,16.188,a,1
char,1,120.833,123.557,736.310,752.498,39.502,39.502,55.690,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,123.557,127.109,736.310,752.498,39.502,39.502,55.690,3.552,16.188,3.552,GRLPPP+MinionPro-Regular,16.188,f,1
char,1,127.109,133.229,736.310,752.498,39.502,39.502,55.690,6.120,16.188,6.120,GRLPPP+MinionPro-Regular,16.188,o,1
char,1,133.229,137.681,736.310,752.498,39.502,39.502,55.690,4.452,16.188,4.452,GRLPPP+MinionPro-Regular,16.188,r,1
char,1,137.681,147.509,736.310,752.498,39.502,39.502,55.690,9.828,16.188,9.828,GRLPPP+MinionPro-Regular,16.188,m,1
char,1,147.509,150.245,736.310,752.498,39.502,39.502,55.690,2.736,16.188,2.736,GRLPPP+MinionPro-Regular,16.188,.,1
char,1,43.953,54.645,694.026,710.214,81.786,81.786,97.974,10.692,16.188,10.692,GRLPPP+MinionPro-Regular,16.188,M,1
char,1,54.645,60.765,694.026,710.214,81.786,81.786,97.974,6.120,16.188,6.120,GRLPPP+MinionPro-Regular,16.188,o,1
char,1,60.765,65.217,694.026,710.214,81.786,81.786,97.974,4.452,16.188,4.452,GRLPPP+MinionPro-Regular,16.188,r,1
char,1,65.217,70.317,694.026,710.214,81.786,81.786,97.974,5.100,16.188,5.100,GRLPPP+MinionPro-Regular,16.188,e,1
char,1,70.317,73.041,694.026,710.214,81.786,81.786,97.974,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,73.041,76.701,694.026,710.214,81.786,81.786,97.974,3.660,16.188,3.660,GRLPPP+MinionPro-Regular,16.188,t,1
char,1,76.701,81.801,694.026,710.214,81.786,81.786,97.974,5.100,16.188,5.100,GRLPPP+MinionPro-Regular,16.188,e,1
char,1,81.801,87.465,694.026,710.214,81.786,81.786,97.974,5.664,16.188,5.664,GRLPPP+MinionPro-Regular,16.188,x,1
char,1,87.465,91.125,694.026,710.214,81.786,81.786,97.974,3.660,16.188,3.660,GRLPPP+MinionPro-Regular,16.188,t,1
char,1,91.125,93.861,694.026,710.214,81.786,81.786,97.974,2.736,16.188,2.736,GRLPPP+MinionPro-Regular,16.188,.,1
char,1,41.728,48.076,662.869,679.057,112.943,112.943,129.131,6.348,16.188,6.348,GRLPPP+MinionPro-Regular,16.188,F,1
char,1,48.076,54.196,662.869,679.057,112.943,112.943,129.131,6.120,16.188,6.120,GRLPPP+MinionPro-Regular,16.188,o,1
char,1,54.196,58.648,662.869,679.057,112.943,112.943,129.131,4.452,16.188,4.452,GRLPPP+MinionPro-Regular,16.188,r,1
char,1,58.648,68.476,662.869,679.057,112.943,112.943,129.131,9.828,16.188,9.828,GRLPPP+MinionPro-Regular,16.188,m,1
char,1,68.476,71.200,662.869,679.057,112.943,112.943,129.131,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,71.200,74.752,662.869,679.057,112.943,112.943,129.131,3.552,16.188,3.552,GRLPPP+MinionPro-Regular,16.188,f,1
char,1,74.752,77.968,662.869,679.057,112.943,112.943,129.131,3.216,16.188,3.216,GRLPPP+MinionPro-Regular,16.188,i,1
char,1,77.968,83.068,662.869,679.057,112.943,112.943,129.131,5.100,16.188,5.100,GRLPPP+MinionPro-Regular,16.188,e,1
char,1,83.068,86.104,662.869,679.057,112.943,112.943,129.131,3.036,16.188,3.036,GRLPPP+MinionPro-Regular,16.188,l,1
char,1,86.104,92.440,662.869,679.057,112.943,112.943,129.131,6.336,16.188,6.336,GRLPPP+MinionPro-Regular,16.188,d,1
char,1,92.440,95.164,662.869,679.057,112.943,112.943,129.131,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,95.164,100.924,662.869,679.057,112.943,112.943,129.131,5.760,16.188,5.760,GRLPPP+MinionPro-Regular,16.188,1,1
char,1,42.284,48.632,609.457,625.645,166.355,166.355,182.543,6.348,16.188,6.348,GRLPPP+MinionPro-Regular,16.188,F,1
char,1,48.632,54.752,609.457,625.645,166.355,166.355,182.543,6.120,16.188,6.120,GRLPPP+MinionPro-Regular,16.188,o,1
char,1,54.752,59.204,609.457,625.645,166.355,166.355,182.543,4.452,16.188,4.452,GRLPPP+MinionPro-Regular,16.188,r,1
char,1,59.204,69.032,609.457,625.645,166.355,166.355,182.543,9.828,16.188,9.828,GRLPPP+MinionPro-Regular,16.188,m,1
char,1,69.032,71.756,609.457,625.645,166.355,166.355,182.543,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,71.756,75.308,609.457,625.645,166.355,166.355,182.543,3.552,16.188,3.552,GRLPPP+MinionPro-Regular,16.188,f,1
char,1,75.308,78.524,609.457,625.645,166.355,166.355,182.543,3.216,16.188,3.216,GRLPPP+MinionPro-Regular,16.188,i,1
char,1,78.524,83.624,609.457,625.645,166.355,166.355,182.543,5.100,16.188,5.100,GRLPPP+MinionPro-Regular,16.188,e,1
char,1,83.624,86.660,609.457,625.645,166.355,166.355,182.543,3.036,16.188,3.036,GRLPPP+MinionPro-Regular,16.188,l,1
char,1,86.660,92.996,609.457,625.645,166.355,166.355,182.543,6.336,16.188,6.336,GRLPPP+MinionPro-Regular,16.188,d,1
char,1,92.996,95.720,609.457,625.645,166.355,166.355,182.543,2.724,16.188,2.724,GRLPPP+MinionPro-Regular,16.188, ,1
char,1,95.720,101.480,609.457,625.645,166.355,166.355,182.543,5.760,16.188,5.760,GRLPPP+MinionPro-Regular,16.188,2,1
```

**Comment by jsfenfen** [comment]
Huh, that's fascinating, it fails for me too. I wonder if this is an upstream issue with pdfminer: https://stackoverflow.com/questions/54596563/pdfminer-cant-read-pdf-forms-that-require-adobe-acrobat

**Comment by ghing** [comment]
I was able to use pdfminder (as a library, not the command-line tool) directly to grab the data from the form fields. Perhaps the issue is just that pdfplumber doesn't look for form objects wherever it does its object discovery?

**Comment by ghing** [comment]
So I'm pretty ignorant to how this all works, but it looks like pdfplumber [gets objects from the each page's objects](https://github.com/jsvine/pdfplumber/blob/master/pdfplumber/pdf.py#L83). However, from the [PDF spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf), it looks like forms exist at the document label, not at the page level:

<img width="723" alt="Screen Shot 2019-06-18 at 6 03 29 PM" src="https://user-images.githubusercontent.com/110420/59725484-66d7a600-91f3-11e9-9526-e9f97f3f05f3.png">
 
(see page 671 of the spec).

I was able to get the form values like this:

```python
def read_form_fields(f):
    names = []
    values = []

    parser = PDFParser(f)
    doc = PDFDocument(parser)
    try:
        fields = resolve1(doc.catalog['AcroForm'])['Fields']

    except KeyError:
        raise ValueError("PDF file contains no forms.")

    for objref in fields:
        field = resolve1(objref)
        name = field.get('T').decode()
        try:
            value = field.get('V').decode()

        except AttributeError:
            value = None

        names.append(name)
        values.append(value)

    return names, values
```

Does it make sense to collect form fields when grabbing the PDF's objects in `PDF.objects`?

**Comment by jsfenfen** [comment]
Huh, ping @jsvine but that seems like a good idea

**Comment by jsvine** [comment]
Thanks for flagging this, @ghing, and thanks for helping, @jsfenfen! Fascinating. Some good news: It does seem that `pdfplumber` retains `pdfminer`'s access to the form data. E.g., with your example:

```python
pdf = pdfplumber.open("~/Downloads/test_pdf_with_form_filled.pdf")

[
    (f.resolve()["T"], f.resolve()["V"])
    for f in pdf.doc.catalog["AcroForm"].resolve()["Fields"]
]
```

... returns:

```python
[(b'Text1', b'Test value 1'), (b'Text2', b'Test value 2')]
```

I suspect that that solution's a bit brittle, and would require some edge-casing. 

But assuming *that's* possible, then the question becomes how to represent that information. Standard `char` info includes a bunch of things, such as `fontname`, `size`, etc. — computed/resolved information that comes "free" with `pdfminer`'s standard parsing. I'm not exactly sure how that'd work with these form fields. (Any AcroForm experts out there?)

Perhaps it makes sense to start by providing a simple method or property that returns just the basics for each field for now:

- label
- text
- bounding box

Something like, `my_page.form_fields` or `my_page.get_form_fields()`.

Thoughts?

One other tricky thing: I'm not quite sure how to tell what page each form field is on. But I can experiment with some examples/tests.

**Comment by ghing** [comment]
I feel like the clearest way to address this is through updated documentation. When I first encountered this problem, I didn't know that the form field text was handled differently than other PDF text.

It would have been really helpful to have documentation that flagged that:

- Form field values are handled differently from regular PDF text.
- pdfplumber doesn't handle form fields.
- Form fields and values can be obtained through pdfplumber's wrapper of the underlying pdfminer API.

I feel like pdfplumber's main utility is to offer insight into the position of text or curve elements to allow users to scrape that information from PDFs where the data is consistently positioned but by virtue of the file format, unstructured.

PDF forms are a little different because there is more structure. I found it really easy to grab data from the forms because the form field names closely matched their labels (thanks to the PDF author), but moreover, because the fields were ordered in the order they appeared on the pages.

So, I think it's ok to not try to cram forms into pdfplumbers existing idiom, and I'm not sure if adding a high-level method to grab forms really adds that much value. I'd be happy to help code this up, but I think what would have been most useful to me a few days ago was just a heads-up that forms are handled differently and that one has to use lower-level APIs to access their data.

Let me know if you think a documentation fix is okay and I'm happy to submit a pull request.

**Comment by jsvine** [comment]
That sounds entirely reasonable, @ghing, and thank you for suggesting it. Looking forward to reading what you whip up!

**Comment by ghing** [comment]
Dropping this here for future reference: PYPDF2's [PyPDF2.PdfFileReader.getFields](https://pythonhosted.org/PyPDF2/PdfFileReader.html#PyPDF2.PdfFileReader.getFields) is a high-level API for getting form fields.

**Comment by jsvine** [comment]
Thanks!
