### ISSUE TITLE
problem for read table content

### ISSUE THREAD

**Issue by aaferrero** [jsvine/pdfplumber#121]
when I used p.extract_tables() method,one or more columns contents were missing. 
<img width="640" alt="5786746d4668b2c6c7ee001a018cbad" src="https://user-images.githubusercontent.com/47381179/59858063-d6dd5c00-93ac-11e9-9873-69e3e1f53f66.png">
<img width="420" alt="cb80dc7e2b7ed9f8df992383273e7ae" src="https://user-images.githubusercontent.com/47381179/59858065-d6dd5c00-93ac-11e9-9eb6-7e90c64e9180.png">

**Comment by jsvine** [comment]
Hmm, it's difficult to tell what might be happening without more information. Can you provide the PDF, plus the code you used? And have you tried adjusting the [table extraction settings](https://github.com/jsvine/pdfplumber#table-extraction-settings)?

**Comment by aaferrero** [comment]
Can you give me e-mail or any other contact information so that I can provide those，thanks sincerely.

**Comment by aaferrero** [comment]
Hi, I provide three files, one was correct, two had some problems which some values could not be recognized,more details should be found when code was ran.








------------------ 原始邮件 ------------------
发件人: "Jeremy Singer-Vine"<notifications@github.com>;
发送时间: 2019年6月20日(星期四) 晚上11:12
收件人: "jsvine/pdfplumber"<pdfplumber@noreply.github.com>;
抄送: "Ferrero"<402059208@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jsvine/pdfplumber] problem for read table content (#121)




Hmm, it's difficult to tell what might be happening without more information. Can you provide the PDF, plus the code you used? And have you tried adjusting the table extraction settings?

**Comment by jsvine** [comment]
Hm, I don't see any files. My contact information can be found here: https://www.jsvine.com/

**Comment by aaferrero** [comment]
Hi，I gave files to your contact email address.  Could you receive it?




------------------ 原始邮件 ------------------
发件人: "Jeremy Singer-Vine"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 凌晨2:47
收件人: "jsvine/pdfplumber"<pdfplumber@noreply.github.com>;
抄送: "Ferrero"<402059208@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jsvine/pdfplumber] problem for read table content (#121)




Hm, I don't see any files. My contact information can be found here: https://www.jsvine.com/

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
