### ISSUE TITLE
how to extract table with invisible lines

### ISSUE THREAD

**Issue by cqluohong** [jsvine/pdfplumber#123]
Like the table below, there are 4 columns per row, but I can't get the correct results when I use pdfpumber to extract.

**Comment by cqluohong** [comment]
![aa (1)](https://user-images.githubusercontent.com/41861288/60098559-5fcb0d80-9788-11e9-990a-b3bad2a94f0b.png)

**Comment by OisinMoran** [comment]
Have you tried cropping to just the table you want to extract before running the extraction?
Another thing to try would be playing around with the parameters (it looks like increasing the `snap_tolerance` might work here).

**Comment by cqluohong** [comment]
> Have you tried cropping to just the table you want to extract before running the extraction?
> Another thing to try would be playing around with the parameters (it looks like increasing the `snap_tolerance` might work here).

**Comment by OisinMoran** [comment]
So pdfplumber "works best on machine-generated, rather than scanned, PDFs". There is no OCR capability. If you can share the actual PDF you are trying to extract a table from it can help with debugging the issue.

**Comment by cqluohong** [comment]
> So pdfplumber "works best on machine-generated, rather than scanned, PDFs". There is no OCR capability. If you can share the actual PDF you are trying to extract a table from it can help with debugging the issue.

[430027-北科光大-2017年年度报告.pdf](https://github.com/jsvine/pdfplumber/files/3344775/430027-.-2017.pdf)
I want to extract tableswith page 47- 57

**Comment by luoqygit** [comment]
If you don't mind using an alpha version, you can switch to 0.6-alpha, and use 'snap_y_tolerance' when calling 'page.extract_tables()'.
`tabs = page.extract_tables( { 'snap_y_tolerance': 6} )`
You can replace 6 with whatever value you want.

Please refer to 0.6-alpha documents and  #51 for details.

**Comment by jsvine** [comment]
Thanks @luoqygit and @OisinMoran! Cleaning up old issues. Feel free to reopen @cqluohong if you'd like to continue the discussion.

**Comment by clj55** [comment]
Hi I'm facing issues extracting the invisible tables too. I can't crop the page to specific coordinates of the table because I'm running the program on multiple PDFs where the table can appear in different positions. 

[Customer Information.pdf](https://github.com/user-attachments/files/15922643/Customer.Information.pdf)

I tried it with these table_settings: 
```
table_settings={
    "vertical_strategy":"text",
                "text_keep_blank_chars":True,
                "horizontal_strategy":"text",
                }
```

But it recognised the paragraph text as a table too
<img width="545" alt="customer_info" src="https://github.com/jsvine/pdfplumber/assets/103747880/8bef3510-9f8b-4ca3-811e-07f5dbaec5b7">
