### ISSUE TITLE
TypeError: WordExtractor.__init__() got an unexpected keyword argument '*' when running extract_table  

### ISSUE THREAD

**Issue by palladium123** [jsvine/pdfplumber#1232]
## Describe the bug

*A clear and concise description of what the bug is.*
Get the above error when running `extract_table `with `table_settings "vertical strategy' = 'text'` and `'text*_'` specified. 

## Have you tried [repairing](https://github.com/jsvine/pdfplumber/blob/stable/docs/repairing.md) the PDF?
No, but I don't think the pdf is the issue - for some reason pdfplumber can't detect Ghostscript on my local environment. Tried another pdf with no luck either. 

## Code to reproduce the problem
```
import pdfplumber

file=r"D:\rail.pdf"

pdf =pdfplumber.open(file)
[rail.pdf](https://github.com/user-attachments/files/18022926/rail.pdf)

page=pdf.pages[170]
table=page.extract_table(table_settings={
    "vertical_strategy": "text", 

    "text_*": "Criteria"  }                             
                                        
                               )
print(table)
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

## Expected behavior

Successful parsing.

## Actual behavior
This traceback: 

` File "D:\pdf_loader.py", line 8, in <module>
    table=page.extract_table(table_settings={
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\page.py", line 500, in extract_table
    table = self.find_table(tset)
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\page.py", line 476, in find_table
    tables = self.find_tables(tset)
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\page.py", line 470, in find_tables
    return TableFinder(self, tset).tables
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\table.py", line 589, in __init__
    self.edges = self.get_edges()
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\table.py", line 619, in get_edges
    words = self.page.extract_words(**(settings.text_settings or {}))
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\page.py", line 544, in extract_words
    return utils.extract_words(self.chars, **kwargs)
  File "c:\Users\Kirigiri\AppData\Local\Programs\Python\Python310\lib\site-packages\pdfplumber\utils\text.py", line 698, in extract_words
    return WordExtractor(**kwargs).extract_words(chars, return_chars)
TypeError: WordExtractor.__init__() got an unexpected keyword argument '*'`

## Environment

- pdfplumber version: latest version. 
- Python version: [e.g., 3.10.4]
- OS: [Win11]

**Comment by palladium123** [comment]
[Uploading rail.pdf…]()

**Comment by palladium123** [comment]
[rail.pdf](https://github.com/user-attachments/files/18022992/rail.pdf)

**Comment by mkl-public** [comment]
In your description you talk about `'text*_'` but in your code there is `"text_*"` (switched order of asterisk and underscore).

**Comment by palladium123** [comment]
Sorry, typo in the description. The actual key for the` table_setting `argument (a dictionary) is `text_*`, which is what I used in my code. See:

https://github.com/jsvine/pdfplumber?tab=readme-ov-file#table-extraction-settings

**Comment by cmdlineluser** [comment]
The `*` is a wildcard/placeholder, it is not meant to be passed literally:

> All settings prefixed with `text_` are then used when extracting text from each discovered table. All possible arguments to `Page.extract_text(...)` are also valid here.

It means you can pass `text_anything` e.g. if you pass `text_layout = True` it will be parsed as `layout = True` internally and given to the text extraction method.


What are trying to do when you use `"text_*": "Criteria"`?

**Comment by palladium123** [comment]
Ah right I see. I misunderstood the docs - I thought the 'text' keyword is to specify the text that is used to try and deduce the imaginary line of the table when 'vertical strategy' is set to 'text. 

Mea culpa.
