### ISSUE TITLE
 ImageWarning: CorruptImageProfile `xmp'

### ISSUE THREAD

**Issue by oliverbj** [jsvine/pdfplumber#125]
I am trying to save a PDF output as an image as described in the docs:
with pdfplumber.open(path_to_pdf_file) as pdf:
        first_page = pdf.pages[0]
        im = first_page.to_image()
        im.save(save_path + '/debug.png')

However above code results in an error:
```
/usr/local/lib/python3.7/site-packages/wand/image.py:6425: ImageWarning: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1772
  self.raise_exception()
```

If I choose another PDF file I don't get above error. Has anyone experienced this before?

**Comment by jsvine** [comment]
I haven't, but it seems there may be a relevant (and recent) thread here: http://www.imagemagick.org/discourse-server/viewtopic.php?t=35171&start=15

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
