### ISSUE TITLE
Missing last row and column when using explicit verical and horizontal lines with curves+edges

### ISSUE THREAD

**Issue by samkit-jain** [jsvine/pdfplumber#127]
Using the table setting like
```
{
    "vertical_strategy": "explicit",
    "horizontal_strategy": "explicit",
    "explicit_vertical_lines": p.curves+p.edges,
    "explicit_horizontal_lines": p.curves+p.edges
}
```

for cases when 
```
{
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines"
}
```

is unable to identify the table, the last row and the last column gets skipped from the resulting table.

Output of `debug_tablefinder` (same happens for the last column):
![image](https://user-images.githubusercontent.com/15127115/61201953-cac29100-a703-11e9-93ce-eada0ee2f6fa.png)

When doing a `draw_rects(p.curves)` or `draw_lines(p.curves)`, every line in the table is correctly detected.

**Comment by jsvine** [comment]
Interesting. It's a bit difficult to troubleshoot without the actual PDF. Is that something you can share?

And although it looks like the horizontal and vertical lines intersect properly, it might still be worth trying to tweak the [`snap_tolerance` and `join_tolerance` settings](https://github.com/jsvine/pdfplumber#table-extraction-settings). Does that make any difference?

**Comment by samkit-jain** [comment]
Here is the [PDF](https://github.com/jsvine/pdfplumber/files/3402705/ttt1.pdf). Do note that I removed all the text from the PDF but you can still reproduce the issue.

Result of `debug_tablefinder`
![ttt1](https://user-images.githubusercontent.com/15127115/61390776-095d7480-a8d9-11e9-81df-59ba202f9dc3.png)
FYI, the long red line from the top left corner to the bottom right corner didn't appear when run on the original PDF.

**Comment by jsvine** [comment]
Thanks for sharing. This bug seems to be caused by how `pdfplumber`'s table logic handles `curve` objects. I haven't quite yet nailed down ultimate cause yet, but this should work for you:

```python
def curves_to_edges(cs):
    edges = []
    for c in cs:
        edges += pdfplumber.utils.rect_to_edges(c)
    return edges

table = page.find_tables({
    "vertical_strategy": "explicit",
    "horizontal_strategy": "explicit",
    "explicit_vertical_lines": curves_to_edges(page.curves),
    "explicit_horizontal_lines": curves_to_edges(page.curves),
})[0]

page.to_image().draw_rects(table.cells)
```

**Comment by samkit-jain** [comment]
Thanks for the helper code @jsvine The table extraction is working well with this.
