### ISSUE TITLE
Adding a delimiter option for extract_text()

### ISSUE THREAD

**Issue by shivampatel8** [jsvine/pdfplumber#128]
Currently it functions as adding a space between the words that exceed the tolerance. Looking at the code It would be quite simple to add the delimiter option. I would like to do this.

**Comment by na4raitda** [comment]
I really need this option...
For I python newbie, it's difficult to parse since there are whitespaces everywhere.

**Comment by jsvine** [comment]
Thanks, @shivampatel8 for raising this, and my apologies for the delay in responding. I'm trying to catch up on old issues. Are you still interested to contribute this code? If so, feel free to submit a PR. Otherwise, I will add it to my todo list.

**Comment by shivampatel8** [comment]
I have a pull request open for this waiting for your approval.

**Comment by jsvine** [comment]
Ah, right! My apologies, I didn’t see it referenced here. Closing this issue for now; we can continue the discussion in the PR. Thanks!
