### ISSUE TITLE
checkboxes / LTRects + LTCurves

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#13]
I've been messing with a pdf that uses checkboxes that are built with an LTRect and (if checked) two LTCurves (see below; objs[44] is the rectangle and 45 and 46 are used to make the lines of an X).(I was expecting that the checkboxes would be embedded as images and it took me a while to realize they weren't--though having them as rect/curves certainly saves space).   

Not really sure how common this is--but figuring out if they are checked is critical to making sense of the form.

I'm hacking this out with PDF miner -- but wondered if you had thoughts on making pdfplumber able to extract this. I think earlier versions supported more types of objects. Although the 'pts' show each point of a curve, I don't actually need them here--just testing if there's an LTCurve inside the LTRect is equivalent to whether the box is checked. I dunno. 

```
>>>page0._objs[44].__class__
<class 'pdfminer.layout.LTRect'>
>>> page0._objs[44].__dict__
{'linewidth': 0.75, 'height': 9.20999999999998, 'width': 9.210000000000008, 'bbox': (78.72, 263.22, 87.93, 272.43), 'y1': 272.43, 'y0': 263.22, 'x0': 78.72, 'x1': 87.93, 'pts': [(87.93, 272.43), (78.72, 272.43), (78.72, 263.22), (87.93, 263.22)]}
>>> page0._objs[45].__class__
<class 'pdfminer.layout.LTCurve'>
>>> page0._objs[45].__dict__
{'linewidth': 0.51, 'height': 9.449999999999989, 'width': 9.450000000000003, 'bbox': (78.6, 263.1, 88.05, 272.55), 'y1': 272.55, 'y0': 263.1, 'x0': 78.6, 'x1': 88.05, 'pts': [(78.6, 272.55), (88.05, 263.1)]}
>>> page0._objs[46].__class__
<class 'pdfminer.layout.LTCurve'>
>>> page0._objs[46].__dict__
{'linewidth': 0.51, 'height': 9.449999999999989, 'width': 9.450000000000003, 'bbox': (78.6, 263.1, 88.05, 272.55), 'y1': 272.55, 'y0': 263.1, 'x0': 78.6, 'x1': 88.05, 'pts': [(88.05, 272.55), (78.6, 263.1)]}
```

**Comment by jsvine** [comment]
Fascinating! I haven't needed to use `LTCurves` before, so I overlooked them while building pdfplumber. I believe, however, they should still be accessible via something like:

```python
p0 = my_pdf.pages[0]
curves = p0.objects["curves"]
```

Does that work? If so, I can add a convenience property a la `page.rects`. 

And would you be able to share the PDF? If you're comfortable with it being public, I'd love to include it in `pdfplumber`'s tests. And even if you don't want it public, it'd be helpful to test privately.

**Comment by jsfenfen** [comment]
Wow. That's great. It's actually p1.objects["curve"] but it seems to work. 

Lemme get back to you on the pdf. As usual it's someone else's docs I'm working with, lemme check with them.

**Comment by jsfenfen** [comment]
Ok, am reopening with sample page and gist the works (for it). 
Here's an example doc: http://www.jacobfenton.com.s3.amazonaws.com/pdf/151201DSP-Fond-581-90D.pdf
This was a hack I used on this stuff: https://gist.github.com/jsfenfen/34208d76eb5587896f9c235df5de289c

**Comment by jsvine** [comment]
Big thanks! I'll incorporate this into the tests. And I don't want to jinx it, but `v0.5.0` is fairly close to release; a convenience `page.curves` accessor will be in it.

**Comment by jsvine** [comment]
So, I jinxed it. Unless "close" means "nine months from now." Earlier today, I finally shipped `v0.5.0`. Your gist appears to be working. Output:

```sh
Found directory: .
        Handling 1 - .  151201DSP-Fond-581-90D.pdf
found 10 rects and 10 curves
 5 are checked
TOTAL OF 1 PROCESSED
```

I've also added a test, based on your gist, in ba9d7ab0.

Thanks again for this!

**Comment by jsvine** [comment]
p.s., As of [v0.5.2](https://github.com/jsvine/pdfplumber/commit/b44f2dc3bcedb40ecdfbbd5297e81bcd997b0b6e), you can now access the points in a curve. See [this new demo](https://github.com/jsvine/pdfplumber/blob/master/examples/notebooks/ag-energy-roundup-curves.ipynb) for an example.

**Comment by jsfenfen** [comment]
Wow, that's awesome! You could probably recover the scale of that graph by
extracting the value labels on each axis. I wonder how well this would work
with maps, assuming they were labelled...

Also: didn't know that about lineto/moveto--that almost sounds like a bug
in pdfminer, no? It seems like it should be there in some form here:
https://github.com/euske/pdfminer/blob/master/pdfminer/pdfinterp.py#L463
('m' for moveto and 'l' for lineto) but no idea what happens with that...

**Comment by jsvine** [comment]
> You could probably recover the scale of that graph by extracting the value labels on each axis. I wonder how well this would work with maps, assuming they were labelled...

Fun ideas!

> Also: didn't know that about lineto/moveto--that almost sounds like a bug in pdfminer, no? It seems like it should be there in some form here: https://github.com/euske/pdfminer/blob/master/pdfminer/pdfinterp.py#L463 ('m' for moveto and 'l' for lineto) but no idea what happens with that...

Exactly. I don't think it's a bug, precisely — the `points` don't claim to be fully-specified paths —  but instead just a missing feature. But I think it should be possible, perhaps with a bit of monkey-patching, to grab the full path from `pdfminer`.
