### ISSUE TITLE
speed performance of pdfplumber

### ISSUE THREAD

**Issue by betterRunner** [jsvine/pdfplumber#131]
Here there, I found pdfplumber is somehow time-consuming, running in my i5 computer, it took nearly 10 seconds to parse a 60 pages PDF (just iter the page.chars without further calculation or printing). I want to ask is this the normal performance of pdflumber? If so, how can i improve the performance (such as not open the output of table and other data)?
By the way, I found each operation `chars = page.chars` is ms level but it is just an attribute access operation, why is that?

Thank you in advanced!

**Comment by jsvine** [comment]
Hi @betterRunner,

> I want to ask is this the normal performance of pdflumber?

Speeds can vary depending on the PDF. At its core, `pdfplumber` is built on [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six), so much of the speed will depend on how your PDF is handled by that library. It's worth checking how `pdfminer.six`'s basic parsing compares, in terms of speed, to `pdfplumber` for your PDF. If you notice a big difference, feel free to re-open this issue and let me know.

> By the way, I found each operation chars = page.chars is ms level but it is just an attribute access operation, why is that?

`page.chars` is a computed property, which accesses the `"char"` key from the `page.objects` dictionary: https://github.com/jsvine/pdfplumber/blob/master/pdfplumber/container.py#L34

**Comment by betterRunner** [comment]
@jsvine got it, thanks for the explanation.

**Comment by RamgopalPareek** [comment]
@jsvine I am processing a pdf of 1000 page to extract tables from each page and its taking about 95 sec for that and still plumber have memory Hogging issue if I go page by and not close the PDF 
Any suggestion to make the process faster

**Comment by jsvine** [comment]
@RamgopalPareek You might try processing the PDF just 10 or 100 pages at a time, using the `pdfplumber.open(..., pages=[1, 2, 3, ...])`, etc.
