### ISSUE TITLE
How to load remote pdf?

### ISSUE THREAD

**Issue by JiangTaoGZU** [jsvine/pdfplumber#132]
I want to crawl some pdf tables on Internet,but the official document seems only shows the way to load native pdf files.Let me know if their are any methods to load remote pdf files or not.Thanks a lot.

**Comment by luoqygit** [comment]
My solution is as below, hope it would be helpful.

```

import requests
import pdfplumer
from io import BytesIO

...
url = "http://some.web.site/filename.pdf"
rq = requests.get(url)
try:
    pdf = pdfplumber.load(BytesIO(rq.content))

```

**Comment by jsvine** [comment]
Thank you, @luoqygit, that's exactly what I would suggest for @JiangTaoGZU as well.

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into  DataFrame or JSON rather Binary Stream,It is more convenient to extract.
`
import tabula
       df = tabula.read_pdf(s, encoding='utf-8',pages='all')   
            #返回一个dataframe对象并对它进行按行遍历
            for index, row in df.iterrows():
                self.send_message(self.project_name, {
                "time": row[0],
                "donor": row[1],
                "projecct":row[5],
                "money":row[3],
`

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.
`import tabula`
` s=response.url`
` df = tabula.read_pdf(s, encoding='utf-8',pages='all') `
` for index, row in df.iterrows():`
`   self.send_message(self.project_name, {`
`   "time": row[0],`
`   "donor": row[1],`
`   "projecct":row[5],`
`    "money":row[3],`

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.

`
import tabula

...
s=response.url
df = tabula.read_pdf(s, encoding='utf-8',pages='all')
for index, row in df.iterrows():
self.send_message(self.project_name, {
"time": row[0],
"donor": row[1],
"projecct":row[5],
"money":row[3],
`

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.
```
import tabula

...
s=response.url
df = tabula.read_pdf(s, encoding='utf-8',pages='all')
for index, row in df.iterrows():
self.send_message(self.project_name, {
"time": row[0],
"donor": row[1],
"projecct":row[5],
"money":row[3],
```

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.
```
import tabula
...
s=response.url
df = tabula.read_pdf(s, encoding='utf-8',pages='all')
for index, row in df.iterrows():
    self.send_message(self.project_name, {
    "time": row[0],
    "donor": row[1],
    "projecct":row[5],
    "money":row[3],
  },url="%s%s" % (response.url,index))
```

**Comment by JiangTaoGZU** [comment]
Thank you @luoqygit ,I have deal with this problem by another way,I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to traverse.
```
import tabula
...
s=response.url
df = tabula.read_pdf(s, encoding='utf-8',pages='all')
for index, row in df.iterrows():
    self.send_message(self.project_name, {
    "time": row[0],
    "donor": row[1],
    "projecct":row[5],
    "money":row[3],
  },url="%s%s" % (response.url,index)
```
