### ISSUE TITLE
Can not parse the pages with watermark

### ISSUE THREAD

**Issue by betterRunner** [jsvine/pdfplumber#133]
it seems like pdfplumber can not parse the pages with the watermark.

Only the first page of the attached pdf (without the watermark) can be parsed while the others can not.
Is this issue about the watermark?
Thanks in advanced!
[watermark.pdf](https://github.com/jsvine/pdfplumber/files/3489550/watermark.pdf)

**Comment by jsvine** [comment]
Hi @betterRunner, this seems to be a malformed PDF; `pdfplumber` (and likely other tools) thinks there is only one page. To fix this, try repairing the PDF with a tool such as [cpdf](https://community.coherentpdf.com/):

```sh
cpdf watermark.pdf -o watermark-fixed.pdf
```

(Doing that worked for me.)

**Comment by betterRunner** [comment]
@jsvine, thanks for your answer. So this has nothing to do with the watermark, right?
