### ISSUE TITLE
read image pdf exception

### ISSUE THREAD

**Issue by buctllx** [jsvine/pdfplumber#134]
i attempt to read a image pdf occur a error below  (pdfplumber==0.5.12)
pdfminer.psparser.PSSyntaxError: Invalid dictionary construct

**Comment by jsvine** [comment]
It's hard to know what the problem might be without more information. Can you post:

- The PDF itself
- The code you're using
- The full error

If, however, you're trying to read a PDF that is a series of images, there is no solution. `pdfplumber` only works with text-based PDFs.

**Comment by akshowhini** [comment]
@buctllx pdfplumber or any other OSS works only on text PDF.

**Comment by jsvine** [comment]
(Thank you @akshowhini.)
