### ISSUE TITLE
Is there any way to open an online pdf file? like pdfminer

### ISSUE THREAD

**Issue by kzs569** [jsvine/pdfplumber#135]
In pdfminer3k, I can open an online pdf file like code below 
`  
    request = Request(url=_path, headers={'User-Agent': random.choice(user_agent)})  
    fp = urlopen(request) 
    praser_pdf = PDFParser(fp)
`
but when I tried this on pdfplumber, I only get error
`
TypeError                                 Traceback (most recent call last)
<ipython-input-26-da575a0d284b> in <module>
      7 request = Request(url=url, headers={'User-Agent': UserAgent().random})  
      8 fp = urlopen(request)
----> 9 pdf = pdfplumber.open(fp)
     10 
     11 pdf.pages[0].to_image()

/usr/local/lib/python3.6/dist-packages/pdfplumber/pdf.py in open(cls, path, **kwargs)
     46     @classmethod
     47     def open(cls, path, **kwargs):
---> 48         return cls(open(path, "rb"), **kwargs)
     49 
     50     def process_page(self, page):

TypeError: expected str, bytes or os.PathLike object, not HTTPResponse
`

Is there any possible solution for online pdf extraction?

**Comment by jsvine** [comment]
Yes, there is; see here: https://github.com/jsvine/pdfplumber/issues/132#issuecomment-519426102

**Comment by JiangTaoGZU** [comment]
I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.
```
import tabula
...
# Read remote pdf into DataFrame
df2 = tabula.read_pdf("https://github.com/tabulapdf/tabula-java/raw/master/src/test/resources/technology/tabula/arabic.pdf")
```
[https://github.com/chezou/tabula-py](url)

**Comment by JiangTaoGZU** [comment]
@kzs569 I think this way is better beacause it can extract all tables into DataFrame or JSON rather Binary Stream,It is more convenient to extract.
```
import tabula
...
# Read remote pdf into DataFrame
df2 = tabula.read_pdf("https://github.com/tabulapdf/tabula-java/raw/master/src/test/resources/technology/tabula/arabic.pdf")
```
[https://github.com/chezou/tabula-py](url)
