### ISSUE TITLE
Text Pdf not found table

### ISSUE THREAD

**Issue by bakefish** [jsvine/pdfplumber#137]
i attempt to open a text pdf and extract table , but result is not found table.

Codes as below: 

`import pdfplumber

pdffile=r"c:\Users\bakef\Documents\OPQW 2017-final.pdf"
pdf=pdfplumber.open(pdffile)          
spage=pdf.pages[0]
print(spage.extract_tables())
spage=pdf.pages[1]
print(spage.extract_tables())`

result:
[]
[]

File:
[OPQW 2017-final.pdf](https://github.com/jsvine/pdfplumber/files/3551679/OPQW.2017-final.pdf)

**Comment by jsvine** [comment]
If you run `spage.to_image().debug_tablefinder()`, what do you see?

**Comment by bakefish** [comment]
Not found any table or lines

**Comment by bakefish** [comment]
![image](https://user-images.githubusercontent.com/34408571/64087485-e810f480-cd6f-11e9-8ec4-bec1fa133eeb.png)

**Comment by bakefish** [comment]
![image](https://user-images.githubusercontent.com/34408571/64087577-4342e700-cd70-11e9-8ceb-5783217972e7.png)

**Comment by jsvine** [comment]
Hi, @bakefish. Yep, that seems to be the issue. This is a strange PDF; most PDFs represent lines as lines, but this represents them as `curve` objects. In most cases, people do *not* want to include curve objects in their table extraction. But you can explicitly tell `pdfplumber` to use them like so:

```python
 def curves_to_edges(cs):
    edges = []
    for c in cs:
        edges += pdfplumber.utils.rect_to_edges(c)
    return edges

spage.extract_table({
    "vertical_strategy": "explicit",
    "horizontal_strategy": "explicit",
    "explicit_vertical_lines": curves_to_edges(spage.curves),
    "explicit_horizontal_lines": curves_to_edges(spage.curves),
})
```

Output:

```
[['No',
  'Project',
  None,
  'Class01',
  None,
  None,
  'Class02',
  None,
  None,
  None,
  None,
  'SubClass03'],
 [None,
  None,
  None,
  'SubClass01001',
  'SubClass01002',
  'SubClass01003',
  'SubClass020\n01',
  'SubClass020\n02',
  'SubClass02003',
  'SubClass02004',
  'SubClass02005',
  None],
 [None, None, None, '1', '2', '3', '4', '5', '6', '7=5-6', '8', '9(2-5)'],
 ['1',
  'Project01',
  None,
  '31,890,599.52',
  '3,337,360.71',
  '17,577,827.08',
  '31,667,490.91',
  '2,427,128.93',
  '0',
  '0',
  '13,403,732.66',
  '910,231.78'],

...
```
