### ISSUE TITLE
Table finder not working on table with first and last columns blank

### ISSUE THREAD

**Issue by alexanderwhatley** [jsvine/pdfplumber#140]
I'm trying to extract a table from a pdf whose first and last columns are blank. This appears to be confusing the table finder however. 
I use the following code to attempt to crop and then extract the table:
```
import pdfplumber
pdf = pdfplumber.open("adversarial_example.pdf")
page = pdf.pages[0]
cropped_page = page.crop((0, 0, page.width, 122))
cropped_page.to_image()
```
![image](https://user-images.githubusercontent.com/14192598/64295156-75497a00-cf25-11e9-9766-0aab81277d9b.png)
`cropped_page.to_image().debug_tablefinder()`
![image](https://user-images.githubusercontent.com/14192598/64295205-94e0a280-cf25-11e9-85bc-8e4d4abdbeff.png)
It appears that the table debug looks fine, but it extracts a single line of text:
`cropped_page.extract_table()`
```
[['Line no UPC code Location Item Description Item Quantity Bill Amount Accrued Amount Handling Rate PO number\n0085648100305 CENTRAL KMA LILYS 40% SLTD ALMND CHOC 637 $ 0.61 $ 388.57 0.0000\n0085648100380 CENTRAL KMA LILYS DRK CHC CRMLZD SLTD 688 $ 0.61 $ 419.68 0.0000\n0085648100303 CENTRAL KMA LILYS ALMND 55% DARK CHOC 560 $ 0.61 $ 341.60 0.0000\n0085648100300 CENTRAL KMA LILYS 55% DARK CHOC BAR 415 $ 0.61 $ 253.15 0.0000'],
 ['']]
```
Additionally, when I crop out the blank columns, the extraction works fine, so it appears that the issue lies with the blank first and last columns:
```
cropped_page2 = page.crop((72, 0, page.width - 90, 122))
cropped_page2.to_image()
cropped_page2.extract_table()
```
```
[['UPC code',
  'Location',
  'Item Description',
  'Item Quantity',
  'Bill Amount',
  'Accrued Amount',
  'Handling Rate'],
 ['0085648100305',
  'CENTRAL KMA',
  'LILYS 40% SLTD ALMND CHOC',
  '637',
  '$ 0.61',
  '$ 388.57',
  '0.0000'],
 ['0085648100380',
  'CENTRAL KMA',
  'LILYS DRK CHC CRMLZD SLTD',
  '688',
  '$ 0.61',
  '$ 419.68',
  '0.0000'],
 ['0085648100303',
  'CENTRAL KMA',
  'LILYS ALMND 55% DARK CHOC',
  '560',
  '$ 0.61',
  '$ 341.60',
  '0.0000'],
 ['0085648100300',
  'CENTRAL KMA',
  'LILYS 55% DARK CHOC BAR',
  '415',
  '$ 0.61',
  '$ 253.15',
  '0.0000']]
```
[adversarial_example.pdf](https://github.com/jsvine/pdfplumber/files/3576662/adversarial_example.pdf)

**Comment by jsvine** [comment]
Hi @alexanderwhatley, and very interesting puzzle you've presented! I've looked into it, and what's happening is that `pdfplumber` actually finds two tables in that section of the PDF:

```python
tables = cropped_page.find_tables()
len(tables)
```

```
2
```
The first looks like this:

```python
cropped_page.to_image().debug_table(tables[0])
```

![table one](https://user-images.githubusercontent.com/534702/66276230-02eaf300-e85f-11e9-8ba4-1f0e994e11d2.png)

... and that's what you're seeing as the result of `.extract_table()`.

The second looks like this:

```python
cropped_page.to_image().debug_table(tables[1])
```

![table two](https://user-images.githubusercontent.com/534702/66276239-201fc180-e85f-11e9-8c13-01d35425cfa4.png)

... the extraction of which is what you wanted:

```python
tables[1].extract()
```

```
[['Line no',
  'UPC code',
  'Location',
  'Item Description',
  'Item Quantity',
  'Bill Amount',
  'Accrued Amount',
  'Handling Rate',
  'PO number'],
 ['',
  '0085648100305',
  'CENTRAL KMA',
  'LILYS 40% SLTD ALMND CHOC',
  '637',
  '$ 0.61',
  '$ 388.57',
  '0.0000',
  ''],
 ['',
  '0085648100380',
  'CENTRAL KMA',
  'LILYS DRK CHC CRMLZD SLTD',
  '688',
  '$ 0.61',
  '$ 419.68',
  '0.0000',
  ''],
 ['',
  '0085648100303',
  'CENTRAL KMA',
  'LILYS ALMND 55% DARK CHOC',
  '560',
  '$ 0.61',
  '$ 341.60',
  '0.0000',
  ''],
 ['',
  '0085648100300',
  'CENTRAL KMA',
  'LILYS 55% DARK CHOC BAR',
  '415',
  '$ 0.61',
  '$ 253.15',
  '0.0000',
  '']]
```

`.extract_table()` is *supposed* to extract the "largest" table it finds, by number of cells, but unfortunately [there's a bug in that logic](https://github.com/jsvine/pdfplumber/blob/master/pdfplumber/page.py#L184), which causes it to do the opposite 🤦‍♂️. Will work on a fix.

**Comment by jsvine** [comment]
Fixed in https://github.com/jsvine/pdfplumber/commit/56a3ac7f2fa19db726ff9a914cab3cc90898aa57; thanks again for flagging.
