### ISSUE TITLE
Assumptions made by PDF Plumber in text positioning?

### ISSUE THREAD

**Issue by ThePrefixCyber** [jsvine/pdfplumber#141]
Can PDF Plumber text bounding boxes be considered a deterministic result of the PDF standard? What assumptions are made about the generation, versioning, and format of the PDF? Is it possible that PDF Plumber's bounding box positions would be very much out of position compared to text rendered in some PDF viewing software?

**Comment by jsvine** [comment]
Hi @ThePrefixCyber. All information about text bounding boxes, etc., comes from `pdfminer.six`: https://github.com/pdfminer/pdfminer.six

`pdfminer.six` is the best-available PDF parser I'm aware of for Python but there are, indeed, occasional differences in how it interprets PDFs versus various PDF viewers.
