### ISSUE TITLE
Table divided on two PDF pages

### ISSUE THREAD

**Issue by nessry** [jsvine/pdfplumber#142]
Hi! thank you for this useful tool and for its excellent accuracy. I would like to ask about dealing with table divided on two PDF pages. How to concatenate the two parts of the table?
I would be even more grateful if there is a new, easy function that can deal with these kind of cases properly.
Thanks a lot!

**Comment by jsvine** [comment]
Hi @nessry, and interesting question. I think the solution would depend a lot on the specific table, and the specific way it's divided. Without seeing the PDF itself, my best guess would be to extract the tables from the two pages, separately, and then combine them with standard Python.
