### ISSUE TITLE
get error when I use Page class to do something

### ISSUE THREAD

**Issue by jimmyhsia** [jsvine/pdfplumber#143]
When I use the Basic example code and get error
`import pdfplumber

with pdfplumber.open("file.pdf") as pdf:

    first_page = pdf.pages[0]
    print(first_page.chars[0])`
and get error like this 
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-8-eb41f7233e1b> in <module>
      4 
      5     first_page = pdf.pages[0]
----> 6     print(first_page.chars[0])

~\Anaconda3\lib\site-packages\pdfplumber\container.py in chars(self)
     33     @property
     34     def chars(self):
---> 35         return self.objects.get("char", [])
     36 
     37     @property

~\Anaconda3\lib\site-packages\pdfplumber\page.py in objects(self)
     64     def objects(self):
     65         if hasattr(self, "_objects"): return self._objects
---> 66         self._objects = self.parse_objects()
     67         return self._objects
     68 

~\Anaconda3\lib\site-packages\pdfplumber\page.py in parse_objects(self)
    165 
    166         for obj in self.layout._objs:
--> 167             process_object(obj)
    168 
    169         return objects

~\Anaconda3\lib\site-packages\pdfplumber\page.py in process_object(obj)
    138         def process_object(obj):
    139             attr = dict((k, CONVERSIONS[k](resolve_all(v)))
--> 140                 for k, v in obj.__dict__.items()
    141                     if k not in IGNORE)
    142 

~\Anaconda3\lib\site-packages\pdfplumber\page.py in <genexpr>(.0)
    139             attr = dict((k, CONVERSIONS[k](resolve_all(v)))
    140                 for k, v in obj.__dict__.items()
--> 141                     if k not in IGNORE)
    142 
    143             kind = re.sub(lt_pat, "", obj.__class__.__name__).lower()

KeyError: 'fontsize'
`
any help? thanks!!

**Comment by jsvine** [comment]
That's very strange. Can you provide more information?

- What version of `pdfplumber` are you using? (`pdfplumber.__version__`)
- Please attach the PDF you're using.

**Comment by jimmyhsia** [comment]
> That's very strange. Can you provide more information?
> 
> * What version of `pdfplumber` are you using? (`pdfplumber.__version__`)
> * Please attach the PDF you're using.

- pdfplumber version is 0.5.14
- python is 3.7
- pdfminer.six is 20181108
- PDF is download from Basic example
  https://cdn.rawgit.com/jsvine/pdfplumber/master/examples/pdfs/background-checks.pdf

**Comment by jsvine** [comment]
Thank you for providing that. I'm running the same — but on a Mac and not through Anaconda — and getting no problems.
