### ISSUE TITLE
to_image() throws "MagickReadImage returns false, but did not raise ImageMagick  exception"

### ISSUE THREAD

**Issue by 2gitrepo** [jsvine/pdfplumber#144]
While trying to execute the statement
`first_page.to_image()`

throws the error 
`MagickReadImage returns false, but did not raise ImageMagick  exception`

**Comment by 2gitrepo** [comment]
The way I resolved this is by installing ghostscript. Did not see that mentioned as a prerequisite.

Please add it under the **Installation** section.

**Comment by jsvine** [comment]
Good catch, thanks! The "Visual debugging" section now clearly notes out the additional dependencies.
