### ISSUE TITLE
too mush useless number after pick from pdf

### ISSUE THREAD

**Issue by drowecho** [jsvine/pdfplumber#145]
files is ------>  
[not too broad.pdf](https://github.com/jsvine/pdfplumber/files/3739702/not.too.broad.pdf)
[too broad.pdf](https://github.com/jsvine/pdfplumber/files/3739701/too.broad.pdf)

i try to convert to pick up datas by using page.extract_tables()
but too much useless numbers in result after picked
like this, i can`t fix this:
----------------------------->
[[['Date\n22222222000000001111111199999999--------0000000088888888--------2222222277777777', 'Customer PO\n11111111444444443333333399999999999999991111111111111111333333330000000011121111YYLDLYLYWWWNRNRL46490111384375570486123011611211550050200', 'Hub SO\n44444444999999996666666699999999333333334444444499999999777777772304011323879704', 'Outband Dlv\n55555555222222222222222266666666666666667777777700000000939992935045494004657586', 'Material\n0000000011121111YYLDLYLYWWWNRNRL464901113843755704861230', 'Description\nMMCCCCCBOOOAAEEEZBBVVVCCELLEEEHHLEERRR __  A   CFAAFCFSRaRRSS MUbcMMUUol e_  Kv  AA,LeMAiLtC  rSCcc EED ooMDaCD_vvsH,P_eeBsHyrrCZ_ Dc   aLAaPpAs_bSLale S Mliaaen_MsstR, ss(B ,eyyswBaai  ,lssb/rvYieC_ellDva,arCBec2m okrLNv K /JoeYEMrI RFNi_PcGSR/MLLIE_DB)lack', 'Ship Qty\n1151111605525000', 'ship from\nWWWWWWWWWWWWWWWWWWWWWWWW        HHHHHHHHuuuuuuuubbbbbbbb', 'IP(16911366nU5322....r0709viS....co34824923Dei7386c)e', 'IAS19411564nD55584601mv484885..)o11o.....i579232uc52ent (U', 'OCoriugnintrayl \n115111160552500@0@@@@@@C@NCCCCCCCNNNNNNN', 'GI Date\n22222222000000001111111199999999--------0000000088888888--------2222222288888888', 'Invoice no\n66666666111111114444444433333333555555555555555511111111000000004444444499999999', 'Invoice Date\n22222222000000001111111199999999--------0000000088888888--------2222222288888888        0000000000000000::::::::0000000000000000::::::::0000000000000000', 'BOL\nDDDDDDDDLLLLLLLL111111119999999900000000888888882222222288888888HHHHHHHH000000001111111133333333', 'Forward', 'HAWB', 'notification time\n22222222000000001111111199999999--------0000000088888888--------2222222299999999        0000000088888888::::::::3333333344444444::::::::0000000000000000', 'pick up time', 'Remark', 'shio to name\nSSSSSSSSMMMMMMMMSSSSSSSS        ((((((((KKKKKKKKuuuuuuuunnnnnnnnsssssssshhhhhhhhaaaaaaaannnnnnnn))))))))        CCCCCCCCoooooooo........,,,,,,,,        LLLLLLLLttttttttdddddddd||||||||||||||||', 'shio to code\n11111111222222221111111144444444999999994444444455555555222222226666666666666666', 
<--------------------------------------

but it works perfect when i delete column named 'SMS申报要素', is this pdf too broad?
how to skip this limit
please help me !
thank you verrrrrrrrrry much  /  ありがとうございます！！

**Comment by jsvine** [comment]
@drowecho In the future, please describe the steps you took to try to solve the problem on your own. Ideally, also show the output of `page.to_image().debug_tablefinder()`. But to help you out, I've done a little digging around. Using pdfplumber's visual debugging tools, it appears that the problem is that the tables in this PDF are delimited not by single lines, but by some sort of overlapping line system:

![IMG_0030](https://user-images.githubusercontent.com/534702/67487755-7d2bbd80-f63c-11e9-992c-79bf9ad5c4f3.jpeg)

(See the positions of the red lines above.)

It appears you can still get your table, though, by passing the `snap_tolerance` setting to `.extract_table()`:

```python
broad.pages[0].extract_table({ "snap_tolerance": 2 })
```

Output:

```
[['Date',
  'Customer PO',
  'Hub SO',
  'Outband Dlv',
  'Material',
  'Description',
  'Ship Qty',
  'ship from',
  'IP(nUrviScoDeic)e',
  'IASnDmv)ooiucent (U',
  'OCoriugnintrayl',
  'GI Date',
  'Invoice no',
  'Invoice Date',
  'BOL',
  'Forward',
  'HAWB',
  'notification time',
  'pick up time',
  'Remark',
  'shio to name',
  'shio to code',
  '品名',
  'HS code',
  '单位',
  'SMS申报要素',
  '净重(kg)'],
 ['2019-08-27',
  '1439911301YN93610',
  '4969349722',
  '5226670950',
  '01YN936',
  'MECH_ASM MECH_ASM,Base,BLK',
  '10',
  'WWW Hub',
  '15.47',
  '154.7',
  '10@CN',
  '2019-08-28',
  '6143551049',
  '2019-08-28 00:00:00',
  'DL190828H013',
  '',
  '',
  '2019-08-29 08:34:00',
  '',
  '',
  'SMS (Kunshan) Co., Ltd||',
  '1214945266',
  '盖板',
  '8473309000',
  '个',
  '0品牌类型：境内自主品牌1.品名：主机下盖；2.用途(适用机型):T490(Drift).用于保护和固定笔记本电脑主机；3、品牌：Lenovo；4、型号：无；5、如是AMD或intel芯片应报清品牌：否；6、如是AMD或intel芯片应报清用途：无；7、产品编号：无编码',
  '1.67'],

[...]
```

**Comment by drowecho** [comment]
great! it works perfect!
thank you very much

and some little trouble happened(the sequence of a word) :
![1573451462(1)](https://user-images.githubusercontent.com/56685203/68564441-9b424c00-048b-11ea-8f62-0526cebcace5.jpg)

and i try to solved it by changing code below
![1573451993(1)](https://user-images.githubusercontent.com/56685203/68564447-9e3d3c80-048b-11ea-8c2e-2c46b1bf9e58.jpg)

**Comment by jsvine** [comment]
That's interesting. Thanks for sharing!
