### ISSUE TITLE
rects linewidth is zero 

### ISSUE THREAD

**Issue by apache135** [jsvine/pdfplumber#146]
1.When extracted the page object, It got those rects which didn ‘t appear on the page ,
I want to know if there is an interface can modify it?
2. I found some rects object have the line width whose value is 0 or 1, I want to know in what condition the rect line width is 1, I found some line which was visible on the page has the linewidth 0.

**Comment by jsvine** [comment]
> 1.When extracted the page object, It got those rects which didn ‘t appear on the page ,
I want to know if there is an interface can modify it?

Sometimes PDFs contain rects that aren't visible, for various reasons. There's no guaranteed way to identify them, but examining the characteristics of each rect can sometimes reveal patterns that make it possible to understand which rects are visible and which are not.

> 2. I found some rects object have the line width whose value is 0 or 1, I want to know in what condition the rect line width is 1, I found some line which was visible on the page has the linewidth 0.

You can use [the `Page.filter` method](https://github.com/jsvine/pdfplumber#the-pdfplumberpage-class) to create a `Page` object that contains only the rects that you care about.

**Comment by mkl-public** [comment]
>I found some line which was visible on the page has the linewidth 0.

That is completely correct.

According to the PDF specification:

>A line width of 0 shall denote the thinnest line that can be rendered at device resolution: 1 device pixel wide. However, some devices cannot reproduce 1-pixel lines, and on high-resolution devices, they are nearly invisible. Since the results of rendering such zero-width lines are device-dependent, they should not be used.

_(ISO 32000-2, section 8.4.3.2 "Line width")_

If you don't want to see a line, don't draw it.
