### ISSUE TITLE
load pdf data by bytes object

### ISSUE THREAD

**Issue by mrkdian** [jsvine/pdfplumber#147]
Is there no such interface???

**Comment by jsvine** [comment]
`pdfplumber.open(...)` accepts a filepath or buffer, so you should be able to pass a `BytesIO` object as the parameter. Closing this issue, but feel free to reopen if this doesn't work for you (with a detailed description of what you tried and the error it produced).

**Comment by LinanYaooo** [comment]
with open(file, 'rb') as f:
    content = io.BytesIO(f.read())

import pdfplumber

doc = pdfplumber.open(content)


      4 
----> 5 doc = pdfplumber.open(content)

D:\Anaconda\lib\site-packages\pdfplumber\pdf.py in open(cls, path, **kwargs)
     46     @classmethod
     47     def open(cls, path, **kwargs):
---> 48         return cls(open(path, "rb"), **kwargs)
     49 
     50     def process_page(self, page):

TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO

**Comment by jessecambon** [comment]
@jsvine  @LinanYaooo I had this same issue. I switched out `pdfplumber.open()` for `pdfplumber.load()` to fix it. 

Some working code is below for reference. If I switch the `load()` function out with `open()` then I get the same error from above: `TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO`. I'm using `pdfplumber==0.5.22` installed via pip.

```python
import pdfplumber, io
file_path = "" # path to local PDF file

def read_pdf(file_path_or_obj):
    """
    Use pdfplumber to read a PDF file (file path or object)
    Returns a list of strings (one string per page)
    """
    pdf = pdfplumber.load(file_path_or_obj)
    doc = []
    for page in pdf.pages:
        doc.append(page.extract_text())
    pdf.close()
    return(doc)

buffer = io.BytesIO()

# write binary content of file to buffer
with open(file_path, mode='rb') as file: 
    buffer.write(file.read())

test = read_pdf(buffer)
```

**Comment by jsvine** [comment]
With the changes released in `v0.5.23`, you should now be able to call `pdfplumber.open(bytes_io_object)`.

Beginning with `v0.5.23`, `pdfplumber.load` is deprecated and unnecessary, as its functionality is now included in `pdfplumber.open`.

**Comment by nikokaoja** [comment]
@jsvine I have a similar problem. In my case `mypy` complains:

```
 Argument 1 has incompatible type "str | Path | BytesIO"; expected "str | Path | BufferedReader"
 ```
 
 `pdfplumber.open(file)` expects `file` to be of type `str | Path | BufferedReader` and not `str | Path | BytesIO`

**Comment by jsvine** [comment]
Hi @nikokaoja, are you sure you're using the latest version of `pdfplumber`? That specific issue [was fixed in `0.8.0`](https://github.com/jsvine/pdfplumber/blob/stable/CHANGELOG.md#development-changes), released in February. Or does it still persist for you even with the most recent version?

**Comment by nikokaoja** [comment]
@jsvine you are right I am using 0.7.6, I will move to 0.8.0.

**Comment by alexander01202** [comment]
This error still persist for me

```
pdf = requests.get(pdf_link, headers)
pdf_content = io.BytesIO(pdf.content)
with pdfplumber.open(self.pdf_content) as pdf_file:
            for page in pdf_file.pages:
                text += page.extract_text()
```

I get the error: `expected str, bytes or os.PathLike object, not _io.BytesIO`

I use 0.10.3

**Comment by jsvine** [comment]
Hi @alexander01202, that's strange. When I run the following code (modified from what you shared to work as a standalone script), I don't encounter any problems:

```python
import io
import requests
import pdfplumber

pdf_link = "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf"
pdf = requests.get(pdf_link)
pdf_content = io.BytesIO(pdf.content)
with pdfplumber.open(pdf_content) as pdf_file:
    for page in pdf_file.pages:
        print(page.extract_text())
```

**Comment by alexander01202** [comment]
It works now.
Seems the problem was because I was reading the pdf.content multiple times
in different functions. Probably was invalidated or something
