### ISSUE TITLE
Is it possible to extract Font Color?

### ISSUE THREAD

**Issue by Mahendra114027** [jsvine/pdfplumber#148]
Hi, I was just wondering if it's possible to extract the font color of characters from the PDF as they are normally available in the font-specs properties of the files.

I am aware of the `fontname` attribute of `pdf.chars` but is there any setting to extract other font properties as well?

@jsvine is this available in pdfplumber?

**Comment by Mahendra114027** [comment]
Does anyone know any workaround for font color using pdfplumber?

**Comment by jsvine** [comment]
@Mahendra114027 At its core, `pdfplumber` uses `pdfminer.six`. It's worth looking through that project's [documentation and issues](https://github.com/pdfminer/pdfminer.six) to see if anyone has come up with a way to do what you want. If you do find one, I'd be interested to hear about it, for possible inclusion into `pdfplumber`.

**Comment by dwalton76** [comment]
@Mahendra114027 in page.parse_objects if you add `"graphicstate", noop,` to the list of `CONVERSIONS` you can then follow the code [here](https://github.com/pdfminer/pdfminer.six/issues/337) as a guideline to get the RGB value of the font. You would end up with something like
```
    def cmyk_to_rgb(self, cmyk):
        r = 255*(1.0-(cmyk[0]+cmyk[3]))
        g = 255*(1.0-(cmyk[1]+cmyk[3]))
        b = 255*(1.0-(cmyk[2]+cmyk[3]))
        return r,g,b
```
+            htmlcolor = ""
+            if len(textcolor) == 4:
+                textcolor = self.cmyk_to_rgb(textcolor)
+            if len(textcolor) == 3:
+                htmlcolor = 'color: rgb(%s,%s,%s)'%(textcolor[0], textcolor[1], textcolor[2])
```
