### ISSUE TITLE
page.to_image() does not popup any graph without error

### ISSUE THREAD

**Issue by hyshun** [jsvine/pdfplumber#150]
![image](https://user-images.githubusercontent.com/34941148/68264942-8c235e80-0085-11ea-8e33-9cdec08547c2.png)

Have installed Pillow6.2.1, pdfplumber0.5.14, ImageMagick Display 6.9.10 and Ghostscript9.50.

Any suggestion for this cases?

**Comment by hyshun** [comment]
![image](https://user-images.githubusercontent.com/34941148/68266689-c80cf280-008a-11ea-8d40-9549f1a0f9c5.png)
use ipython in pycharm and only shows the content, but can show the content with save function. so any display function or show function for that?

**Comment by samkit-jain** [comment]
There is a save method using which you can save the image locally. See https://github.com/jsvine/pdfplumber#basic-pageimage-methods

**Comment by hyshun** [comment]
Ok, thanks, that is helpful
