### ISSUE TITLE
Is it possible to extract hyperlinks?

### ISSUE THREAD

**Issue by ubmarco** [jsvine/pdfplumber#151]
I see the `Page` object has an `annos` attribute but it's just an empty list for me.
However in the PDF page I'm extracting there are 24 hyperlinks.

I also see these 24 links using the approach in https://github.com/euske/pdfminer/issues/172#issuecomment-283628657.

Is it possible to get them using pdfplumber?

**Comment by jsvine** [comment]
Hi @ubmarco, and thanks for raising this issue. It's a good question. Extracting links should be possible, but I don't quite know if there's a fully-generalizable solution. (If someone here does know, I'd be very interested to hear it.) I've had luck with code like this:

```python
# Some of the PDF's properties are encoded as strings,
# while others are encoded as PDFObjects. Here, we resolve
# them all to strings, rather than guess
def try_resolve(x):
    try:
        return x.resolve()
    except:
        return x

# Just to transform the PDF spec's version of bounding boxes
# into more common coordinates
def rect_to_bbox(rect, page):
    return (
        rect[0],
        float(page.height) - rect[3],
        rect[2],
        float(page.height) - rect[1],
    )

def generate_links(page):
    for anno in page.page_obj.annots.resolve():
        anno = anno.resolve()
        if anno.get("Subtype").name != "Link":
            continue
            
        yield {
            "url": try_resolve(anno["A"])["URI"].decode("utf-8"),
            "bbox": rect_to_bbox(try_resolve(anno["Rect"]), page),
        }

links = list(generate_links(my_page))
```

Does that work for you?

**Comment by jsvine** [comment]
`v0.5.23` introduces the `.hyperlinks` attribute for `PDF` and `Page` objects, as well as more robust support for annotations (`.annots`) more generally. Thank you for having raised this issue!
