### ISSUE TITLE
How to display the PageImage object

### ISSUE THREAD

**Issue by benlhy** [jsvine/pdfplumber#152]
I was wondering how to manipulate the PageImage object. 

Are there any examples of displaying the PageImage object other than in a IPython or Jupyter notebook?

**Comment by jsvine** [comment]
`PageImage.original` and `PageImage.annotated` are `wand.image.Image` objects, which you can manipulate in many ways: http://docs.wand-py.org/en/latest/wand/image.html#wand.image.Image

You can also call `PageImage.save(*args, **kwargs)` to save the image to file for display however you'd like elsewhere. (The parameters are the same as `wand.image.Image.save`: http://docs.wand-py.org/en/latest/wand/image.html#wand.image.Image.save

**Comment by jsvine** [comment]
@benlhy My apologies; I mis-wrote. The `PageImage.original` and `PageImage.annotated` objects are, rather `PIL.Image` objects, the documentation of which can be found here: https://pillow.readthedocs.io/en/stable/reference/Image.html#the-image-class
