### ISSUE TITLE
Is it possible to judge the text on or below an image for pdf

### ISSUE THREAD

**Issue by apache135** [jsvine/pdfplumber#153]
I got a pdf file, there is invisible text below the image, and visible text on the image . When use page.extract_text() , it will return all text on the page which contain visible and invisible text. Is there a way to check which text box on the image  and others not?

**Comment by jsvine** [comment]
It will depend on the precise PDF, and how that PDF has decided to represent the visible and invisible text. By inspecting the objects in `page.chars`, you may be able to observe properties which make the below/above-image text possible to separate from one another. If so, you can use `page.filter` to select only the text you care about before running `page.extract_text()`.
