### ISSUE TITLE
Is it possible to show image with password protected PDF? (use to_image)

### ISSUE THREAD

**Issue by michael34435** [jsvine/pdfplumber#154]
Is it possible to show the image with password-protected PDF? I have an encrypted PDF file but I can't extract tables directly so I want to crop it(and extract it again). However, it always shows me the error ;(

Here is the example

```python
with pdfplumber.open(filename, password=password) as pdf:
    page_count = len(pdf.pages)

    for page in range(0, page_count):
        p = pdf.pages[page]
        p.to_image()
```

I had installed `ghostscript` on my MacBook (10.15 Catalina) and gs raised an exception
```
   **** This file requires a password for access.
Error: /invalidfileaccess in pdf_process_Encrypt
```

**Comment by jsvine** [comment]
Great, tricky question. The conversion from PDF to image is handled by the [`wand` library](http://docs.wand-py.org/en/latest/wand/image.html) and I don't see an obvious way to pass a password to that. Your best bet might be first to make a non-password protected copy of the PDF before analyzing it. ([cpdf](https://community.coherentpdf.com/) might be handy for this.)

**Comment by michael34435** [comment]
Thanks! `cpdf` helps me
