### ISSUE TITLE
Get locations of table

### ISSUE THREAD

**Issue by alison84r** [jsvine/pdfplumber#156]
Hello,
I have one query.
Can I get the location of the Tables or Bounding box in the pdf. 
If possible can you please guide me.

**Comment by jsvine** [comment]
Yes, the `Table` objects returned by `page.find_tables(...)` should contain those locations: https://github.com/jsvine/pdfplumber#table-extraction-methods

**Comment by alison84r** [comment]
Thanks. I am able to extract it.

**Comment by Falven** [comment]
@jsvine is there no graphical or simpler approach to finding coordinates similar to how camelot allows you to plot the PDFs? Especially for cases where some specific tables may not be detected in the overall document but could potentially be if you cropped?

**Comment by jsvine** [comment]
Hi @Falven, if I'm understanding your question correctly, I believe the answer is yes, via `page.to_image().debug_tablefinder(...)`. Does that suit your needs?

More broadly, the [visual debugging tools](https://github.com/jsvine/pdfplumber?tab=readme-ov-file#visual-debugging) may be handy.
