### ISSUE TITLE
metadata resolve bug

### ISSUE THREAD

**Issue by meldonization** [jsvine/pdfplumber#157]
file: `pdf.py` line 32
when resolving metadata from pdf file
error occurs when `self.metadata` has a value of type `dict`
thus I may suggest adding an if clause for this special case as follows:
```
elif isinstance(v, dict):
    pass
```

**Comment by meldonization** [comment]
@jsvine I can't remember the specific pdf file that I have encountered, but this should be a general issue. Please consider fix it in the next release of pdfplumber. Much thanks. 😛

**Comment by jsvine** [comment]
It will be difficult to test a fix without an example PDF. If you're able to find one, that'd be quite helpful. Thanks.

**Comment by jsvine** [comment]
Closing this issue for now, but feel free to reopen with an example PDF. Alternatively, if anyone else knows of a PDF that demonstrates this issue, please do comment below, with a link or upload the the PDF.
