### ISSUE TITLE
Find font Name of the character or word

### ISSUE THREAD

**Issue by alison84r** [jsvine/pdfplumber#158]
1. I am able to get the required table.
2. From the table I am getting each row,
3. I am able to get the text from each cell, but I am not able to get any other properties like text size, text font etc..
![image](https://user-images.githubusercontent.com/12997350/69777597-0b104080-11c7-11ea-892f-d55d798534e5.png)

Let me know if I am doing anything wrong.

**Comment by jsvine** [comment]
You're not doing anything wrong, @alison84r. The results of table extract produces only the strings of the text in each cell, not other characteristics of the text. (There are a few reasons for this, but the primary one is that the characters in a table cell are not guaranteed to have the same characteristics.) To examine the characters more closely, however, you could pass the bounding boxes for each cell (`table.cells`) to the `page.crop(...)` method.
