### ISSUE TITLE
When I use extract PDF content, it's all CID: XXXX

### ISSUE THREAD

**Issue by xiaojiejiela** [jsvine/pdfplumber#159]
![image](https://user-images.githubusercontent.com/50126188/69896404-09d34500-137a-11ea-8153-64fe667d70b9.png)
Is it because the PDF content is Chinese,？but I try to display other PDF normally

**Comment by samkit-jain** [comment]
Related to https://github.com/jsvine/pdfplumber/issues/29 and https://github.com/euske/pdfminer/issues/122

**Comment by jsvine** [comment]
Thank you, @samkit-jain 👍
