### ISSUE TITLE
Is it possible to extract table with no line just one side?

### ISSUE THREAD

**Issue by choiasher** [jsvine/pdfplumber#160]
The pdf table that I am trying to extract is spanned into next page. 

First-pages-table has no line at the bottom and next-page-table has no line at the top.

I found pdfplumber can't extract table with no lines at the bottom.

how can I extract these tables("no line at the top or bottom side table")??

**Comment by jsvine** [comment]
If you know where the bottom line *should* be, you can specify it with `explicit_horizontal_lines` in the table-extraction settings: https://github.com/jsvine/pdfplumber#table-extraction-settings
