### ISSUE TITLE
Simple way to write PDF object to file 

### ISSUE THREAD

**Issue by d-cubed** [jsvine/pdfplumber#162]
I've been trying to use pdfrw or pdfwriter to write a pdfplumber PDF object to a file.
Forgive me if I missed something - short of converting to an image is there a straightforward way to write the pdfplumber objects to a PDF file?

**Comment by jsvine** [comment]
Hi @d-cubed. You didn’t miss anything; there’s no feature for that. (`pdfplumber` is focused on extracting information from PDFs, rather than creating/modifying them.)

**Comment by rcdosado** [comment]
hello, i just want to ask what is the recommended way of generating PDFPlumber Page object to PDF?i have cropped a PDFPlumber  object and want to dump it as pdf, i'm also using PyPDF2, is there a way to convert PDFPlumber object to PyPDF pdf object so i can write it to file?thanks

**Comment by jsvine** [comment]
Hi @rcdosado, this library focuses only on extracting information from PDFs, rather than writing it. So although what you’re asking about does sound interesting, it is not part of this library’s functionality.
