### ISSUE TITLE
How to get the color filled in the curve?

### ISSUE THREAD

**Issue by pakaLFZ** [jsvine/pdfplumber#164]
As I am trying to convert pdf into svg, I found out that pdfplumber seems to give no information for the color filled in curve

**Comment by jsvine** [comment]
Hi, @pakaLFZ. This is a bit difficult to diagnose without providing the PDF or code. But color characteristics should be available in each rect/line/curve’s `stroking_color` and `non_stroking_color` properties. Closing this issue for now. But if you don’t see those color properties, feel free to reopen this issue with the following:

- An example PDF
- A short code snipped that demonstrates the problem
- The pdfplumber version number you are using
