### ISSUE TITLE
Not detecting full table, Missing a part of table

### ISSUE THREAD

**Issue by nessry** [jsvine/pdfplumber#166]
Hi jsvine,
Thank you so much for contributing such a great package.
I would like to ask why in the case of the table showed below the full table is not recognized. As you can see, only the left part of the table is detected (colored white) and the grey part is not detected. Is it because of the different level of colors of the two parts?
Thank you very much.
![Capture1](https://user-images.githubusercontent.com/56122012/71888268-0cc31180-3140-11ea-9f32-881253d13ec3.PNG)
![Capture](https://user-images.githubusercontent.com/56122012/71888285-164c7980-3140-11ea-91a9-d69da06f4c24.PNG)

**Comment by jsvine** [comment]
Hi, @nessry, and thanks for the kind words. It is fairly difficult, however, to diagnose the problem without seeing the original PDF and the code you used. (The color itself should not cause a problem; more likely, the right-side portion was constructed in an unconventional way. Experimenting with the with the [table-extraction settings](https://github.com/jsvine/pdfplumber#table-extraction-settings) might help you.)
