### ISSUE TITLE
Add six as dependency

### ISSUE THREAD

**Issue by GjjvdBurg** [jsvine/pdfplumber#167]
Hi there,

First of all, thanks for making this package! I noticed that the dependency on 'six' is not included in the setup.py file, while it is used in ``utils.py``. This breaks the installation on platforms or environments where six is not installed.

Thanks in advance for the fix!

**Comment by jsvine** [comment]
Hi @GjjvdBurg. It looks like what happened is that `pdfminer.six`, which this project depends on, [dropped support for Python 2](https://github.com/pdfminer/pdfminer.six/commit/3502dc9f3bc81de721fccde782da844ae8239a0a#diff-2eeaed663bd0d25b7e608891384b7298) and, with it, the `six` dependency, which we had been piggybacking on. Sooner or later, `pdfplumber` will also phase out support for Python 2. For now, though, this is a helpful catch, thanks! Will fix.

**Comment by jsvine** [comment]
Fixed, and now available in v0.5.16.

**Comment by GjjvdBurg** [comment]
Thanks for the fix @jsvine!
