### ISSUE TITLE
PDF fails to init when metadata includes a PostScript literal

### ISSUE THREAD

**Issue by boblannon** [jsvine/pdfplumber#17]
when calling `pdfplumber.open()`, the `PDF.__init__` method crashes if the metadata includes a value that is a `PSLiteral`, rather than a string. 

```pdfplumber/pdfplumber/pdf.py in open(cls, path, **kwargs)
     38     @classmethod
     39     def open(cls, path, **kwargs):
---> 40         return cls(open(path, "rb"), **kwargs)
     41 
     42     def process_page(self, page):

pdfplumber/pdfplumber/pdf.py in __init__(self, stream, pages, laparams, precision)
     31             else:
---> 32                 self.metadata[k] = decode_text(v)
     33         self.device = PDFPageAggregator(rsrcmgr, laparams=self.laparams)
     34         self.interpreter = PDFPageInterpreter(rsrcmgr, self.device)

/pdfplumber/pdfplumber/utils.pyc in decode_text(s)
     40     Adds py3 compatability to pdfminer's version.
     41     """
---> 42     if s.startswith(b'\xfe\xff'):
     43         return six.text_type(s[2:], 'utf-16be', 'ignore')
     44     else:

AttributeError: 'PSLiteral' object has no attribute 'startswith'```

**Comment by jsvine** [comment]
Hi, @boblannon-picwell, and thanks again for this! Any chance you still have, and could share, the (or any) PDF that raised this error? (I'm belatedly writing a test for the fix.)

**Comment by boblannon** [comment]
hey, i'm actually not with Picwell anymore, so my personal handle @boblannon is a better way to get in touch.

I don't have the source document any longer, either, because it was work that I did for Picwell. I can try my best to find something similar, though.

**Comment by jsvine** [comment]
Thanks, @boblannon, and noted!
