### ISSUE TITLE
If the PDF file contains the stsong-light font, this data is missing from the parsing results

### ISSUE THREAD

**Issue by l523402485** [jsvine/pdfplumber#170]
Can stsong-light fonts be supported in the new version?

**Comment by l523402485** [comment]
Windows 10
Python 3.6.8
PDFPlumber 0.5.15

**Comment by jsvine** [comment]
Hi, @l523402485. I’m not quite sure what “stsong-light fonts” are. Can you provide the following?:

1. A PDF that contains stsong-light fonts
2. The code you executed
3. The results you *expected* to see
4. What the results *actually* were

**Comment by samkit-jain** [comment]
@jsvine A similar issue #332 has been raised here. It also contains the PDF. One of these can be closed in favour of the other.
