### ISSUE TITLE
.edges property of Page or DerivedPage does not contain horizontal or vertical edges contained in curves

### ISSUE THREAD

**Issue by ratulbhadury** [jsvine/pdfplumber#171]
Hi, 

I would first like to start by saying thank you for the amazing work you have done with this package.

To provide some context with my issue, I am extracting information from a PDF whereby the page (at least looking at it in a PDF viewer) is structured in a table, and the information I want is within cells of the tables.

When using PdfPlumber to intepret these pages I am seeing that the vertical and horizontal lines that constitute the tables are not only individual PdfPlumber lines and rects, but sometimes also lines within the page's 'curve' objects. I have just realised that it seems the 'edges' property on the Container class does not take vertical/horizontal edges in curves into account. Therefore when I use TableFinder on a Page or DerivedPage, it sometimes misses the lines necessary to identify a Table.

Is there a reason for this? Could the 'edges' property on Container also be made to include vertical/horizonal lines held within curves?

Many thanks.

**Comment by jsvine** [comment]
Hi @ratulbhadury, and thanks for the kind words. You raise a very interesting issue, and I appreciate the detailed explanation. This is a tricky situation. I get the sense that PDF curves are rarely used to represent tables. I’m also concerned that developing a heuristic to identify *desired* vertical/horizontal lines in curves may be trickier that it sounds. So my initial instinct is not to make this a main feature of pdfplumber. *However*, I’m certainly open to being persuaded. A few things that would help:

- Do you have any PDFs you can share? That’d help with testing.

- Can you describe a bit more about what rules you’d expect the logic to follow? For instance, should it only use curves that are purely vertical/horizontal lines? Would you expect pdfplumber to extract vertical/horizontal sections from curves that also involve more “curvy” secitons?

**Comment by jsvine** [comment]
Thanks for the responses and extra details, @ratulbhadury. I think your suggestion is a reasonable one. I’ve been thinking of overhauling the API for table extraction, in part to make customizations like these much easier. I don’t know when I’ll get to that, but issues like these are good reminders.

Having at least one actual PDF to test against, however, will be crucial. And that PDF would have to be able to be shared publicly, since I would want to include it in the test suite.

**Comment by ratulbhadury** [comment]
@jsvine 

I have not tried making changes to public PyPi packages before, but will have a shot at it as I need to resolve this issue for my work asap. Though I will obviously not overhaul the exraction API :) If it goes ok, I will send you a pull request to consider.

Thanks again for you promptness and openess.

**Comment by jsvine** [comment]
Now realizing that, per other discussions in this repository, that passing `pdf_page.curves` to the `"explicit_horizontal/vertical_lines"` table-setting may achieve what you're looking for.
