### ISSUE TITLE
Problem when extracting values from table

### ISSUE THREAD

**Issue by nessry** [jsvine/pdfplumber#172]
First of all, I would like to thank you for this great package.
I want to extract tables from some financial PDF files. Everything goes well, just for the attached table, the first value in the column "Initial Fixing" is modified : instead of getting the value 20'410.8800, I am getting the value 20,4L1e0v.e8l8 00.
![Capture2](https://user-images.githubusercontent.com/56122012/72438037-4f21c980-37a4-11ea-9ce4-dfd640b4b590.PNG).
Is there any reason for getting this result.
Thank you!

**Comment by jsvine** [comment]
It’s very hard to say without having a copy of the actual PDF. Have you tried visual debugging? Something like this might help you diagnose the problem:

```
pdf = pdfplumber.open(“mypdf.pdf”)
p0 = pdf.pages[0]
im0 = p0.to_image()
im0.draw_rects(p0.chars)
```

One possibility is that the bounding boxes of the characters overlap more than they do in a typical PDF. (The visual debugging might show that.) You might want to try adjusting the `text_y_tolerance` table-extraction setting.

Closing for now. Feel free to reopen with additional details.
