### ISSUE TITLE
pdfplumber not reading bytes object

### ISSUE THREAD

**Issue by Anitha15890** [jsvine/pdfplumber#173]
**this is my code** 

data=cos.get_object(Bucket=credentials_1['BUCKET'], Key=i)["Body"].read()

print(type(data))
**<class 'bytes'>**

with pdfplumber.open(data,password="") as pdf :
     first_page=pdf.pages[x]

**ValueError: embedded null byte**

**Comment by jsvine** [comment]
Hi, @Anitha15890. If you first write the bytes to file, and then open that file (rather than the raw bytes) with pdfplumber, does *that* work? Or does it throw a similar error?

**Comment by sharmila-polamuri** [comment]
Hi,
  I got same error , please suggest in which file format i have to write bytes .txt or any other formats ?

**Comment by Anitha15890** [comment]
I used pdfplumber.load() instead of pdfplumber.open().. it worked fine for me .

**Comment by Anitha15890** [comment]
I first converted the bytes file into data=io.Bytes(filename), then used pdfplumber.load(data). This worked fine for me

**Comment by jsvine** [comment]
With the changes released in `v0.5.23`, you should now be able to call `pdfplumber.open(bytes_io_object)`.

Beginning with `v0.5.23`, `pdfplumber.load` is deprecated and unnecessary, as its functionality is now included in `pdfplumber.open`.
