### ISSUE TITLE
Problem when reading table columns

### ISSUE THREAD

**Issue by nessry** [jsvine/pdfplumber#174]
Hi jsvine,
First of all, I would like to thank you for this great package.
I am having a PDF file that I am trying to extract tables from it. The format of all tables is same as the attached photo.
I would like to ask why in the case of the table showed below, the table columns names are not recognized (they are recognized as None values) while the other table values are correctly extracted.
 Is it because of the different level of colors of the two parts? Or maybe because of the dark color of the background of the columns.
![Capture](https://user-images.githubusercontent.com/56122012/72974729-d20fd900-3dcf-11ea-8db4-779e0b00ae2a.PNG)

Thank you very much.

**Comment by jsvine** [comment]
Hi @nessry. Unfortunately, it’s nearly impossible to diagnose issues with PDFs based only on a screenshot. Are you able to post the PDF and the code you’re using?

And have you tried examining the `page.lines`, `pages.rects`, and `pages.chars` for clues? 

Closing this issue for now, but feel free to reopen with additional information.

**Comment by nessry** [comment]
Hi jsvine, 
Thank you for your response.
Please find enclosed the PDF file that I am testing.
The code I am using to extract tables is as follow:

```
import pdfplumber
import pandas as pd

def find_tables_in_pdf(input_pdf):
    assert isinstance(input_pdf, pdfplumber.pdf.PDF)
    for input_page in (input_pdf.pages):
        table = input_page.extract_tables()
        for i in range(len(table)):
        table_df = pd.DataFrame(table[i][1:], columns=table[i][0])
    return table_df 
```
Thank you!
[TS_Safety_Guard.pdf](https://github.com/jsvine/pdfplumber/files/4154649/TS_Safety_Guard.pdf)

**Comment by jsvine** [comment]
Hi @nessry. Run this code:

```python
pdf = pdfplumber.open("./TS_Safety_Guard.pdf")
page = pdf.pages[10]
im = page.to_image()
im.draw_rects(page.rects)
```

... and you'll see what's happening:

![debug](https://user-images.githubusercontent.com/534702/74073327-fd054a00-49d7-11ea-8a01-88a86e1f6c8e.png)

... which is that the PDF contains a bunch of rectangles *within* the headers. To resolve this, you can either try to programmatically identify the "bad" rectangles, or to extract the tables and then post-process the extracted values to identify the column headers.
