### ISSUE TITLE
text_x_tolerance ignored by extract_table?

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#176]
I noticed that the text_tolerance and text_x_tolerance were not behaving the way I thought they should in the context of extract tables. 

I was working on an example [here](https://github.com/jsfenfen/pdf20/blob/master/pdfs/senate_expenditures.ipynb)--(how does one link to the middle of a notebook on github?) it's essentially at the bottom. 

Extracting text from the relatively small font requires a text tolerance of 1 or 2 to realize word separation, but the same text tolerance appears not to work when in a table extraction context? Possibly I'm not understanding something important.

**Comment by jsvine** [comment]
Thanks for flagging, @jsfenfen. That's a good catch and, indeed, a bug. `Table.extract(...)` [accepts `x_tolerance` and `y_tolerance` as parameters](https://github.com/jsvine/pdfplumber/blob/b44f2dc3bcedb40ecdfbbd5297e81bcd997b0b6e/pdfplumber/table.py#L351-L353), but `Page.extract_tables(...)` [does not pass those parameters to that method](https://github.com/jsvine/pdfplumber/blob/df00787adae64af94f899b83e5909fefd53a5574/pdfplumber/page.py#L167).

In the meantime, until I've pushed a fix for the bug, you can replace this in your notebook:

```python
result = pg.crop(under_headers_region).extract_tables(config)
```

... with this:

```python
result = [ table.extract(x_tolerance = 1)
  for table in pg.crop(under_headers_region).find_tables(config) ]
```

Does that do it for you?

**Comment by jsfenfen** [comment]
Hey @jsvine that totally works for my purposes, thanks a ton!

**Comment by jsvine** [comment]
(Fixed in https://github.com/jsvine/pdfplumber/commit/b498df230fa4b0e291a771b263e904e489cea56e)
