### ISSUE TITLE
Words in adjacent table columns are merged when there are no spaces between them

### ISSUE THREAD

**Issue by greddyatpt** [jsvine/pdfplumber#177]
When a number column is followed by a text column and there's no white space between the right-aligned numbers and left-aligned text, `page.extract_words()` returns merged words.  

Test PDF: [merged-words.pdf](https://github.com/jsvine/pdfplumber/files/4151729/merged-words.pdf)

The screenshot below shows a part of the page with word bounding boxes (as returned by `page.extract_words()`) superimposed.  The merged words are highlighted.
![bounding-boxes](https://user-images.githubusercontent.com/2243686/73720330-8c5be600-46d6-11ea-9575-cadaff1c8b93.JPG)

Are there any workarounds?

This sample also shows another issue.  The tiny bounding boxes with no visible content have dashes (-) with perhaps matching text and background colors.  Is there an option to ignore such invisible words?  If not, it would be very useful to add it.  Suggested name for the option: WYSIWYG :)

**Comment by AbhishekCW** [comment]
You can try with `page.extract_words(x_tolerance=0)`. If it helps.

**Comment by greddyatpt** [comment]
Hi Abhishek,  Tried `x_tolerance=0` but it has the opposite effect of splitting legitimate words and numbers...

**Comment by greddyatpt** [comment]
This issue is unfortunately coming in the way of using pdfplumber in our project.  If pdfplumber is an active project, I'd greatly appreciate a response from the project contributors.

**Comment by jsvine** [comment]
Hi @greddyatpt, I have a full-time job outside of open-source work, but I do try to keep `pdfplumber` maintained. That said, I cannot always address issues quickly. Some thoughts on the issue you've encountered:

- `pdfplumber` makes no distinctions between numeric text and non-numeric text. To `pdfplumber` (and the underlying `pdfminer.six`) a character is just a character.

- `page.extract_words(...)` pays no attention to non-character objects, such as lines.

So it makes sense to me that `pdfplumber` would see those accumulations of characters as a single word. There are, however, ways you can separate them. 

For instance: You could, based on the line objects in the PDF and `page.crop(...)`, create column-specific crops of the page, and extract the words from each individually.

Alternatively, you could create two `page.filter(...)`'ed versions of the page, one with only numbers/commas, and one without them, and then the extract the words.
