### ISSUE TITLE
KeyError:'Type' when using pdfplumber.open(file_path)

### ISSUE THREAD

**Issue by ouyqf** [jsvine/pdfplumber#180]
Hi,

Thanks for creating this usefull package. I helped a lot to my work. But I met an issue when reading a pdf file today. 

I ran this code : pdf = pdfplumber.open(file_path) on jupyter notebook and it came out with an error, which was KeyError: 'Type'

Could you please help me to solve this problem ? 

Thank you a lot.

Ouyqf

**Comment by jsvine** [comment]
Hi @ouyqf, it is very difficult to diagnose pdfplumber issues without the original PDF, since so much of the parsing depends on how to the PDF was created. Closing this issue for now, but feel free to reopen with the file.
