### ISSUE TITLE
Table detection has room for improvement

### ISSUE THREAD

**Issue by greddyatpt** [jsvine/pdfplumber#181]
The following (partial) screen shot of the [attached PDF page](https://github.com/jsvine/pdfplumber/files/4178366/tables.pdf) shows detected tables in red. Wondering if it's possible to determine the table's extent based on the row and column borders (like humans do) even when some outer borders are missing.
![tables](https://user-images.githubusercontent.com/2243686/74113262-eede3780-4b57-11ea-8010-e48586687ace.jpg)

**Comment by HanSoLong** [comment]
This is the makeshift solution I came up with:

```
def augmented_extract_tables(page) -> list:
    raw_tables = page.find_tables()
    calibrated_tables = []
    for raw_table in raw_tables:
        page_fragment = page.crop((0, raw_table.bbox[1], page.width, raw_table.bbox[3]))
        min_x = page.width
        max_x = 0
        for char_obj in page_fragment.chars:
            min_x = min(min_x, char_obj['x0'])
            max_x = max(max_x, char_obj['x1'])
        calibrated_tables.append(page_fragment.extract_table({"explicit_vertical_lines": [min_x, max_x]}))
    return calibrated_tables

```

**Comment by jsvine** [comment]
Thanks for sharing that, @HanSoLong. In general, PDFPlumber aims to be predictable and explicit in table identification, so I'm wary of adding implicit assumptions, but that seems like a good solution for this particular PDF.

**Comment by greddyatpt** [comment]
Thanks @HanSoLong .  Will give that a try.
