### ISSUE TITLE
raspberry pi NoneType attribute error

### ISSUE THREAD

**Issue by jaka87** [jsvine/pdfplumber#184]
While running latest raspbian on raspberry pi with python 3.7.3 and latest pdfplumber and trying to run...

```
pdf = pdfplumber.open(file)
text=pdf.pages[0].extract_text()
pdf.close()
print(text)
text=" ".join(text.split())
```
i get AttributeError: 'NoneType' object has no attribute 'split'

I can for example print the text var and see all the data but the var has no attribute. How could I avoid that ?

**Comment by samkit-jain** [comment]
Is there any text on the first page of the PDF?

**Comment by jaka87** [comment]
Yes there is. And I can see the text with the printing command just before text split. The problem is not lack of text but that var containing the text don't have a type.
This script works fine on my linux and windows machine but on on raspberry.

**Comment by jaka87** [comment]
You were right. I was running this command as function and one of the files was in fact empty. Its working fine on all platforms...
