### ISSUE TITLE
Unable to read hidden cell value 

### ISSUE THREAD

**Issue by navulurinaresh** [jsvine/pdfplumber#185]
[hiddencell.pdf](https://github.com/jsvine/pdfplumber/files/4185400/hiddencell.pdf)

Unable to extract full value in the cell 2nd row & 5th column.the hidden value in the cell is missing,

How can I get the hidden value?

**Comment by mkl-public** [comment]
Your PDF merely contains a **bitmap image** of a table. Thus, that "hidden value" indeed is hidden very effectively, it is not at all contained in the PDF and, therefore, cannot be extracted.

**Comment by jsvine** [comment]
Thank you for looking into this, @mkl-public. Your diagnosis appears to be correct.
