### ISSUE TITLE
pdfplumber reads in column header entry twice 

### ISSUE THREAD

**Issue by alexanderwhatley** [jsvine/pdfplumber#187]
Here is the file: [bug.pdf](https://github.com/jsvine/pdfplumber/files/4207622/bug.pdf)

When I run the following code, it reads in the "Accrued Amount" column twice:

```
pdf = pdfplumber.read('bug.pdf')
page = pdf.pages[0]
x0, x1, top, bottom = 0, Decimal('612'), Decimal('549.257'), Decimal('769.408')
cropped_page = page.crop((x0, top, x1, bottom))
table = cropped_page.extract_table(table_settings={ 'vertical_strategy': 'lines', 'horizontal_strategy': 'lines' })
table[0]
['Line no',
  'UPC code',
  'Location',
  'Item Description',
  'Item Quantity',
  'Bill Amount',
  'Accrued Amount',
  'Accrued Amount',
  'Handling Rate',
  'PO number']
```

**Comment by samkit-jain** [comment]
Lowering the `top` value from 549.257 to 548 works.

**Comment by jsvine** [comment]
Thanks @samkit-jain! And looking into this, it seems to be a case of an oddly-constructed table. If you run this code:

```python
(
    cropped_page
    .to_image(resolution = 300)
    .debug_tablefinder({
        'vertical_strategy': 'lines',
        'horizontal_strategy': 'lines'
    })
)
```

You should see this: 

![image](https://user-images.githubusercontent.com/534702/74788370-960d4e00-527f-11ea-95a1-a65e80bbc2c2.png)

The first thing to notice is that, for some reason, the table surrounds every column name in its own rectangle, separate from the header *cells*. And the second thing, which is a bit difficult to see, is that the rectangle surrounding "Accrued Amount" gets close so close to the right side of the cell that — to `pdfplumber`, at least — it is interpreted as an additional cell. (See the additional circle on the right-side of that cell, indicating a cell vertex.)
