### ISSUE TITLE
Multirows in one Cell

### ISSUE THREAD

**Issue by DustBytes** [jsvine/pdfplumber#19]
Let's say Table in pdf contains two columns, so simple key,value pair can be formed but in second column few cells there have multiple lines(say 5 and key is in middle row). Then pdfplumber prints [None, value] for 2 times then it print [key, value] because the key for this row is at pos3 then again prints [None, value] two times. We can scan this presence of 'None' join them and put them as value for this key. If multiple such rows occur, we can still manage. Problem is when two or more such rows are adjust to each other, then finding the end line of one and beginning of other is difficult. The length of content also differs per table so can't put a line counter.

**Comment by jsvine** [comment]
Thanks, Gulzar. And, yes, dealing with tables that aren't formatted as strict grids is tricky. I've been working on some improvements to `pdfplumber`'s table detection, but some tables will always be out of its reach. If you send or attach an example a PDF that contains a table of this type, however, I can use it as a reference when building/testing.

**Comment by bighaidao** [comment]
hi , thanks for you useful pdf lib. @jsvine 

And I also got this problem . Can any improve to help  this bug now?

**Comment by jsvine** [comment]
Hi, @bighaidao. It depends on the specific PDF, and the specific table you're trying to extract. Some tables are easier than others, and some may be impossible to automatically extract with `pdfplumber`. If you send or attach an example a PDF, however, I can take a look.

**Comment by trivenigk** [comment]
Can we able to extract some thing like below table to a csv !!
![image](https://user-images.githubusercontent.com/9095840/68426014-3ded8880-0175-11ea-8659-bf5f49a4e82b.png)

when tried this i got the following error 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-37-7bf34bc5aba7> in <module>
----> 1 table = p0.extract_table()

c:\python3\lib\site-packages\pdfplumber\page.py in extract_table(self, table_settings)
    183         # Return the largest table, as measured by number of cells.
    184         sorter = lambda x: (-len(x.cells), x.bbox[1], x.bbox[0])
--> 185         largest = list(sorted(tables, key=sorter))[0]
    186         return largest.extract()
    187 

IndexError: list index out of range

**Comment by jsvine** [comment]
Given that the rows are generally separated vertically by whitespace (rather than lines, which only occur every five rows), I suspect you'll have more luck if you adjust the table-extraction settings to use the "text" `vertical_strategy`: https://github.com/jsvine/pdfplumber#table-extraction-settings 

... but it's difficult to know for sure without seeing the actual PDF file.
