### ISSUE TITLE
pdfplumber question - why can't extract text from the pdf I attached

### ISSUE THREAD

**Issue by homejzc** [jsvine/pdfplumber#190]
Dear GitHub contributer ，
I am new for python from China , I read your article in GitHub (https://github.com/jsvine/pdfplumber), thanks for it and I  try to use pdfplumber but meet some problems ?
I attach the pdf sample , seems my sample has good quality to extract text but after testing , I get nothing , could you help me if the pdf issue or some other issues ?

thanks and hope to get feedback from you ~

import pdfplumber
path = r'E:\SI\AE20191203146.pdf'

with pdfplumber.open(path) as pdf:
    page = pdf.pages[0]
    print(page.extract_text())
    print(page.extract_table())
    print(page.extract_tables())
    print(page.extract_words())

pdf.close()

C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe E:/PDF_extractor/pdf_plumber_test.py
None
[['', None, '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], ['', None, '', None, None]]
[[['', None, '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], [None, '', '', '', ''], ['', '', '', '', ''], ['', None, '', None, None]], [['', '']], [['', '', '', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', '', '', '']], [['', '', '', '', ''], ['', '', '', '', ''], ['', None, '', '', '']]]
[]

Process finished with exit code 0

**Comment by jsvine** [comment]
Hello, @homejzc, and thank you for your interest in this library. Unfortunately, I do not see the PDF attached.

One idea/question: If, on your computer, you open the PDF in a PDF-viewer, select all the text, and then paste it into a text editor, do you see text ... or nothing?

Closing this issue for now, but feel free to reopen with the PDF attached.
