### ISSUE TITLE
Invoice with vertical text line in margin left

### ISSUE THREAD

**Issue by dasapa** [jsvine/pdfplumber#194]
Hi,

i have to extract data of pdf invoices. All Invoices have a vertical string in the left margin (1 cm left) with legal information of the company but this line destroy the rest of invoice when i extract text. Do you know any method to delete this line?

Thx

**Comment by jsvine** [comment]
It's hard to know definitively without seeing the PDFs, but you can try using `Page.crop(...)` before extracting the text.
