### ISSUE TITLE
Convert the coordinates and overlay them on a pdf

### ISSUE THREAD

**Issue by qillbel** [jsvine/pdfplumber#196]
Hi all,

I was wondering if pdfplumber has a method to convert coordinates and plot them on the pdf. Having said that, my bounding box coordinates are standardized coordinates, where (0,0) is the top-left and (1,1) is the bottom-right of the pdf. 
And the coordinates of my bounding box is xmin,ymin,xmax,ymax. 

So, how can I convert these coordinates to allow pdfplumber overlays them on the pdf?

Thanks all and I'm sorry if this seems trivial for some of you.

Best

**Comment by jsvine** [comment]
`pdfplumber` does not have a specialized method for this, but you can convert the coordinates yourself by multiplying them by `page.width` and `page.height`.
