### ISSUE TITLE
collate chars w/ slight doctop variations

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#2]
Collate_chars' [sort](https://github.com/jsvine/pdfplumber/blob/master/pdfplumber/utils.py#L43) assumes that colinear words have the same exact doctop. In the wild, there's sometimes variations on this--especially for fillable pdfs (at least I think that's what I'm seeing).  I hacked around this with words by mucking with precision, but the variations here are much bigger--1 or 2 pixels. 

I'm hacking around this with an optional snap_to_y_grid arg, and something like: 

    if snap_to_y_grid:
        snap_to_grid = lambda x: round(x/float(snap_to_y_grid))
        chars["doctop"] = chars["doctop"].apply(snap_to_grid)

This alters the underlying dataframe values (maybe?)--which I assume would require a copy or something, or setting a different value. Any thoughts?

**Comment by jsvine** [comment]
Great question / conundrum! 

Not too concerned about the value-alteration. This can be handled easily by — as you allude to — making a `.copy()` of `chars`. And I think `snap_to_y_grid` handles most cases like these. 

But how should something like this handle edge-cases, e.g., a word gently-sloping-down? For the sake of a concrete-if-lame example:

|letter|doctop|
|-------|---------|
|C|`20`|
|O|`21`|
|M|`22`|
|P|`23`|
|U|`24`|
|T|`25`|
|E|`26`|
|R|`27`|

You'd have to set a pretty aggressive `snap_to_grid` value to clump all those letters together. But the letter-to-letter variation in `doctop` is actually pretty small — just one pixel at a time. I wonder:

- Is there a clever way to algorithmically identify strings of near-to-each-other characters? (And one that isn't too computationally expensive?)
- Should we even be worrying about edge cases like these?

Eager for your thoughts, and thanks again for raising the issue!

**Comment by jsvine** [comment]
Alternative attempt at solving this, using doctop-clustering: 
https://github.com/jsvine/pdfplumber/blob/doctop-variations/pdfplumber/utils.py

**Comment by jsvine** [comment]
Alternative attempt at solving this, using doctop-clustering: 

- Code: https://github.com/jsvine/pdfplumber/blob/doctop-variations/pdfplumber/utils.py
- Diff: https://github.com/jsvine/pdfplumber/commit/fd79cc8f01171f03a3a26599d64d5bc708defb16

Essentially, it looks at all `doctop`s, sorts them, then clusters any `doctop`s within `y_tolerance` of the next-smallest `doctop`. Then, it treats all `doctop`s in the same cluster as being on the same line. Would seem to handle your situation — does it? — and my fake example above. What do you think?

And do you have any PDF (or CSV char-output) of previously-failing examples?

**Comment by jsfenfen** [comment]
I think this would work--lemme dig around for the one that was failing. This is actually a problem for me in just coalescing words for merging with some fonts--all cap fonts sometimes have larger first letters which also makes trouble. I may try to adapt this to that. 

The question of sloping letters is also a really good one--and pretty gnarly to deal with once the delta y approaches line height. I've mucked around with that a little, and I think you need a different approach than clustering. For text that's just slanted I did an experiment with linear regression, and choosing words that had a shared y-intercept that sorta worked. But the other problem one gets (much more with scanned text) is of non-linear curve (think of putting a book on a copy machine). But that's an even worse problem...

**Comment by jsvine** [comment]
> all cap fonts sometimes have larger first letters which also makes trouble

Interesting! Hadn't encountered that before, but makes total sense.

> For text that's just slanted I did an experiment with linear regression, and choosing words that had a shared y-intercept that sorta worked.

Clever! I'm a bit worried about the computational expense of that, at least for the main `collate_chars` function. Maybe worth breaking out more-advanced chars-in-a-line detection into its own method?

> But the other problem one gets (much more with scanned text) is of non-linear curve (think of putting a book on a copy machine). But that's an even worse problem...

Oy, yeah. I'm thinking handling super-crazy text layouts is outside the scope of this library. But definitely open to being convinced otherwise!

**Comment by jsfenfen** [comment]
Yeah, wrt angle detection that's definitely something you wouldn't want there. If you assume a constant angle (not a great assumption) you can do some detection stuff and then apply your discovered angle. FWIW

**Comment by jsvine** [comment]
Just a heads-up that the new strategy for handling doctop-variations is now in `master` and `v0.2.0` — pushed and published this morning.

**Comment by jsfenfen** [comment]
Awesome!
