### ISSUE TITLE
PDF Encoding

### ISSUE THREAD

**Issue by spidru** [jsvine/pdfplumber#202]
Hi there,

I am currently working on a project which involves modifying existing PDF files, meaning that both decoding and encoding of PDF files are required. From what I understand, pdfplumber deals only with PDF decoding.

Would you be interested in extending the scope of pdfplumber to also include PDF encoding? I would be happy to contribute to this feature.

**Comment by jsvine** [comment]
Hi, @spidru. Given that there are already many libraries for generating PDFs, my general preference is to keep pdfplumber focused on text/data/information-extraction. But I'm interested to hear more about your proposal. How would it work?

**Comment by spidru** [comment]
Thanks for getting back to me. From what I've looked up, there are indeed a few libraries out there that focus more on PDF manipulation/editing, which is closer to what I need. I've started some initial testing with [PyPDF4](https://github.com/claird/PyPDF4), but I've already encountered unsupported features such as encoding text back into PDF. Since PyPDF4 also seems inactive, I'd rather be using a library which is actively maintained if at all possible.
If you are open to the idea of extending the library to also support encoding, I will start some initial testing with pdfplumber to get an idea what encoding support would look like.

**Comment by jsvine** [comment]
Thanks, @spidru! I'd definitely be open to discussing initial ideas/proposals. I think the key will be to have the encoding interoperate easily with pdfplumber's current architecture and object system.

**Comment by spidru** [comment]
Hello again. Apologies progress is rather slow at the moment. I've given PyPDF4 a final try, but I have now fully given up with it, since the classes are clearly not designed to handle modifications to text data in the content stream.

Since you are willing to discuss, I would like to see if pdfplumber can offer something more convenient. To get started, I think the best way is to get more familiar to the code by perhaps looking into some issues myself. Are there any issues (perhaps easy for newcomers to pdfplumber) that you can recommend for me to look into?

**Comment by jsvine** [comment]
Hi @spidru, and thanks for your interest! Apologies that it's taken a while for me to respond. If you'd like a relatively simple issue, you might try this one, since it doesn't require too much knowledge of pdfplumber's internals: https://github.com/jsvine/pdfplumber/issues/222

I'm closing this issue for now, but feel free to reopen if you'd like to restart the PDF encoding discussion.
