### ISSUE TITLE
Which option should i use for this case

### ISSUE THREAD

**Issue by quangtuan202** [jsvine/pdfplumber#207]
I have a table like this.
Plumber pdf works fine for other cases but not in this case.
Some rows border is not continous.
I have gone through your docs with extracting strategy but I still don't understand.
Your help is highly appreciated

![image](https://user-images.githubusercontent.com/63573592/80306569-50748080-87ee-11ea-8e18-23b471560a01.png)

**Comment by jsvine** [comment]
Hi @quangtuan202. It will depend on the actual PDF and code you're using. Unfortunately, PDFs can be quite complicated, to the extent that screenshots often can't tell the whole story.

From a glance, though, you might want to identify the vertical lines of interest, and then use them via the `explicit_vertical_lines` parameter in the table-extraction settings.

Alternatively, increasing `join_tolerance` may work. Documentation of both are in the README.md. 

Closing this issue for now, but feel free to re-open (with code and PDF) if the suggestions above do not work.

**Comment by quangtuan202** [comment]
Thank you. I change horizontal dimension to ‘text’ and it works with a little string concatenation.
