### ISSUE TITLE
Cell of table is skipped

### ISSUE THREAD

**Issue by OD1995** [jsvine/pdfplumber#209]
I am attempting to extract information using the following code:

```
import requests
import pdfplumber
from io import BytesIO

url = "https://nflcdns.nfl.com/liveupdate/gamecenter/57947/WAS_Gamebook.pdf"
req = requests.get(url)
pdf = pdfplumber.load(BytesIO(req.content))
```

I am trying to get the text under the Substitutions header on the first page. As much of the data I am trying to extract is in table form, I have been using `extract_tables`. I am able to get the left set of substitutions with the following code:

`awaySubs = pdf.pages[0].extract_tables()[2][15][0]`

However, I am unable to get the right set of substitutions using `extract_tables`. Why is this? And also, what would be the best way of getting the right set using a different approach? Thank you!

**Comment by jsvine** [comment]
Hi @OD1995. Given that many of the parts of that page aren't very traditional tables, I think you just got lucky with the left-side substitutions. Here's the output from `pdf.pages[0].to_image()debug_tablefinder()`, which demonstrates that:

![image](https://user-images.githubusercontent.com/534702/80558303-e273b900-89a7-11ea-9206-036c080783cc.png)

I think you're probably better off cropping the page based on the horizontal lines and possibly the header text (such as `Substitutions`), and extracting the text from those crops.
