### ISSUE TITLE
page height is a float in python 2.7? 

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#21]
I'm seeing this with a current version of pdf plumber. Seems to only apply to some pages? 

...pdfplumber_env/lib/python2.7/site-packages/pdfplumber/page.py", line 65, in process_object
    attr["top"] =h - attr["y1"]
TypeError: unsupported operand type(s) for -: 'float' and 'Decimal'

**Comment by jsvine** [comment]
Thanks for flagging! Do you have an example PDF that throws this error? For the purposes of reproducing the bug, add a test, and fix it.

**Comment by jsfenfen** [comment]
Here's one: 
[150109DSP-Milw-505-90D.pdf](https://github.com/jsvine/pdfplumber/files/794587/150109DSP-Milw-505-90D.pdf)

**Comment by jsvine** [comment]
Super, thanks!

**Comment by jsvine** [comment]
Many thanks again. Fixed, tested, and incorporated in v0.5.0/#23
