### ISSUE TITLE
Cannot get Text from this pdf

### ISSUE THREAD

**Issue by zbjdonald** [jsvine/pdfplumber#210]
Hi, this is my pdf, I can't get text from this pdf. `pdfplumber = "^0.5.20"`
```
path = settings.BASE_DIR / 'raw_data' / 'hehe.pdf'
with pdfplumber.open(path) as pdf:
        first_page = pdf.pages[0]
        text = first_page.extract_text()
```
![image](https://user-images.githubusercontent.com/5664723/80853271-111cb880-8c62-11ea-8560-2021eeeddd4d.png)
https://zbjdonald-dev.oss-cn-zhangjiakou.aliyuncs.com/%E8%B5%84%E4%BA%A7%E5%87%80%E5%80%BC%E5%85%AC%E5%91%8A_SGW076_%E4%BD%91%E7%BB%B4CTA%E8%BF%9B%E5%8F%96%E4%B8%80%E5%8F%B7%E7%A7%81%E5%8B%9F%E8%AF%81%E5%88%B8%E6%8A%95%E8%B5%84%E5%9F%BA%E9%87%91_2020-04-17.pdf

**Comment by jsvine** [comment]
That looks like it's related to how `pdfminer.six` is parsing the document. Based on feedback from other users, it's possible that this has something to do with recent changes to that library. You might try downgrading `pdfminer.six` either to an earlier release, or the version published last week: https://pypi.org/project/pdfminer.six/#history
