### ISSUE TITLE
extract_table and extract_not working.

### ISSUE THREAD

**Issue by kvora99** [jsvine/pdfplumber#211]
I have a large pdf which contains various tables, I am extracting that table using OpenCV contour method and then dumping that image contour into pdf. Then applying pdfplumber methods to extract tabular data but its throwing error "IndexError: list index out of range", I have tried all using table_settings parameter but it didn't work.
Please help me to fetch data from pdf, generated from an image.

**Comment by jsvine** [comment]
Hello, and thanks for your interest in this library. As noted in the readme, however, pdfplumber is designed for use with non-image/scanned PDFs.
