### ISSUE TITLE
How to ignore blank pages?

### ISSUE THREAD

**Issue by lanw0622** [jsvine/pdfplumber#214]
Hi, there

As per the title. I'm trying to extract tables from a pdf which has some blank pages. 
Can pdfplumber identify and ignore them?

Many thanks!

**Comment by samkit-jain** [comment]
If a page is completely blank, you can run `.extract_text()` and consider the page to be blank if the result is null or an empty string.

**Comment by lanw0622** [comment]
@samkit-jain  That worked, Many thanks! How can I forget this! 

I imported PyPDF2 package, analysized the difference between full page and blank page, and found that ` "/Font" `is not in blank pages' `"/Resources".keys()`......I am so stupid!

Thanks again!
