### ISSUE TITLE
Documentation: Missing Objects

### ISSUE THREAD

**Issue by Mahendra114027** [jsvine/pdfplumber#219]
Hi, are images and figures removed from the newest version of PdfPlumber? They are not available under objects section of the documentation.

**Comment by jsvine** [comment]
There have been no explicit changes to image or figure access in pdfplumber recently. It's possible that you're encountering a bug, but it's hard to tell without more information. Can you provide a PDF and code that replicates the issue you're seeing?

**Comment by Mahendra114027** [comment]
I am able to access the said objects. Only that the documentation from the homepage doesn't show images, figures, in the https://github.com/jsvine/pdfplumber#objects section. So I thought these will be discontinued in future releases. Hence the question.

**Comment by jsvine** [comment]
Ah, thank you for explaining. That's a good point. I have now made sure to mention them in the documentation.
