### ISSUE TITLE
Error while using crop method to get back the content

### ISSUE THREAD

**Issue by luckysunda** [jsvine/pdfplumber#221]
I have just discovered pdfplumber and experimenting with it. I am trying to get back the content using the crop method.  I am passing the correct values of x0, top, x1, bottom to crop method but getting the following error:

```

import pdfplumber
pdf=pdfplumber.open("one.pdf")
first_page=pdf.pages[0]
print(first_page.chars[0])
{'fontname': 'ACOLSB+AvenirLTStd-Book', 'adv': Decimal('0.593'), 'upright': 1, 'x0': Decimal('36.000'), 'y0': Decimal('471.060'), 'x1': Decimal('41.930'), 'y1': Decimal('483.140'), 'width': Decimal('5.930'), 'height': Decimal('12.080'), 'size': Decimal('12.080'), 'object_type': 'char', 'page_number': 1, 'text': 'E', 'top': Decimal('128.860'), 'bottom': Decimal('140.940'), 'doctop': Decimal('128.860')}
```
Earlier I was using crop method like this:
```
first_page.crop(36.000, 128.860, 41.930, 140.940)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-50e24b9fa176> in <module>
----> 1 first_page.crop(36.000,128.860,41.930, 140.940)

TypeError: crop() takes 2 positional arguments but 5 were given

```

I think we are supposed to use it like following:
```
print(first_page.crop([36.000, 128.860, 41.930, 140.940]))
<pdfplumber.page.Page.crop.<locals>.CroppedPage object at 0x7f7e847f9710>
```
But still I am not able to print the content.

**Comment by samkit-jain** [comment]
You should try this to correctly crop a page.

```python
import pdfplumber

pdf = pdfplumber.open("one.pdf")
first_page = pdf.pages[0]

# Crop the page
cropped_page = first_page.crop((36.000, 128.860, 41.930, 140.940))

# Print text of the cropped region
print(cropped_page.extract_text())
```

**Comment by luckysunda** [comment]
> You should try this to correctly crop a page.
> 
> ```python
> import pdfplumber
> 
> pdf = pdfplumber.open("one.pdf")
> first_page = pdf.pages[0]
> 
> # Crop the page
> cropped_page = first_page.crop((36.000, 128.860, 41.930, 140.940))
> 
> # Print text of the cropped region
> print(cropped_page.extract_text())
> ```

Hey thanks, I got the text. I know it was a small doubt but thanks for solving it.
