### ISSUE TITLE
upgrade the version of pdfminer.six

### ISSUE THREAD

**Issue by youngquan** [jsvine/pdfplumber#224]
I read the release notes from [here](https://github.com/pdfminer/pdfminer.six/releases).
It seems that pdfminer.six>=20200104 could also works.

**Comment by jsvine** [comment]
Thanks for mentioning this! Upgrading to `pdfminer.six==20200517` causes a couple of errors in the test suite. It seems like this is happening because of changes to pdfminer's layout analysis algorithm. I'll have to dig into this a bit more before deciding the best resolution.

**Comment by jsvine** [comment]
I looked into it, and it appears the broken tests were due to true *improvements* in `pdfminer.six`'s layout analysis. I have now updated the `pdfminer.six` requirement in the latest `pdfplumber` version (v0.5.22). Thanks for the suggestion!
