### ISSUE TITLE
Handling off-axis tables with no lines

### ISSUE THREAD

**Issue by ryanskene** [jsvine/pdfplumber#226]
Just wondering if anyone has come up with a strategy for handling off-axis tables. I know the module works better with digitally-generated pdfs but I have a project where I have a mix of digital and scanned and most of the scanned images are rotated. None of the tables have explicitly drawn lines.

So, for example, the text of rows might be rotated such that strict horizontal lines won't properly contain them. It does not appear possible to simply provide horizontal lines with an ((x,y), (x.y)) structure and it doesn't look like a line object can simply be created either.

For now, I'm just going to crop the tables into pieces (that do work better with axis lines) and then join them together. Perhaps there's a more elegant solution out there.

Btw, im behind corporate firewall and cannot utilize ImageMagick

**Comment by jsvine** [comment]
Hi @ryanskene, and thanks for your interest in this library! Given `pdfplumber`’s focus on digitally-generated PDFs, I’m going to close this comment. But if anyone does have suggestions — now or later — feel free to chime in on this thread.
