### ISSUE TITLE
Did not extract texts with symbols in right order.

### ISSUE THREAD

**Issue by Freakwill** [jsvine/pdfplumber#227]
I read the document of pdfplumber and try to replace pdfminer3 in some case.
However, I extracted text from a math paper, got the follows (partly) by `print(page.extract_text())`

> The following fact is among the cornerstones of Linear Programming.
> ×
> Theorem 1 (Farkas lemma). Let A be a matrix of size m n and b be a column vector of size n.
> Exactly one of the following is true:
> ∈ R ≥
> 1. There exists x n such that Ax = b and x 0.
> ∈ R (cid:62) ≥ (cid:62)
> ...

It shown × before Theorem1, but in fact it appears between m and n, i.e. m × n, also other symbols such as ∈ R ≥; while pdfminer3 prints them in right order

> The following fact is among the cornerstones of Linear Programming.
> Theorem 1 (Farkas lemma). Let A be a matrix of size m × n and b be a column vector of size n.
> Exactly one of the following is true:
> 1. There exists x ∈ Rn such that Ax = b and x ≥ 0.
> 2. There exists y ∈ Rm such that A(cid:62)y ≥ 0 and b(cid:62)y < 0.

**Comment by jsvine** [comment]
Thanks for your interest in this library, @Freakwill. It's a bit hard to debug this issue, however, without the PDF itself. Can you provide it?

**Comment by Freakwill** [comment]
You can use any math paper. This is the test paper https://pan.baidu.com/disk/pdfview?path=%2FMaths%2FFarkas.pdf.

**Comment by jsvine** [comment]
Hello, and thanks. Unfortunately, when I click that link, I get this:

<img width="253" alt="Screen Shot 2020-07-18 at 10 17 06 AM" src="https://user-images.githubusercontent.com/534702/87854425-e563b300-c8df-11ea-985e-cc7ab7540460.png">

**Comment by Freakwill** [comment]
Could you give me your email or the account of skype? Or just load a math paper from the web for example http://math.nsc.ru/LBRT/g2/english/ssk/spb-18.pdf.

**Comment by jsvine** [comment]
Thank you for the example PDF. That one seems solvable by reducing the `x_tolerance` and `y_tolerance` parameters from their default setting of `3`, e.g.: `page.extract_text(y_tolerance = 1, x_tolerance = 1)`

This makes sense, as lines in mathematical equations are often printed much closer together than in typical text.

Closing this issue for now, but let me know if you come across examples that cannot be resolved by adjusting those parameters.
