### ISSUE TITLE
Question: What are the page sizes measured in?

### ISSUE THREAD

**Issue by rosswf** [jsvine/pdfplumber#229]
What are the page sizes measured in? I have a PDF where adobe  is reporting the page size as around 16.5" wide.

page.width has a value of around 1190. What unit of measurement is this?

**Comment by jsvine** [comment]
According to the PDF spec, the standard unit of measurement is "points," with 72 points/inch: https://www.pdfscripting.com/public/PDF-Page-Coordinates.cfm

`1190 / 72 = 16.52`, so that seems to line up with what Adobe is reporting to you.
