### ISSUE TITLE
how to merge table from different page

### ISSUE THREAD

**Issue by YellowDong** [jsvine/pdfplumber#232]
Tables are distributed on different two pages, and how to merge into the same table
![无标题](https://user-images.githubusercontent.com/23050255/87745852-9a836600-c821-11ea-8ada-765f144f1791.png)

**Comment by jsvine** [comment]
Hello, and thank you for the helpful illustration. There’s no specific feature within `pdfplumber` for merging tables. But if you extract the two tables separately, you can likely write some Python code to combine the results.
