### ISSUE TITLE
the first line text can't extract

### ISSUE THREAD

**Issue by YellowDong** [jsvine/pdfplumber#233]
hello @jsvine Your work is fantastic. now，I have a problem with you and ask for your help. when i call page.extract_tables() method,I can't get the first line of text messages. Do I need to set up something to get it? Here's a screenshot of my debug.
![image](https://user-images.githubusercontent.com/23050255/88146250-351ee300-cc2e-11ea-80a2-5fa5e6903e6b.png)

![image](https://user-images.githubusercontent.com/23050255/88146498-89c25e00-cc2e-11ea-8b84-5f2803e6a182.png)
thanks!

**Comment by jsvine** [comment]
Hi @YellowDong, and thank you for sharing the visually debugging output!

However, I'm not certain I understand this part of your question: "I can't get the first line of text messages." Can you explain more?

Is it that you expect the box at the very top of the page to be interpreted as a table? If so, yes, there is an explanation: pdfplumber only finds tables with __at least two cells__. (See [this line of code](https://github.com/jsvine/pdfplumber/blob/e99a66470153824a492b2d0b05ac6e81a1e09384/pdfplumber/table.py#L315).) The idea is to distinguish between tables and simple rectangles. Perhaps it would be helpful to give users the option to change that setting?

In the meantime, you could capture the text in the top rectangle by (a) identifying the rectangle, (b) running `page.crop(...)` with the rectangle's dimensions, and then, (c) running `cropped_page.extract_text()`.

**Comment by YellowDong** [comment]
Thank you for answering my question in detail.Yes, I'm talking about getting the text inside the rectangle.I will take the advice you gave. However, I don't know how to identify the rectangle.I need to fumble ！=-=

**Comment by jsvine** [comment]
Thanks for the response, @YellowDong. I’ve opened a new issue proposing that addition to the user options. In the meantime, you should be able to find all rectangles via `page.rects`.
