### ISSUE TITLE
is there a way to extract PDF title if not present in the metadata

### ISSUE THREAD

**Issue by ibrahimshuail** [jsvine/pdfplumber#234]
I need to capture the title of the pdf file if it's not present in the metadata as same pdftitle

**Comment by jsvine** [comment]
It will depend on the specific PDF you’re examining. But a generally useful approach might be to select all `char` objects with a `size` of a certain value or larger.

**Comment by ibrahimshuail** [comment]
I tried it but it doesn't work, is there any methods related to the above

**Comment by jsvine** [comment]
Unfortunately, it's very hard to answer this question without a specific example of a PDF. Can you provide one, and the code you're currently using to analyze it?

**Comment by ibrahimshuail** [comment]
please find the sample pdf (http://africau.edu/images/default/sample.pdf) I need to extract only the larger text out of this. below mentioned I tried but not sure.

def extract_words(chars, x_tolerance=False,y_tolerance=False,keep_blank_chars=False,match_fontsize=False,match_fontcolor=True,match_fontname=True)

**Comment by jsvine** [comment]
You could do something like this:

```python
import pdfplumber
pdf = pdfplumber.open("sample.pdf")
page = pdf.pages[0]

filtered = page.filter(lambda x: x.get("size", 0) > 20)
filtered.extract_text()
```

Result: `' A Simple PDF File '`

Another approach, if you use pandas:

```python
import pandas as pd
import pdfplumber
pdf = pdfplumber.open("sample.pdf")
page = pdf.pages[0]

(
    pd.DataFrame(page.chars)
    .loc[lambda df: df["size"] == df["size"].max()]
    .pipe(lambda df: "".join(df["text"]))
)
```

Result: `' A Simple PDF File '`
