### ISSUE TITLE
I can't download/install pdfplumber

### ISSUE THREAD

**Issue by GraceGong83** [jsvine/pdfplumber#237]
I can't download/install pdfplumber. I just use pip install pdfplumber. but here is the error. 
![image](https://user-images.githubusercontent.com/53991939/88304309-ad72ca80-cd3a-11ea-8e41-2bcaa7cff769.png)

**Comment by jsvine** [comment]
Judging by the error message, it looks like your computer was having trouble connecting to pythonhosted.org, which hosts Python packages. Closing this issue, since it appears to be unrelated to pdfplumber, but feel free to reopen if the problem persist and is specific to this library.
