### ISSUE TITLE
Save pdf file after cropping a page

### ISSUE THREAD

**Issue by AntonioMarsella** [jsvine/pdfplumber#240]
Hi,
I need to use the pdfminer pdf2txt.py script, so I think I need to save the cropped pdf that I get from here. Is there a way to save a cropped single page into a .pdf format file?

Thank you

**Comment by jsvine** [comment]
Hi @AntonioMarsella, pdfplumber currently focuses only on analyzing PDFs, not generating them. For your purposes (cropping a PDF and then saving the result), you might try either of these tools:

- https://github.com/claird/PyPDF4
- https://community.coherentpdf.com/
