### ISSUE TITLE
extracting text from a two columns page

### ISSUE THREAD

**Issue by fdq09eca** [jsvine/pdfplumber#244]
I extract the text of the following page:
![image](https://user-images.githubusercontent.com/51902242/89656554-548c6000-d8fe-11ea-819f-fb1fad409c79.png)

I used the following code
```python
import requests, pdfplumber
from io import BytesIO
url = 'https://www1.hkexnews.hk/listedco/listconews/sehk/2020/0428/2020042801961.pdf'
rq = requests.get(url)
pdf = pdfplumber.load(BytesIO(rq.content))
page = pdf.pages[62]
txt = page.extract_text()
print(txt)
```
it produce this 
![image](https://user-images.githubusercontent.com/51902242/89657657-fa8c9a00-d8ff-11ea-9655-1f1610ec6f55.png)

I want to turn two columns ending section, see below, into two rows
![image](https://user-images.githubusercontent.com/51902242/89657217-4c80f000-d8ff-11ea-85e0-c7906e1b2521.png)

such that it is 

```
Mazars CPA Limited
Certified Public Accountants
Hong Kong, 22 April 2020
The engagement director of Mazars CPA Limited on the
audit resulting in this independent joint auditors report
is:
She Shing Pang Yan Tat Wah, Joseph
Practising Certificate number: P05510
LKY China
Certified Public Accountants
Hong Kong, 22 April 2020
The engagement partner of LKY China on the audit 
resulting in this independent joint auditors report is:
```

not sure if it is possible. It will be great that if there is a function which returns boolean that show if the ending is a two-columns. Any suggestion will be appreciated!

**Comment by samkit-jain** [comment]
Hi @fdq09eca , thanks for showing interest in the library. This is something not possible since when extracting text, it goes top to down and left to right. To get the text in the way you desire, you would have to come up with your own logic. One possible workaround could be to (assuming that the 2 columns section is a table) extract table and then read the text column by column.

**Comment by samkit-jain** [comment]
Another possible solution, specific to the page 63 could be:

1. Crop the page into 2 equal haves vertically and removing the top 40% portion and bottom 10% assuming the interested region is only that 2-column section.
    ```python
    left = page.crop((0, 0.4 * float(page.height), 0.5 * float(page.width), 0.9 * float(page.height)))
    right = page.crop((0.5 * float(page.width), 0.4 * float(page.height), page.width, 0.9 * float(page.height)))
    ```
2. Extract text from the left half.
    ```python
    left.extract_text()
    ```
3. Extract text from the right half.
    ```python
    right.extract_text()
    ```

**Comment by fdq09eca** [comment]
@samkit-jain excellent work-around!

**Comment by samkit-jain** [comment]
Glad it helped you out. Thanks to you @fdq09eca as well as I found a bug (#245 ) when working on this.

**Comment by cmicek1** [comment]
Is there no general solution to this problem though? I have a dataset of 100 or so scientific papers I'm trying to parse, and having text extraction just smush the columns together is a bit problematic when I'm trying to see certain parts in context.

**Comment by samkit-jain** [comment]
@cmicek1 Could you please share a sample PDF that you are dealing with and elaborate on the problem that you are facing along with a reproducible code and the result that you are getting?

**Comment by jsvine** [comment]
> Is there no general solution to this problem though?

This StackOverflow page provides some interesting insight into this very question: https://stackoverflow.com/questions/22675690/if-identifying-text-structure-in-pdf-documents-is-so-difficult-how-do-pdf-reade

**Comment by danielbellhv** [comment]
> 1. Crop the page into 2 equal haves vertically and removing the top 40% portion and bottom 10% assuming the interested region is only that 2-column section.

How might I do this **conditionally**? Only if when a page does have column text @samkit-jain

**Comment by samkit-jain** [comment]
@danielbellhv It would depend on the PDFs you are dealing with. A sophisticated solution might be to use a layout analysis algorithm to identify whether a page is multi column or not.

A simpler solution could be to crop the page keeping the middle 5% and run text extraction on it to see if there's any text or not. If no text, then there could be 2 columns. Of course, you will have to tweak the 5% and see what best fits your need. This also assumes that the full page is in a 2 column layout.

**Comment by danielbellhv** [comment]
Would you mind copying and pasting that as a comment under my [SO post](https://stackoverflow.com/q/70170544/16105404), please? I will try **middle 5%** :)

**Comment by danielbellhv** [comment]
I have since solved my own sub-issue, using **pdfminer**. Answered [here](https://stackoverflow.com/a/70187426/16105404). Thanks for your input

**Comment by ameymn** [comment]
You can use PyPDF2 instead of pdfplumber there it reads the pdf  left side first and then the right side just like humans do .Hence  if you use PyPDF2 no need splitting the page .

**Comment by mzhadigerov** [comment]
@ameymn yes, but PyMuPdf is under gpl license

**Comment by abubelinha** [comment]
> You can use PyPDF2 instead of pdfplumber there it reads the pdf left side first and then the right side just like humans do. Hence if you use PyPDF2 no need splitting the page

@ameymn can you post a link to a example code of that specific PyPDF2 usage?
Thanks
@abubelinha

**Comment by ameymn** [comment]
This is my code which I used 
<img width="272" alt="Screenshot 2023-06-26 154357" src="https://github.com/jsvine/pdfplumber/assets/84408423/a8bbf850-31e5-4cbd-ad05-a22b12774daf">

You can read this documentation if you need any help 

https://pypdf2.readthedocs.io/en/3.0.0/index.html

@abubelinha

**Comment by eshwarbc30** [comment]
> Is there no general solution to this problem though? I have a dataset of 100 or so scientific papers I'm trying to parse, and having text extraction just smush the columns together is a bit problematic when I'm trying to see certain parts in context.

did you got any solution for this? I need extract text from pdf containing 2 pdf format.

**Comment by eshwarbc30** [comment]
> Is there no general solution to this problem though? I have a dataset of 100 or so scientific papers I'm trying to parse, and having text extraction just smush the columns together is a bit problematic when I'm trying to see certain parts in context.

hi, @cmicek1 Did you get any solution for this?
