### ISSUE TITLE
Can't install pdfplumber

### ISSUE THREAD

**Issue by gui1herme** [jsvine/pdfplumber#246]
Hello
This is my first attempt at using Python. Following a YouTube tutorial, but can't go past the installation of pdfplumber. Could some one guide me?
I could successfully install jupyterlab, pandas, requests, scipy, and xlrd. No luck with pdfplumber. Tried Googling this issue but I have no idea what to look for, to be honest.

I'm using the latest Miniconda version (3.8).

This is the error:
![Untitled](https://user-images.githubusercontent.com/48537496/89741027-33458400-da64-11ea-9ffa-bf98f6517d22.png)

Thanks in advance.

**Comment by samkit-jain** [comment]
Hi @gui1herme Thanks for your interest in the library. The package can be installed using `pip`. `conda` not supported. Instead of running `conda install pdfplumber`, please run `pip install pdfplumber`.
