### ISSUE TITLE
First and last row of table with only horizontal line cannot be extract

### ISSUE THREAD

**Issue by amouro** [jsvine/pdfplumber#247]
## What are you trying to do?

Extract data from a table with only horizontal line.

## What code are you using to do it?

```
		tables = page_crop.find_tables({
			    "vertical_strategy": "text", 
			    "horizontal_strategy": "lines",
		})
		page_crop.to_image(resolution=200).debug_table(tables[0]).save("./deb.png", format="PNG")
```

## PDF file

[PDF](https://github.com/jsvine/pdfplumber/files/5049210/064_968_p5.pdf)

## Expected behavior

All table content are extracted.

## Actual behavior

First and last row in the bbox are not extracted.

## Screenshots

![table](https://user-images.githubusercontent.com/3444618/89753716-3b5cfc80-db14-11ea-8161-9ed3b0f02b71.png)

![table_crop](https://user-images.githubusercontent.com/3444618/89753715-3a2bcf80-db14-11ea-96e0-62eff0530e19.png)

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

Tried another table settings with explicit horizontal lines. Still cannot extract the first and last rows.

```
tables = page_crop.find_tables({
			    "vertical_strategy": "text", 
			    "horizontal_strategy": "explicit",
			    "explicit_horizontal_lines": rects_to_edges(page.rects)
		})
```

**Comment by samkit-jain** [comment]
Hi @amouro Thanks for your interest in the library. When using the settings as 
```
{
    "vertical_strategy": "text", 
    "horizontal_strategy": "lines"
}
```
and saving the image with `.debug_tablefinder()`, you'll notice that in the bottom portion, there is some difference between the vertical lines and horizontal lines.
![image](https://user-images.githubusercontent.com/15127115/89765245-94786080-db13-11ea-987b-46c0a9a722b1.png)

To get around this, you would need to use `intersection_tolerance`. Try using the following
```
{
    "vertical_strategy": "text",
    "horizontal_strategy": "lines",
    "intersection_y_tolerance": 15,
}
```

**Comment by amouro** [comment]
Thank you @samkit-jain, it does resolve my problem.

I am curious what is your code creating the `.debug_tablefinder()` image. I wasn't able to save the image with any line in your screenshot.

**Comment by samkit-jain** [comment]
Here you go,
```python
import pdfplumber

table_settings = {
    "vertical_strategy": "text",
    "horizontal_strategy": "lines",
    "intersection_y_tolerance": 15,
}

pdf = pdfplumber.open("file.pdf")
p0 = pdf.pages[0]
im = p0.to_image()
im.reset().debug_tablefinder(table_settings)
im.save("image.png", format="PNG")
```
