### ISSUE TITLE
how to ignore the text that is at the edge of the page?

### ISSUE THREAD

**Issue by fdq09eca** [jsvine/pdfplumber#248]
```python
url, page = 'https://www1.hkexnews.hk/listedco/listconews/sehk/2019/1004/ltn20191004413.pdf', 75
rq = requests.get(url)
pdf = pdfplumber.load(BytesIO(rq.content))
txt = pdf.pages[page].extract_text()
txt = re.sub("([^\x00-\x7F])+", "", txt)  # no chinese
print(txt)
```
Here is part of the result
![image](https://user-images.githubusercontent.com/51902242/89818749-ddb0ca80-db7c-11ea-87b1-d32211c7f9ba.png)

Here is the page
![image](https://user-images.githubusercontent.com/51902242/89818597-9d514c80-db7c-11ea-80d3-7a86cef46224.png)
the edge test is the source of noise and it is unwanted.. how may I extract the main text without them?

**Comment by samkit-jain** [comment]
Hi @fdq09eca You can try cropping the page and then extracting the text of the cropped page.

**Comment by jsvine** [comment]
Thanks @samkit-jain! And just to clarify, @fdq09eca: You would do this by running `page.crop(...)`. More details in the documentation here: https://github.com/jsvine/pdfplumber#the-pdfplumberpage-class
