### ISSUE TITLE
page.extract_words() and page.extract_text()  output is empty

### ISSUE THREAD

**Issue by NeoWang9999** [jsvine/pdfplumber#269]
## Describe the bug

page.extract_words() and page.extract_text()  output is empty

## Code to reproduce the problem

```
import pdfplumber
pdf = pdfplumber.open(pdf_path, laparams={"word_margin": 1.0})
for p in pdf.pages:
    words = p.extract_words(keep_blank_chars=True)
    texts = p.extract_text()
    print(words, texts)

```

## PDF file

[Sponsorship Agreement Template (CN) 1-未改动.pdf](https://github.com/jsvine/pdfplumber/files/5198715/Sponsorship.Agreement.Template.CN.1-.pdf)

## Expected behavior

output is not empty

## Environment

- pdfplumber version: [0.5.23]
- Python version: [3.7.7]
- OS: [Mac OS]

## other note

when i tried with pdfbox like:
```

p = pdfbox.PDFBox()
p.extract_text(input_path=f_path, console=False)

```
it worked fine and output the txt file. but I need the chars coordinate information.

Please help me solve this problem, thank you.

**Comment by samkit-jain** [comment]
Hi @NeoWang9999 Thanks for your interest in the library. The reason `pdfplumber` is not able to extract text is because this PDF does not contain any embedded font.
![image](https://user-images.githubusercontent.com/15127115/92692606-0be31f00-f362-11ea-9bf3-aa59c6c809d3.png)
The reason `pdfbox` is able to extract could most likely because of it substituting the missing font. When the PDF viewer substitutes a font, the result usually isn't what you intended.

**Comment by NeoWang9999** [comment]
Hi @samkit-jain thanks for your reply！ according 

> "The reason pdfbox is able to extract could most likely because of it substituting the missing font."

Is there any effort to make pdfplumber achieve the same results? Because it looks like the necessary information does exist in the file, just we need to do some extra processing to read it correctly.
thank you.

**Comment by samkit-jain** [comment]
@NeoWang9999 This feature request would be more suited for [pdfminer](https://github.com/pdfminer/pdfminer.six) since that is what `pdfplumber` relies upon. I am closing this issue for the same reason. Feel free to reopen if you have a different proposition.

**Comment by mkl-public** [comment]
As an aside:

> The reason pdfbox is able to extract could most likely because of it substituting the missing font.

No, there is no need for that, the PDF objects describing the font provide all the information needed, an *Encoding* value of *GB-EUC-H* or *GB-EUC-V* and a *CIDSystemInfo* _ROS_ Adobe-GB1-0.
