### ISSUE TITLE
spisific data in PDF

### ISSUE THREAD

**Issue by Arwa200** [jsvine/pdfplumber#271]
Hi, 
I would like to ask how can I extract specific entered data from pdf these data into CSV? 
I've tried with metadata but for some reason it's not working as well as I tried 
`curl "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf" > background-checks.pdf
pdfplumber < background-checks.pdf > background-checks.csv` 
in terminal but I got empty CSV

**Comment by samkit-jain** [comment]
Hi @Arwa200 Thanks for your interest in the library. It looks like you combined the 2 commands into one. You have to run them one by one
```sh
curl "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf" > background-checks.pdf

pdfplumber < background-checks.pdf > background-checks.csv
```
or combine via "&&" like 
```sh
curl "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf" > background-checks.pdf && pdfplumber < background-checks.pdf > background-checks.csv
```

Feel free to reopen the issue if you still get an empty CSV as the output.
