### ISSUE TITLE
Strange characters when extracting text

### ISSUE THREAD

**Issue by dasapa** [jsvine/pdfplumber#274]
Hello,

I have extracted data from several invoices, everything has gone perfectly, but with one when I extract text it shows characters like the following:

**_++IIKKB=B?=J?KJHK=HJ=@ +IKJH=!="&& 
+IKJH= !=$#'! 

 +@A=ECK=+=@A=CK=
-LK?E?IK
-LK?E?IK 6EFKI6EFCAAH= !=$#" '&
6EFKI6EFAIFA?BE? !=$"&$ %%&
 #_**

Any suggestions if it can be fixed?

Thank you

**Comment by samkit-jain** [comment]
Hi @dasapa Thanks for your interest in the library. Could you please share the PDF so that we can investigate further? What happens when you use `pdftotext`? Is the text captured correctly?

**Comment by dasapa** [comment]
Hi Samkit,

thanks for the answer, there are two pdf files in wetransfer link. What is pdftotext? other librarie?

https://wetransfer.com/downloads/932b33efbce9be5fb51972d908bf5d7c20200927190237/e3355946c178b7b3430d4d07d60807be20200927190304/ee1009

**Comment by samkit-jain** [comment]
Thanks for sharing the PDFs @dasapa [`pdftotext`](https://www.xpdfreader.com/pdftotext-man.html) is a utility to extract text from PDFs.

In the PDF, if you try and copy-paste, gibberish comes out. It is sometimes done intentionally by the PDF creators to prevent people from copy-pasting text from the PDF in which the unicode mapping (what character a glyph represents) is not included in the PDF or is incomplete. One workaround could be to run OCR on the PDF.

**Comment by SAIVENKATARAJU** [comment]
I am having the same issue. In my case most of the lines are replacing with question mark. most of the lines are getting lost

**Comment by afierro23** [comment]
@SAIVENKATARAJU were you able to figure out why you were getting the question marks?   I am having a similar issue on some pdfs.   

Thanks!

**Comment by SAIVENKATARAJU** [comment]
@afierro23  In my case, I am not able to do because the pdf creators itself use custom  encoding techniques to avoid copying, We should go with OCR if required.
