### ISSUE TITLE
word-level font names and heights

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#28]
Having a font for an entire word helps parsing. A lot. Height also helps some. 

I took a crack at this here, with some settings. Defaults also may need adjustment.

If you've got thoughts, @jsvine, lemme know and I can clean this up into a pr. Haven't gotten the testing set up yet. 

https://github.com/jsfenfen/pdfplumber/commit/847a3bbe637e4a3c6bf7a8151eeccf166b3d4fdf

**Comment by jsfenfen** [comment]
I guess with word heights I'm going back and fourth on averaging them or taking the mode; left the latter in for the moment.

**Comment by jsvine** [comment]
Thanks! I like this. For testing's sake: Do you have shareable examples of PDFs where chars that *should* belong to the same word either have different heights or fontnames?

**Comment by jsfenfen** [comment]
So I still haven't heard back about the files that originally required this. I could pretty easily just *make up* a sample pdf that failed the font height test, though obviously having an example would be better... The other time this stuff (can) come up is when the word tolerance is set too high and words run together inadvertently--though only if adjacent cells have different fonts. Will look around a bit.

**Comment by jsvine** [comment]
No worries. Thinking through this a bit. I'm tempted to, by default, group words by fonts, size, *and* color. (Yes, upcoming versions of `pdfplumber` will include font color!) Boolean params could turn them off. I.e., defaults would be:

```python
def extract_words(chars,
  x_tolerance=DEFAULT_X_TOLERANCE,
  y_tolerance=DEFAULT_Y_TOLERANCE,
  keep_blank_chars=False,
  match_fontsize=True,
  match_fontcolor=True,
  match_fontname=True
)
```

That'd mean losing some of the flexibility of, e.g., `DEFAULT_FONT_HEIGHT_TOLERANCE`, but might make the options clearer. It'd also mean avoiding having to calculate the average/mode values for `tolerance`-ed attributes. For instance, this ...

```python
page.extract_words()
```

.... might return ...

```python
[ {
  "text": "Hello",
  "fontsize": 12,
  "fontname": "ArialBold",
  "fontcolor": "#000000"
} ]
```

... while ...

```python
page.extract_words(match_fontsize=False)
```

.... would return ...

```python
[ {
  "text": "Hello",
  "fontname": "ArialBold",
  "fontcolor": "#000000"
} ]
```

What do you think? Too inflexible?

**Comment by jsfenfen** [comment]
I think that's great! 

Also, I think whatever adjustments might be needed will become more obvious the more pdfs we trawl through...

**Comment by jsfenfen** [comment]
I got a different sample of the docs with the font height thing! Going through them, uh, soonish.

**Comment by jsfenfen** [comment]
Ok, I have this working in the word_fonts branch [here](https://github.com/jsfenfen/pdfplumber/tree/word_fonts) using made up pdfs as [tests](https://github.com/jsfenfen/pdfplumber/blob/word_fonts/tests/test_fonts.py). Trying to dig up the sample observed in the wild.

Am doing this with a custom WordFontError subclassed from RuntimeError, but am open to suggestions...

No idea if this will be at all helpful ahead of 0.60 rewrite, but...

**Comment by jsvine** [comment]
Ooh, thanks! Will definitely aim to incorporate this (or something close to it) into the next big release.

**Comment by krishnakt031990** [comment]
Is this in the current version? I am looking for font name and font size per work and not per letter.

**Comment by jsfenfen** [comment]
hey @krishnakt031990 I don't think so, though the version I did of it is still here:  https://github.com/jsfenfen/pdfplumber/tree/master . I guess there's a minor release that's been added since, I will update when I've got a sec. 
@jsvine it looks like the [pr](https://github.com/jsvine/pdfplumber/pull/32) doesn't have squashed commits? this isn't a big change, though would be clearer if I could squash those. Hmm.

**Comment by krishnakt031990** [comment]
Works perfectly! thanks @jsfenfen. Just have another question regarding the document. Did you try to reverse engineer to build a pdf out of the extracted properties of text? Just wanted some tips to create one if you did look into doing it.

**Comment by jsfenfen** [comment]
"Did you try to reverse engineer to build a pdf out of the extracted properties of text?"
No.... I'm not sure I get the use case--couldn't you just use the original pdf? But if you really want to create a pdf from objects of your choosing, maybe https://bitbucket.org/rptlab/reportlab ?

**Comment by krishnakt031990** [comment]
@jsfenfen it is just to show the business that they can rebuild the pdf using these properties - and  for them to compare the original and the generated one from the properties we extracted.

**Comment by krishnakt031990** [comment]
@jsfenfen one more thing that I have seen is that the fonts that have been extracted have a style which says AllOrNone. I believe it is not a valid font. I get that for almost all the words.

**Comment by jsfenfen** [comment]
@krishnakt031990 is this a pdf that's been OCR'ed? Fonts aren't very reliable in most of the OCR I've seen--could this have been set there? Also possible this is a pdfminer thing? Can you share a doc that does this?

**Comment by krishnakt031990** [comment]
For the font size.. the point size is about 2-3 pts more than the actual font. I can give an example with an image here.

![image](https://user-images.githubusercontent.com/7476799/31902611-43301862-b7da-11e7-96cc-fcc47636cfcc.png)

See that extra spacing on top of **My**?

**Comment by Saqhas** [comment]
@jsvine Is this issue resolved and the functionality added.

**Comment by jsvine** [comment]
This functionality has not yet been added. I'm certainly open to adding it, but haven't had the time quite yet.

**Comment by Saqhas** [comment]
I wanted this functionality in one of my project. I have done some changes in the repo code to support  this functionality, should I push it in a branch and create pull request. So that we can discuss and add it.

**Comment by jsvine** [comment]
Thanks, @Saqhas! It's definitely worth a discussion and opening a pull request. I'm not certain I'll use your code, but it could definitely be helpful inspiration and I would certainly credit you for that.

**Comment by ibrahimshuail** [comment]
can we capture based on the font size, for eg if my font size is 12 I need the relevant words from that?

**Comment by jsvine** [comment]
@ibrahimshuail See my response to the separate issue you opened, #234

**Comment by jsvine** [comment]
Closing this now-done issue. Per merged PR above, this feature was added last year! 🎉
