### ISSUE TITLE
Raising KeyError when I tried to extract text from PDF file

### ISSUE THREAD

**Issue by coderliuhao** [jsvine/pdfplumber#284]
`with pdfplumber.open("example/paper.pdf") as p:
    page = p.pages[1]
    print(page.extract_text())`

raise KeyError:"ID"

paper.pdf is a chinese article after renaming

**Comment by samkit-jain** [comment]
Hi @coderliuhao and appreciate your interest in the library. Could you please provide the following so that we can investigate further?
1. `pdfplumber` version, Python version and the OS.
2. Correctly formatted reproducible code.
3. The PDF.

**Comment by jsvine** [comment]
Hi @coderliuhao, I'm just checking in on this. Can you provide the information/PDF requested above?

**Comment by coderliuhao** [comment]
Sorry for lately response,I thought I can find a solution of my issue



At 2020-11-02 07:09:37, "Jeremy Singer-Vine" <notifications@github.com> wrote:

Hi @coderliuhao, I'm just checking in on this. Can you provide the information/PDF requested above?
