### ISSUE TITLE
AttributeError: 'Page' object has no attribute '_objects'

### ISSUE THREAD

**Issue by samkit-jain** [jsvine/pdfplumber#293]
## Describe the bug

Instance variable `_objects` in class `Page` accessed before assignment in `dedupe_chars()`. `_objects` gets instantiated only when the property method `objects` of the `Page` class is invoked. Source: https://github.com/jsvine/pdfplumber/blob/04fd56ac405fd753e7f9c826ce103459013f2e71/pdfplumber/page.py#L148-L153

## Code to reproduce the problem

```python
import pdfplumber
pdf = pdfplumber.open("examples/pdfs/ag-energy-round-up-2017-02-24.pdf")
page = pdf.pages[0]
page.dedupe_chars()
```

## PDF file

https://github.com/jsvine/pdfplumber/blob/stable/examples/pdfs/ag-energy-round-up-2017-02-24.pdf

## Expected behavior

No error.

## Actual behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/samkitjain/Samkit/Projects/Python/pdfplumber/pdfplumber/page.py", line 273, in dedupe_chars
    p._objects = dict((kind, objs) for kind, objs in self._objects.items())
AttributeError: 'Page' object has no attribute '_objects'
```

## Environment

- pdfplumber version: `develop` branch
- Python version: 3.8.2
- OS: Ubuntu 18.04

**Comment by sarraAyed** [comment]
Hello, I am still facing this issue.

**Comment by jsvine** [comment]
Hi @sarraAyed, and thanks for your note. Can you provide the code and PDF that reproduces the error you're encountering?
