### ISSUE TITLE
Reading order of multi-column document.

### ISSUE THREAD

**Issue by lvbohui** [jsvine/pdfplumber#296]
Hello, I have a question.
I want to know how this library controls the reading order of **multi-column** documents when reading chars.
For example, for a two-column document, when getting chars, it will read the second column until the end of the first column, instead of reading the first row of the second column after reading the first row of the first column.

**Comment by samkit-jain** [comment]
Hi @lvbohui Appreciate your interest. Assuming a 2-column page like

| Line 1 <br/> Column 1 | Line 1 <br/> Column 2 |
| --- | --- |

The library will read it as 
```
Line 1 Line 2
Column 1 Column 2
```

Goes top to bottom, left to right.

**Comment by lvbohui** [comment]
Hi @samkit-jain . 
Thank you very much for your answer, I know this, maybe I didn’t describe it clearly enough,
What I want to know is how this library achieves this. If it can't be described  in a  word, could you tell me which code file I should look at?
Thanks again for your answer

**Comment by jsvine** [comment]
Hi. This library is built upon `pdfminer.six`, and parses characters in the same order that `pdfminer.six` parses them, which I believe is the order in which they encoded (in the raw directives, not necessarily how they are displayed) in the PDF itself. This is the order the characters will appear when you access them directly, e.g., via `Page.chars`. By default, however, `pdfplumber`‘s `Page.extract_words()` method “reads” the characters from left to right and top to bottom — regardless of their order in which `pdfminer.six` processed them. But you can pass `use_text_flow=True` to extract the words in the original processing order. Does this answer your question?

**Comment by lvbohui** [comment]
Hi, @jsvine .Thanks for your answer. But I'm not very clear. 
What I want to know is how this library can read from top to the bottom of the first column **before** reading the second column. Is it achieved through the **encoding** or **metadata** of the PDF file itself? Is `pdfminer.six` used?

**Comment by samkit-jain** [comment]
hI @lvbohui Unfortunately, I am not sure if I understand your question. By "how", do you mean the code that is responsible for this? If yes, have a look at https://github.com/jsvine/pdfplumber/blob/954dc94563e6f94f5a118788e97f17d0844a9aab/pdfplumber/utils.py#L349 or https://github.com/jsvine/pdfplumber/blob/954dc94563e6f94f5a118788e97f17d0844a9aab/pdfplumber/utils.py#L328. If not, could you please elaborate by taking the page 2 of [this PDF](https://github.com/jsvine/pdfplumber/blob/stable/tests/pdfs/federal-register-2020-17221.pdf) as an example?

**Comment by lvbohui** [comment]
Hi @samkit-jain  . Yes, that's what I need. Appreciate you very much.
