### ISSUE TITLE
ValueError: Cannot convert None to Decimal.

### ISSUE THREAD

**Issue by wellsangels** [jsvine/pdfplumber#30]
I'm having the same problem that [this previous thread](https://github.com/jsvine/pdfplumber/issues/27) documented (not resolved there.) I'm running the following code, but get the same error with different pdfs.

`pdf = pdfplumber.open("ca-warn-report.pdf")
print(pdf.pages[0].extract_table())`

I'm on a Mac running OS 10.11.6 and Python 3.6.

Any help would be appreciated!

**Comment by jsvine** [comment]
Thanks for flagging, @wellsangels! Looks like `pdfminer.six` pushed a new version that creates some unexpected effects. I'll look into it. In the meantime, I've pushed a hotfix to `pdfplumber` — now available in `v0.5.4` — that pins `pdfminer.six`'s version. That seems to resolve the problem. 

To fix on your end, run `pip install pdfplumber --upgrade`. That should work. Let me know if it doesn't.

**Comment by wellsangels** [comment]
Perfect. Thanks!

**Comment by frascuchon** [comment]
I have the same error extracting tables with version `pdfplumber==0.5.21`.  Last working version is `0.5.16`

**Comment by lbolunya** [comment]
Thank you and bump to frascuchon's comment. Had to decrement version to get around this error.
