### ISSUE TITLE
How to extract text and tables from pdf pages and delete duplicate text of tables from the result text?

### ISSUE THREAD

**Issue by cjmqwerty** [jsvine/pdfplumber#300]
## What are you trying to do?

I need to extract both text and tables from pdf pages. And the tables' content should not exist in the text part.

## What code are you using to do it?

page.extract_text()
page.extract_tables()

## Expected behavior

For example, if a pdf page is like:

line1
line2
line3
table_a
line4
table_b
line5
line6

I want a result like:
[text, table_a, text, table_b, text]

## Actual behavior

I can only get the whole text by using extract_text(), but I dont want the table part.

**Comment by samkit-jain** [comment]
Hi @cjmqwerty Appreciate your interest in the library. This issue looks like a duplicate of https://github.com/jsvine/pdfplumber/issues/242 and https://github.com/jsvine/pdfplumber/issues/276 Could you please check and confirm?

**Comment by cjmqwerty** [comment]
Hi @samkit-jain Yes, they are same issues. And the solution works well. Thank you for your help!
