### ISSUE TITLE
pip install UnicodeDecodeError

### ISSUE THREAD

**Issue by ShaneKao** [jsvine/pdfplumber#304]
## Describe the bug

I got the following error message when installing. 

`
    ERROR: Command errored out with exit status 1:
     command: 'd:\pyvm\ailabuap0.2-dev\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-l2zwa6vd\\pdfplumber\\setup.py'"'"';
 __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-l2zwa6vd\\pdfplumber\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"
');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-xa95nanc'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-l2zwa6vd\pdfplumber\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-l2zwa6vd\pdfplumber\setup.py", line 19, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 4981: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

## Code to reproduce the problem

pip install pdfplumber==0.5.24

## Environment

- pdfplumber version: 0.5.24
- Python version: 3.7.5
- OS: Windows

**Comment by jsvine** [comment]
Seems like you may not have UTF-8 set as your default encoding. Does it work if you run it like this?:

```sh
LANG=en_US.UTF-8 pip install pdfplumber==0.5.24
```

**Comment by jsvine** [comment]
Now fixed in `develop`.

**Comment by jsvine** [comment]
Now available in v0.5.25.
