### ISSUE TITLE
An error was reported when using the "to_image" method.

### ISSUE THREAD

**Issue by lvbohui** [jsvine/pdfplumber#305]
## Describe the bug

An error was reported when using the "to_image" method on the pages of the following two documents

## Code to reproduce the problem
```
import pdfplumber
import numpy as np

with pdfplumber.open("documents/user1.pdf") as f:
    page0 = f.pages[0]
    img0 = page0.to_image(resolution=256)
    img0.save("1.png", format="png")
with pdfplumber.open("documents/user2.pdf") as f:
    page1 = f.pages[0]
    img1 = page1.to_image(resolution=256)
    img1.save("2.png", format="png")
```

## PDF file

[user1.pdf](https://github.com/jsvine/pdfplumber/files/5479189/user1.pdf)
[user2.pdf](https://github.com/jsvine/pdfplumber/files/5479190/user2.pdf)

## Expected behavior

In fact, the result is the same as expected, but an error will be reported at runtime

## Actual behavior

Lots of Errors like these:
```
   **** Error: Invalid (0 scaling) text matrix for Tm ****
               Output may be incorrect.
   **** Error: Invalid (0 scaling) text matrix for Tm ****
               Output may be incorrect.
   **** Error: Invalid (0 scaling) text matrix for Tm ****
               Output may be incorrect.
   **** Error: Invalid (0 scaling) text matrix for Tm ****
               Output may be incorrect.
```

## Screenshots

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/31612613/97947347-ffaa9980-1dc7-11eb-882a-87a1c5fcacda.png)

## Environment

- pdfplumber version:  0.5.22
- Python version: 3.6.8
- OS: Ubuntu 18.04

## Additional context

Put the two PDF files into **documents/** and run that code.

Look forward to your reply.

**Comment by samkit-jain** [comment]
Hi @lvbohui Appreciate your interest in the library. This output is coming from the `user2.pdf` file. I am not sure on the cause but I was able to get rid of them by repairing the PDF. You can repair the PDF using ghostscript by running the command `gs -o user2-repaired.pdf -sDEVICE=pdfwrite user2.pdf`.
`

**Comment by jsvine** [comment]
Thanks @samkit-jain, and I agree: This appears to be an error output by ImageMagick/Wand (which pdfplumber uses for image conversion), stemming from a PDF that needs repairing.
