### ISSUE TITLE
using extract_text() still have the blank,while using .chars lose all the blanks

### ISSUE THREAD

**Issue by BriskyGates** [jsvine/pdfplumber#306]
something wrong happened in the pdf as follows

[otl20110003-海运托书.pdf](https://github.com/jsvine/pdfplumber/files/5479989/otl20110003-.pdf)

**Comment by jsvine** [comment]
Per the issue templates, please share code that clearly demonstrates the problem, as well as a more complete description. It is very hard to help you without this information.

**Comment by jsvine** [comment]
Closing this issue due to lack of detail, but feel free to reopen with the requested information.
