### ISSUE TITLE
Option to allow tables which contain only one single cell

### ISSUE THREAD

**Issue by Pique7** [jsvine/pdfplumber#309]
I realized, that `pdfplumber.Page.extract_tables()` filters out tables which contain only one single cell. I have personally adapted `table.py` in order to include also tables with only one cell (or rather a framed text box than a table).  
Is it possible to include a configurable option (`allow_one_cell_table -> yes/no` or `minimum_cells_per_table -> 1..99`) in a future release?

**Comment by samkit-jain** [comment]
Hi @Pique7 Appreciate your interest in the library. Could you please share a PDF that can demonstrate this? Please don't forget to redact any sensitive information from the PDF. Would also be interested in knowing what changes you made in the `table.py` file.

**Comment by samkit-jain** [comment]
Also, per https://github.com/jsvine/pdfplumber/blob/eb73b06f404c1ae2c9a7ced4f1a7670afa32aa48/pdfplumber/table.py#L316 a valid table is considered to be the one that has at least 2 cells. There's already an open issue for users to allow specifying the minimum cell count. See https://github.com/jsvine/pdfplumber/issues/236. I am closing this issue for now and request you to continue the conversation in issue https://github.com/jsvine/pdfplumber/issues/236
