### ISSUE TITLE
Does "page.to_image()" can be converted to numpy array or binary stream?

### ISSUE THREAD

**Issue by lvbohui** [jsvine/pdfplumber#310]
Such as:
```
with pdfplumber.open("file.pdf") as f:
    page = f.pages[0]
    image = page.to_image()
```
and I want to the `image` can be the format of numpy array or in binary format. Is there any way to converted?
Shall I change the `display.py`?

By the way, I don't want to save it as `temp.png` and read it again.
Thanks.

**Comment by jsvine** [comment]
`PageImage` objects are a thin wrapper around [PIL `Image`](https://pillow.readthedocs.io/en/5.1.x/reference/Image.html) objects. `PageImage.original` provides access to that the PIL image object, while `PageImage.annotated` provides a version of the image that contains whatever you may have added to it via `PageImage.draw_rects(...)`, et cetera. Using either of those, you can get the byte representation via the PIL `Image`'s  [`.tobytes(...)`](https://pillow.readthedocs.io/en/5.1.x/reference/Image.html#PIL.Image.Image.tobytes). For instance, using your example:

```python
with pdfplumber.open("file.pdf") as f:
    page = f.pages[0]
    image = page.to_image()
    b = image.original.tobytes()
```

**Comment by lvbohui** [comment]
Appreciate for your answer, but is this byte format different with the file read byes? Like this:
```
with open("file", "rb") as f:
    image_bin = f.read()
``` 
Because I try to use the byte you said to converted to the format of opencv, it doesn't work  but when I use the `image_bin` above to convert, it works.

**Comment by jsvine** [comment]
I'd recommend reading the [documentation for PIL's Image class](https://pillow.readthedocs.io/en/5.1.x/reference/Image.html). This part may be relevant, depending on what exactly you're trying to do:

<img width="725" alt="Screen Shot 2020-11-09 at 10 48 17 PM" src="https://user-images.githubusercontent.com/534702/98625508-b681aa80-22dd-11eb-8176-5cda95c33da8.png">

**Comment by lvbohui** [comment]
Thanks, I will read it.
