### ISSUE TITLE
unexpected/non-exist vertical/horizontal lines generated in tables which cause extract table result wrong

### ISSUE THREAD

**Issue by guo1017138** [jsvine/pdfplumber#311]
## Describe the bug

*A clear and concise description of what the bug is.*
I have a lot of tables need to process in my pdfs but some of them always crashed after extract. After debug, I found some non-existed lines/edges get identified. This cause table has wrong size.
My original table in pdf like this: You can download the attached pdf PDF file section.
![image](https://user-images.githubusercontent.com/24711429/98945759-ea530f00-252d-11eb-9487-bceb3e9a5708.png)

Here is the graphic debug result, There are many lines don't exist.
![image](https://user-images.githubusercontent.com/24711429/98946085-6188a300-252e-11eb-961d-e658d09603aa.png)

## Code to reproduce the problem

*Paste it here, or attach a Python file.*
```python
import pdfplumber
pdf = pdfplumber.open("../pdfs/251.pdf")
p0 = pdf.pages[0]
im1 = p0.to_image()
im1
im1.debug_tablefinder()
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*
[251.pdf](https://github.com/jsvine/pdfplumber/files/5530807/251.pdf)

## Expected behavior

*What did you expect the result __should__ have been?*
Table 1 in attached pdf shall have correct rows and columns
Table 2 shall have correct columns(2)

## Actual behavior

*What actually happened, instead?*
Table 1 in attached pdf has extra rows and columns
Table 2 has many column with None value

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by samkit-jain** [comment]
Hi @guo1017138, appreciate your interest in the library. You can use the following code to filter out those invisible lines.
```python
import pdfplumber

def keep_visible_lines(obj):
    if obj['object_type'] == 'rect':
        return obj['non_stroking_color'] == 0
    return True

pdf = pdfplumber.open('../pdfs/251.pdf')
p0 = pdf.pages[0]
p0 = p0.filter(keep_visible_lines)

im1 = p0.to_image()
im1.debug_tablefinder()
```

The result I get after running debug table finder is as below.
![image](https://user-images.githubusercontent.com/15127115/99108684-ba7b3880-260d-11eb-98f2-c48babd1a453.png)

**Comment by guo1017138** [comment]
@samkit-jain . Nice!!! Thank you in advance!

**Comment by jfuruness** [comment]
Wow, this just saved me. It might be nice to have this as one of the examples, this was very hard to find. Or maybe update the description to include tags such as "non visible", "invisible". Thank you so much for this fix!

**Comment by jsvine** [comment]
Thanks for noting that @jfuruness, and good idea! Thinking more broadly, I think it's worth adding some documentation on common table-extraction challenges, and have created a new issue (see auto-added reference directly above) to address that.

**Comment by jfuruness** [comment]
Agreed, thank you! Also, maybe it is just for my specific answer, but I have a hunch that the inner workings changed a little bit to have the non_stroking_color be a list. For me, I had to use the following function:

```python
def keep_visible_lines(obj):
    if obj['object_type'] == 'rect':
        return obj['non_stroking_color'] == [1]
    return True
```

**Comment by jsvine** [comment]
@jfuruness I believe that the particular representation of `non_stroking_color` depends on the color specification the PDF itself used, as parsed by `pdfminer.six`. As a result, the particular solution will likely differ from PDF to PDF, but hopefully we can provide general guidance that points people in a helpful direction for whatever PDF they happen to be examining.

**Comment by jfuruness** [comment]
Ah, understood, that makes sense. Definitely, the original fix was quite helpful in pointing me in the right direction :)

**Comment by KingDracula** [comment]
![image](https://github.com/user-attachments/assets/f3cb0029-5fac-454e-a211-8f0e67eac88a)
i try to use these code ,but try error is dont have "object_type" property
