### ISSUE TITLE
File-object given to PDF() and open() should not be closed

### ISSUE THREAD

**Issue by the-vindicar** [jsvine/pdfplumber#312]
## Describe the bug

PDF class instance constructed with a file-like object closes that object upon deletion. `open()` does the same.
This behaviour is not documented, and is unexpected.

## Code to reproduce the problem

```python
import pdfplumber
with open('sample.pdf', 'rb') as src:
    with pdfplumber.PDF(src) as pdf:
        pass
    assert not src.closed, 'why is the file closed?'
```

## PDF file

Any valid pdf file will do.

## Actual behavior

File object given to PDF constructor is closed when `close()` method is called. See: https://github.com/jsvine/pdfplumber/blob/954dc94563e6f94f5a118788e97f17d0844a9aab/pdfplumber/pdf.py#L72
This disrupts using PDF class on temporary files and `BytesIO` objects, as those are destroyed upon being closed.

## Expected behavior

File object given to `PDF()` constructor should remain in open state upon closing the resulting PDF class instance.
PDF class instance should only close those file objects it opened by itself.

## Environment

- pdfplumber version: 0.5.24
- Python version: 3.8.2
- OS: Windows 10

**Comment by jsvine** [comment]
Hi @the-vindicar, and thanks for flagging this! Good catch. Now fixed in `develop`, and a relevant `assert` added to the tests
