### ISSUE TITLE
Extract text without tables

### ISSUE THREAD

**Issue by Spiritus44** [jsvine/pdfplumber#314]
Hello,

First thank you for this great library, it really help me to quick process pdf files.

I'm working on a PDF summarizer and I use pdfplumber to export all the text of the PDF. Unfortunately, I have documents which contains tables and (to make the summary process easier) I want to just export the text without the tables cells.

According to you   what is the best manner to do that ?

Thanks a lot for answer me,

**Comment by samkit-jain** [comment]
Hi @Spiritus44 Appreciate your interest in the library. Please have a look at issue #242 to extract text excluding tables.
