### ISSUE TITLE
how to extrat table in the picture

### ISSUE THREAD

**Issue by a417886** [jsvine/pdfplumber#323]
how to extrat table in the picture,I want to use my bbox

**Comment by samkit-jain** [comment]
Hi @a417886 Appreciate your interest in the library. I don't see any attached image. Request you to kindly edit your message with more details and a PDF.

**Comment by a417886** [comment]
I have used the OCR engine to get the texts and bbox of my table(picture,not pdf),I want to recognize the table strcture.I'm not sure whether pdfplumber can be done.

**Comment by samkit-jain** [comment]
pdfplumber does not work on scanned PDFs. If you are able to get the coordinates of every character as well from your OCR engine, you can perhaps try the following:
1. Add a text layer on top of the scanned PDF based on the coordinates provided by OCR.
2. Crop the PDF per the bounding box of the table given by OCR.
3. Run table extraction using pdfplumber using the "text" strategy.
    ```
    {
        "horizontal_strategy": "text",
        "vertical_strategy": "text"
    }
    ```
