### ISSUE TITLE
Merged two rows in one

### ISSUE THREAD

**Issue by IlyaTroshchynskyi** [jsvine/pdfplumber#328]
## What are you trying to do?

* A clear and concise description of your goals. *
Good evening. Please tell me why two adjacent rows in the table are merged into one

## What code are you using for this?

* Paste it here or attach a Python file. *

I use such settings for the table
            "vertical_strategy": "lines",
            "horizontal_strategy": "lines"
## PDF file

* Attach the PDF files used in the code. *

* If you need to edit the text in a confidential PDF, you can run it via [JoshData / pdf-redactor] (https://github.com/JoshData/pdf-redactor). *

## Expected behavior

* What do you expect __should__ result? *
Should be like other lines without concatenating adjacent lines

## Actual behavior

* What really happened? *

## Screenshots

* If possible, please add screenshots to explain your problem. *
![image](https://user-images.githubusercontent.com/40124417/103174727-1ec82380-486d-11eb-9659-515aabaf27c7.png)

![image](https://user-images.githubusercontent.com/40124417/103174759-4e772b80-486d-11eb-8ebe-fda952ce6cdf.png)

![image](https://user-images.githubusercontent.com/40124417/103174765-5cc54780-486d-11eb-8d11-36960dd5410c.png)

## Environment

- pdfplumber version: [eg 0.5.24]
- Python version: [eg 3.8.2]
- OS: [Windows 7]

## Additional context

* Add any other context / notes about the issue here. *

**Comment by samkit-jain** [comment]
Hi @IliaTroschiskiy Appreciate your interest in the library. Could you please provide a PDF that demonstrates this issue?

**Comment by IlyaTroshchynskyi** [comment]
> Hi @samkit-jain. Thank you for your answear. It's table on pages 146-149. It's like example. Because I have issues on other pages also.
[fry_14.pdf](https://github.com/jsvine/pdfplumber/files/5746316/fry_14.pdf)

**Comment by samkit-jain** [comment]
Thanks for sharing the PDF @IliaTroschiskiy I ran the `.debug_tablefinder(table_settings)` method on page 147 and this is the result I got
![image](https://user-images.githubusercontent.com/15127115/103202793-5ee4e000-4919-11eb-8ee9-80aeb094d91e.png)
which looks correct but the text like you mentioned was not extracted as expected. To figure out why, I ran `.draw_rects(page.chars)` and it gave the following result
![image](https://user-images.githubusercontent.com/15127115/103202894-b1260100-4919-11eb-9c40-959205ef6e14.png)

You'll notice that the bounding boxes for the characters are not positioned correctly which is causing troubles with the table extraction. Is this something that can be handled in the pdfplumber library? I don't know. I'll have to check. Might take some time as I am preoccupied with some stuff at the moment.

As a workaround, you can repair the PDF using GhostScript like `gs -o output.pdf -sDEVICE=pdfwrite input.pdf`. Running on this PDF, the results I got were correct as can be seen from the following screenshots
![image](https://user-images.githubusercontent.com/15127115/103203239-80929700-491a-11eb-8a8d-b1b51a0d29bc.png)
![image](https://user-images.githubusercontent.com/15127115/103203287-92743a00-491a-11eb-930f-87634386cc46.png)
```
['', 'Line', '', 'Line Item Name', 'MDRM \n(CCAM)', 'Detailed Description', 'Allowed Values', 'Format, Line \nItem Length']
[None, 'Item', None, None, None, None, None, None]
[None, 'No.', None, None, None, None, None, None]
['3', None, None, 'Property City', '9130', 'Report the city in which the property is located. \nContributors should be careful to provide the property \ncity (not the mailing city of the borrower).', 'Text line item', 'Text(50)']
['4', None, None, 'Property State', '9200', 'Report the state in which the property is located. \nContributors should be careful to provide the property \nstate (not the mailing state of the borrower), as the two \nmay differ for non-owner occupied properties and \nsecond/vacation homes.', 'Two-letter postal \ncodes for the state.', 'Character(2)']
['5', None, None, 'Property ZIP \nCode', '9220', 'Report the nine-digit ZIP code of the property or five-digit \nZIP code if nine-digit is not available. Please be sure to \nprovide the property ZIP code (not the mailing ZIP \ncode). \n \nNote: Provide the zip code as 9 digits when available.', 'Five-digit or nine-\ndigit number. \nInclude leading \nzeroes WITH \nNO DASHES, \ne.g., 00901, \n101015271', 'Character(9)']
['6', None, None, 'Mailing Street \nAddress', '9110', 'Report the borrower’s mailing street address. May be the \nsame as the Property Street Address.  Must include \nstreet prefixes, suffixes, and unit number for condos \nand co-ops.', 'Text line item. \nInclude street \nprefixes, suffixes, \nand unit number, \ne.g., 123 E Main St \nApt 123, 123 \nHighway 79 South \nUnit 567', 'Text(100)']
['7', None, None, 'Mailing City', 'F206', 'Report the borrower’s mailing city. May be the same as \nthe Property City.', 'Text line item.', 'Text(50)']
['8', None, None, 'Mailing State', 'F207', 'Report the borrower’s mailing state.  May be the same as \nthe Property State. \n \nIf the Mailing State is an international address, then use \na code value of "FF" to represent the Mailing State \ninformation.', 'Two-letter postal \ncodes for the state.', 'Character(2)']
['MDRM']
['(CCAM)']
['Format, Line']
['Item Length']
```
If you don't want the hidden lines from the header that are causing the `None`s to appear, you can filter out them by following https://github.com/jsvine/pdfplumber/issues/311#issuecomment-726958591

The repaired PDF is [here](https://github.com/jsvine/pdfplumber/files/5746570/tttt.pdf).

**Comment by IlyaTroshchynskyi** [comment]
Hi @samkit-jain. Thank you for advice and your attention to my problem. I would like to know how we can resolve this problem with pdfplumber. I will wait your answear. Also I downloaded the ghostscript but I have such problem. Can you look through and give some advice.
![image](https://user-images.githubusercontent.com/40124417/103245209-186aa200-4968-11eb-9614-9b7d9d05f1e1.png)

**Comment by samkit-jain** [comment]
I am not a Windows user and neither does have access to one. Maybe you can try the solution provided on this similar StackOverflow question: https://stackoverflow.com/questions/9296631/keep-getting-error-messages-in-ghostscript-when-using-the-documented-ghostscript?

**Comment by IlyaTroshchynskyi** [comment]
Thank you. But how is about solution with help pdfplumber?

**Comment by samkit-jain** [comment]
I'll start work on it in some time. Can't promise a timeline.

**Comment by IlyaTroshchynskyi** [comment]
Okey. I will wait your answear as long as necessary

**Comment by jsvine** [comment]
Many thanks for looking into this, @samkit-jain! Given that @IliaTroschiskiy's problem seems to stem from a buggy PDF, and that the problem disappears once the PDF is fixed with Ghostscript, I am closing this issue. Feel free, however, to continue the discussion.

**Comment by IlyaTroshchynskyi** [comment]
Can you help me with Ghostscript? I have run this comand but I don't see any results. Maybe I did something wrong
gswin64c -o -sDEVICE=pdfwrite -sOutputFile=new.pdf fry_14.pdf

**Comment by samkit-jain** [comment]
@IliaTroschiskiy Try `gswin64c  -o new.pdf -sDEVICE=pdfwrite fry_14.pdf`

**Comment by IlyaTroshchynskyi** [comment]
Thank you. But I have such result with comand gswin64c -o -sDEVICE=pdfwrite -sOutputFile=new.pdf fry_14.pdf
![image](https://user-images.githubusercontent.com/40124417/103354149-6f30c280-4ab3-11eb-9716-31e25bee3d27.png)
When I used this comand gswin64c -o -sDEVICE=pdfwrite -sOutputFile=new.pdf fry_14.pdf
i have such result 
![image](https://user-images.githubusercontent.com/40124417/103354215-a7d09c00-4ab3-11eb-9922-7b53e3c77948.png)
It looks like work but I don't see the pdf file with new result.

**Comment by samkit-jain** [comment]
`-o` and `-sOutputFile` perform the same function. Perhaps, try running `gswin64c -sDEVICE=pdfwrite -sOutputFile=new.pdf fry_14.pdf` instead? I removed the `-o`

**Comment by IlyaTroshchynskyi** [comment]
![image](https://user-images.githubusercontent.com/40124417/103363857-ddca4c00-4ac4-11eb-8b45-07cc0d757b3c.png)
Now I have such result. I can't understand why it trys open new file instead the fry_14.pdf

**Comment by samkit-jain** [comment]
Does https://stackoverflow.com/a/32357364/7760998 solve the issue?
>it doesn't work with PowerShell, whereas it works with cmd.exe

**Comment by IlyaTroshchynskyi** [comment]
![image](https://user-images.githubusercontent.com/40124417/103383414-4fbd8800-4afb-11eb-9df2-a97540b06beb.png)
I run this comand gswin64c -o -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH -sOutputFile=test.pdf fry_14.pdf
I have result like on screen. I think it working program but it dosn't create new file
