### ISSUE TITLE
I can't extract mathematical expression texts.

### ISSUE THREAD

**Issue by ai-motive** [jsvine/pdfplumber#329]
I wanna extract mathematical expression texts in pdf.

**Attached pdf** : [8_11074_XnE0n_4_p.pdf](https://github.com/jsvine/pdfplumber/files/5756741/8_11074_XnE0n_4_p.pdf)

**preview image ex)**

![스크린샷, 2020-12-31 16-46-42](https://user-images.githubusercontent.com/69468134/103400269-d0c26100-4b87-11eb-9f51-b5bf0c3d880d.png)

Looking at the second line, I want to get the following latex text output.

① -2^2 = 4
② (-1)^101 = -101
       ...
④ (-\frac{1}{2})^2 = -\frac{1}{4}

can I take some helps ?

**Comment by jsvine** [comment]
Hi @ai-motive, and thank you for your interest in this library. It does not currently provide any special support for mathematical expressions or LaTeX output. Closing this issue for now, but if someone in the community would like to try adding this support, feel free to discuss it here.
