### ISSUE TITLE
tables in a page getting wrong order

### ISSUE THREAD

**Issue by gqh1995** [jsvine/pdfplumber#336]
Hello,

First thank you for this great library, it really help me to quick process pdf files.

When i use **page.extract_tables** to extract tables in a same page, i get tables in a wrong order.

Why this problem occurs?

Thanks a lot for answer me

**Comment by samkit-jain** [comment]
Hi @gqh1995 Appreciate your interest in the library. Could you please provide the PDF and a reproducible Python code along with the expected and actual output?

**Comment by gqh1995** [comment]
@samkit-jain 
![image](https://user-images.githubusercontent.com/30197534/104863450-d8984880-5970-11eb-88ec-0d9dbca064a6.png)

> code:
```
with pdfplumber.open(path) as pdf:
    page = pdf.pages[-2]
    tables = page.extract_tables()
    for table in tables:
        print(table)
```


>expected  output:

[['公路技术\n等级', '车道数', '用地指标基准值', '编制条件', None], [None, None, None, '路段交通量Q（peu/d）', '大型车比例u（%）'], ['高速公路', '八', '2.5000', '60000≤Q＜80000', '20＜μ≤30'], [None, '六', '2.1333', '45000≤Q＜60000', '20＜μ≤30'], [None, '四', '1.6667', '25000≤Q＜40000', '20＜μ≤30'], ['一级公路', '六', '1.3333', '30000≤Q＜55000', '20＜μ≤30'], [None, '四', '0.6667', '15000≤Q＜30000', '20＜μ≤30'], ['二级公路', '二', '0.3333', 'Q＜15000', '20＜μ≤30']]
[['公路\n技术\n等级', '车道数', '路段交通量Q \n（pcu/d）', '大型车比例μ（%）', None, None, None, None], [None, None, None, 'μ≤10', '10＜\nμ≤20', '20＜\nμ≤30', '30＜\nμ≤40', 'μ＞40'], ['高速\n公路', '八', '80000≤Q＜100000', '0.92', '1.02', '1.11', '1.19', '1.26'], [None, None, '60000≤Q＜80000', '0.87', '0.93', '1.00', '1.06', '1.10'], [None, '六', '60000≤Q＜80000', '0.97', '1.04', '1.12', '1.19', '1.25'], [None, None, '45000≤Q＜60000', '0.82', '0.91', '1.00', '1.09', '1.16'], [None, '四', '40000≤Q＜55000', '1.01', '1.11', '1.20', '1.30', '1.39'], [None, None, '25000≤Q＜40000', '0.81', '0.92', '1.00', '1.08', '1.16'], ['一级\n公路', '六', '30000≤Q＜55000', '0.80', '0.90', '1.00', '1.05', '1.10'], [None, '四', '15000≤Q＜30000', '0.80', '0.90', '1.00', '1.10', '1.15'], ['二级\n公路', '二', 'Q＜15000', '1.00', '1.00', '1.00', '1.00', '1.00']]
[['路段监控通信分中心', '路段监控通信站', '桥隧监控通信站'], ['1.7333', '0.8667', '0.5333']]

> actual output:

[['公路技术\n等级', '车道数', '用地指标基准值', '编制条件', None], [None, None, None, '路段交通量Q（peu/d）', '大型车比例u（%）'], ['高速公路', '八', '2.5000', '60000≤Q＜80000', '20＜μ≤30'], [None, '六', '2.1333', '45000≤Q＜60000', '20＜μ≤30'], [None, '四', '1.6667', '25000≤Q＜40000', '20＜μ≤30'], ['一级公路', '六', '1.3333', '30000≤Q＜55000', '20＜μ≤30'], [None, '四', '0.6667', '15000≤Q＜30000', '20＜μ≤30'], ['二级公路', '二', '0.3333', 'Q＜15000', '20＜μ≤30']]
[['路段监控通信分中心', '路段监控通信站', '桥隧监控通信站'], ['1.7333', '0.8667', '0.5333']]
[['公路\n技术\n等级', '车道数', '路段交通量Q \n（pcu/d）', '大型车比例μ（%）', None, None, None, None], [None, None, None, 'μ≤10', '10＜\nμ≤20', '20＜\nμ≤30', '30＜\nμ≤40', 'μ＞40'], ['高速\n公路', '八', '80000≤Q＜100000', '0.92', '1.02', '1.11', '1.19', '1.26'], [None, None, '60000≤Q＜80000', '0.87', '0.93', '1.00', '1.06', '1.10'], [None, '六', '60000≤Q＜80000', '0.97', '1.04', '1.12', '1.19', '1.25'], [None, None, '45000≤Q＜60000', '0.82', '0.91', '1.00', '1.09', '1.16'], [None, '四', '40000≤Q＜55000', '1.01', '1.11', '1.20', '1.30', '1.39'], [None, None, '25000≤Q＜40000', '0.81', '0.92', '1.00', '1.08', '1.16'], ['一级\n公路', '六', '30000≤Q＜55000', '0.80', '0.90', '1.00', '1.05', '1.10'], [None, '四', '15000≤Q＜30000', '0.80', '0.90', '1.00', '1.10', '1.15'], ['二级\n公路', '二', 'Q＜15000', '1.00', '1.00', '1.00', '1.00', '1.00']]

**Comment by jsvine** [comment]
Hello, @gqh1995. Could you provide the *PDF file* rather than a screenshot of the PDF? Because `pdfplumber` operates only on PDFs and not image files, it will be difficult to debug your issue otherwise.

**Comment by gqh1995** [comment]
[test1.pdf](https://github.com/jsvine/pdfplumber/files/5833111/test1.pdf)
@jsvine

**Comment by samkit-jain** [comment]
Thanks for sharing the PDF @gqh1995 I have raised PR #338 that should resolve the issue.

**Comment by gqh1995** [comment]
@samkit-jain thanks a lot，the problem is solved.
