### ISSUE TITLE
Missing pdfminer layout related objects "textboxhorizontal" and "textlinehorizontal"

### ISSUE THREAD

**Issue by frascuchon** [jsvine/pdfplumber#359]
## Describe the bug

Hi. I'm not really sure if is a bug or an expected behaviour in newer versions, but the related pdfminer layout objects are missing under `page.objects` dict when passing `laparams` configuration.

## Code to reproduce the problem

```python
with pdfplumber.open(<path>, laparams= {}) as pdf:
  page = pdf.pages[0]
  assert "textboxhorizontal" in page.objects.keys() # This will fail
```

## Expected behavior

Like previous versions, passing the `laparams` configuration on pdf creation, will make available layout objects.

## Actual behavior

The custom objects "textboxhorizontal" and "textlinehorizontal", related to pdfminer layout analysis and given by default in previous versions (0.5.16 at least), are missing.

## Environment

- pdfplumber version: 0.5.26
- Python version: 3.7.6
- OS: Mac

## Additional context

I think the `else` condition in function `iter_layout_objects` discard all high-level objects that could contain textual info (horizontal textboxes and horizontal lines)

https://github.com/jsvine/pdfplumber/blob/002727803c09fdd739ae4bac9090c3801c097cac/pdfplumber/page.py#L199

**Comment by jsvine** [comment]
Hi @frascuchon, and thanks for your interest in this library. I'll look into this.

**Comment by jsvine** [comment]
Thanks again for opening the issues, @frascuchon. Those objects should be accessible again in the latest release, `0.5.27`.
