### ISSUE TITLE
`Page.to_image()` causes segmentation fault

### ISSUE THREAD

**Issue by xguse** [jsvine/pdfplumber#36]
I am able to run your example notebook fine. But when I try to use `to_image()` on this pdf (https://www.bdbiosciences.com/documents/cd_marker_handbook.pdf) I get a seg fault. 

Any idea what could be causing that?

**Comment by jsvine** [comment]
Hi, Gus, and thanks for filing this issue. Using `.to_image()` seems to work fine for me: https://gist.github.com/jsvine/28ac1f8ab94d5fc897e981d58f0dde8d

Did the seg fault message provide any extra context?

Perhaps it's an issue with your `PIL`/`Pillow` installation?

In any case, would be great to get to the bottom of this, in case other users encounter the same problem. Thanks again!

**Comment by xguse** [comment]
would you mind posting a `pip freeze` in the python environment that you used to test this in so that I can try to narrow down some culprits? I agree that it is probably in pillow or wand or something.

**Comment by jsvine** [comment]
Sure thing. I created a `--no-site-packages` virtual environment on Python 3.6, and ran `pip install pdfplumber`. Running `pip freeze` produces this output:

```sh
chardet==3.0.4
olefile==0.44
pdfminer.six==20151013
pdfplumber==0.5.5
Pillow==4.2.1
pycrypto==2.6.1
six==1.10.0
unicodecsv==0.14.1
Wand==0.4.4
```

**Comment by jwestwsj** [comment]
I know this is a closed issue, but I just wanted to post here in case someone else searches the same error that seems to be rearing its ugly head once again. I just had this very issue today with `ImageMagick@7` installed from Homebrew. I ended up downgrading to `ImageMagick@6` which solved the issue for me, but it appears that (as of three days ago) Wand [is suffering](https://github.com/emcconville/wand/issues/587) from an issue with its interactions with ImageMagick. I'd prefer not to have to downgrade ImageMagick, but it looks like Wand is on the case...

This is a great tool, thanks for maintaining/creating, y'all!
