### ISSUE TITLE
Error importing in ubuntu

### ISSUE THREAD

**Issue by ghost** [jsvine/pdfplumber#362]
Hello! When i´m trying importing in ubuntu, this error is displayed:

```
>>> import pdfplumber
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pdfplumber/__init__.py", line 10, in <module>
    from .pdf import PDF
  File "/usr/local/lib/python3.5/dist-packages/pdfplumber/pdf.py", line 49
    f'[WARNING] Metadata key "{k}" could not be parsed due to '
                                                              ^
SyntaxError: invalid syntax

```

**Comment by jsvine** [comment]
My best guess is that your environment (or virtual environment) is using Python 2, rather than Python 3.

**Comment by samkit-jain** [comment]
>  File "/usr/local/lib/python3.5/dist-packages/pdfplumber/pdf.py", line 49

@betances It seems like you are using Python 3.5. The support for Python 3.5 was dropped in [version 0.5.23](https://github.com/jsvine/pdfplumber/blob/stable/CHANGELOG.md#0523--2020-08-15). Request you to upgrade to Python 3.6 or higher if you want to use pdfplumber 0.5.23 or higher else downgrade to pdfplumber 0.5.22 or lower.

**Comment by jsvine** [comment]
Ah, good catch, @samkit-jain, and thanks for reading the traceback more carefully than I did! I concur.

**Comment by ghost** [comment]
> > File "/usr/local/lib/python3.5/dist-packages/pdfplumber/pdf.py", line 49
> 
> @betances It seems like you are using Python 3.5. The support for Python 3.5 was dropped in [version 0.5.23](https://github.com/jsvine/pdfplumber/blob/stable/CHANGELOG.md#0523--2020-08-15). Request you to upgrade to Python 3.6 or higher if you want to use pdfplumber 0.5.23 or higher else downgrade to pdfplumber 0.5.22 or lower.

Thanks! :)
