### ISSUE TITLE
Can we have exclude box in Page.Crop functionality

### ISSUE THREAD

**Issue by sreeni5493** [jsvine/pdfplumber#369]
To exclude a list of boxes based on bounding box locations.

Also can Page Crop have capabilities to include multiple bbox to crop multiple areas. For including it is fine since we can run a for loop and get text inside mulitple crop box. But for excluding, this technique wont work.

**Comment by jsvine** [comment]
Hi @sreeni5493, I agree: I think that could be a useful feature. Thanks for the suggestion. Adding it to my to-do list.

**Comment by jsvine** [comment]
You can now call `Page.outside_bbox(...)`: https://github.com/jsvine/pdfplumber/releases/tag/v0.7.4

If you have multiple bounding boxes you want to exclude, you can chain calls to `.outside_bbox(...)` or loop through them. E.g.,:

```python
page = pdf.pages[0]
bboxes = [ bbox_0, bbox_1, bbox_2 ]
for bbox in bboxes:
  page = page.outside_bbox(bbox)
```
