### ISSUE TITLE
Passing something other than list to `extract_text` results in error

### ISSUE THREAD

**Issue by alexreg** [jsvine/pdfplumber#386]
## Describe the bug

This exception is raised when calling `pdfplumber.utils.extract_text` and passing a `chars` object that is an iterator (with no `__len__` attribute).
```
TypeError: object of type 'generator' has no len()
```

## Code to reproduce the problem

```python3
pdfplumber.utils.extract_text(chars_iterator_obj)
```

## Expected behavior

No error; `chars_iterator_obj ` should get converted to list.

## Actual behavior

Error is raised.

## Environment

- pdfplumber version: 0.5.27
- Python version: 3.9.2
- OS: all

**Comment by jsvine** [comment]
I believe #385 fixes this and is merged, so closing this issue. Thanks @alexreg!
