### ISSUE TITLE
Add guidelines for submitting pull requests

### ISSUE THREAD

**Issue by jsvine** [jsvine/pdfplumber#387]
At the very least, should indicate:

- That PRs should be submitted against `develop`, not `stable`
- That PRs should contain tests
- How to write new tests
- How to run tests
- How to run linter and reformat code

Anything else I'm forgetting?

**Comment by alexreg** [comment]
This looks good to me as a new contributor.

**Comment by samkit-jain** [comment]
Suggestions:
* Adding oneself to the [list of contributors](https://github.com/jsvine/pdfplumber#acknowledgments--contributors)
* Update [CHANGELOG.md](https://github.com/jsvine/pdfplumber/blob/stable/CHANGELOG.md)

**Comment by jsvine** [comment]
Belatedly: Closed via #428.
