### ISSUE TITLE
Page 1 text extracted in Page 2 too

### ISSUE THREAD

**Issue by sreeni5493** [jsvine/pdfplumber#395]
[Buprenorphine.pdf](https://github.com/jsvine/pdfplumber/files/6181079/Buprenorphine.pdf)

```
import pdfplumber
pdf=pdfplumber.open('./Buprenorphine.pdf')
pages=pdf.pages
print(pages[0].extract_text())
print(pages[1].extract_text())
```

Hi,

With the following code, a lot of text from Page 1 are extracted in both Page 1 and Page 2. For example: "MEDICATION GUIDE". This text in capital is present in page 1 only. But pages[1].extract_text() is returning this and page[0].extract_text() also has this. But it is not there in page 2 at all. Similarly for "FULL PRESCRIBING INFORMATION" which is given as output in page 2 and page 1 , but it is present only in page 1.

**Comment by samkit-jain** [comment]
In the PDF, there are certain out of page objects. For example, the word `MEDICATION` has negative coordinates.
```python
{'text': 'MEDICATION', 'x0': Decimal('1006.437'), 'x1': Decimal('1056.577'), 'top': Decimal('-1435.744'), 'bottom': Decimal('-1425.744'), 'upright': True, 'direction': 1}
```

To filter out such objects, you may crop the page like
```python
page = page.crop((0, 0, page.width, page.height))
```

**Comment by sreeni5493** [comment]
Thanks.

This worked. Closing the issue.
