### ISSUE TITLE
How to extract objects in PDF？

### ISSUE THREAD

**Issue by situchen** [jsvine/pdfplumber#397]
Please describe, in as much detailHow to extract objects in PDF, for example, need to extract selected characters in the picture?
[text.pdf](https://github.com/jsvine/pdfplumber/files/6186204/text.pdf)

**Comment by jsvine** [comment]
Hello, and thank you for your interest in this library. Please read the documentation in this repository's [README.md file](https://github.com/jsvine/pdfplumber/blob/stable/README.md), which explains how to use the library. If you still have questions after that, please describe the specific problem or confusion.
