### ISSUE TITLE
PSKeyword' object has no attribute 'decode

### ISSUE THREAD

**Issue by HTransistor** [jsvine/pdfplumber#398]
## Describe the bug
Probably a bug after some refactoring or because of new python version.

## Code to reproduce the problem

```python
with pdfplumber.open(Path(dir_path, input_file)) as pdf:
    # get all pages
    plumber_text_full = ""
    for j in range(len(pdf.pages)):
        # one page at a time
        page = pdf.pages[j]
        plumber_text = page.extract_text()
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

Extracted text from file

## Actual behavior
```
Traceback (most recent call last):
  File "/home/dsche/Documents/upwork/pdf_scrape_chemical/scrape.py", line 232, in <module>
    plumber_text = page.extract_text()
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfplumber/page.py", line 260, in extract_text
    return utils.extract_text(self.chars, **kwargs)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfplumber/container.py", line 48, in chars
    return self.objects.get("char", [])
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfplumber/page.py", line 161, in objects
    self._objects = self.parse_objects()
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfplumber/page.py", line 222, in parse_objects
    for obj in self.iter_layout_objects(self.layout._objs):
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfplumber/page.py", line 110, in layout
    interpreter.process_page(self.page_obj)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 906, in render_contents
    self.init_resources(resources)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 354, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 202, in get_font
    font = self.get_font(None, subspec)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 193, in get_font
    font = PDFCIDFont(self, spec)
  File "/home/dsche/.local/lib/python3.9/site-packages/pdfminer/pdffont.py", line 672, in __init__
    cid_registry = resolve1(
AttributeError: 'PSKeyword' object has no attribute 'decode'
```

## Environment

- pdfplumber version: 0.5.27
- Python version: 3.89.2
- OS: Manjaro Linux

**Comment by jsvine** [comment]
Thanks for raising this issue. It's a bit hard to debug, however, without an example PDF. Are you able to provide one that helps to reproduce this error?

**Comment by HTransistor** [comment]
I got three different files causing this issue:

[epoxyshield-sealer-msds.pdf](https://github.com/jsvine/pdfplumber/files/6203104/epoxyshield-sealer-msds.pdf)
[febra-Silk-Teat-Wipes-QUAT-Free-MSDS.pdf](https://github.com/jsvine/pdfplumber/files/6203105/febra-Silk-Teat-Wipes-QUAT-Free-MSDS.pdf)
[file_msds_39.pdf](https://github.com/jsvine/pdfplumber/files/6203106/file_msds_39.pdf)

**Comment by jsvine** [comment]
Hi @HTransistor and thanks again. Here's what I've found after looking into this:

The error for `file_msds_39.pdf` is raised `pdfminer.six` (upon which `pdfplumber` is built). You can see this in the stacktrace you've pasted above, but also by running this test program:

```python
from pdfminer.high_level import extract_text
text = extract_text("path/to/file_msds_39.pdf")
```
... which throws the same error. But I don't think that `pdfminer.six` is the problem, since `file_msds_39.pdf` file appears to be malformed. For instance, running [`cpdf`](https://community.coherentpdf.com/) on the PDF (`cpdf file_msds_39.pdf`) produces this output:

```
Attempting to reconstruct the malformed pdf file_msds_39.pdf...
list length 0
list length 0
Recovering from Lex error: Pdf.PDFError("Could not extract object")
list length 0
Recovering from Lex error: Pdf.PDFError("Could not extract object")
list length 0
list length 0
Recovering from Lex error: Pdf.PDFError("Could not extract object")
list length 2
EndStream
endobj
list length 0
Read 21 objects
cpdf encountered an error. Technical details follow:

Failed to read PDF - initial error was
Pdf.PDFError("Could not read object whilst reading file file_msds_39.pdf at position 148533")

final error was
Pdf.PDFError("No /Root entry whilst reading file file_msds_39.pdf at position 332255")

 whilst reading file file_msds_39.pdf at position 332255
```

---

Separately: When running `epoxyshield-sealer-msds.pdf` and `febra-Silk-Teat-Wipes-QUAT-Free-MSDS.pdf` through your script, however, I encounter **no error** on `pdfplumber==0.5.27`, the same version you're using.

**Comment by samkit-jain** [comment]
Additionally, if you try repairing the PDF via Ghostscript, it works fine. Command to run
```
gs -o output.pdf -sDEVICE=pdfwrite input.pdf
```

Attaching the file here. I ran on `file_msds_39.pdf`.
[output.pdf](https://github.com/jsvine/pdfplumber/files/6204938/output.pdf)

**Comment by HTransistor** [comment]
@jsvine you are right, I just checked the other two files work, but `file_msds_39.pdf` not.
I just wonder why `file_msds_39.pdf` is malformed. The pdf by first glance looks okay...

@samkit-jain that works fine. Thanks!

**Comment by mkl-public** [comment]
@HTransistor 
>I just wonder why `file_msds_39.pdf` is malformed. The pdf by first glance looks okay...

Inspecting the PDF around 148533 from _Could not read object whilst reading file file_msds_39.pdf at position 148533_ one finds

```
14 0 obj
(Adobe)
endobj16 0 obj
 1015
endobj
```

As you see a line break is missing between `endobj` and `16 0 obj`. In my experience that is a seldom seen issue, I don't remember seeing such missing line breaks except between revisions, right after the `%%EOF` of the former revision..

The other message _No /Root entry whilst reading file file_msds_39.pdf at position 332255_, though, I do not understand.
