### ISSUE TITLE
Why pdfplumber is giving table as a list [while we extracting table from the pdf file]

### ISSUE THREAD

**Issue by bharath-kumarn** [jsvine/pdfplumber#399]
## Why pdfplumber is giving table as a list [while we extracting table from the pdf file]

*A clear and concise description of what the bug is.*
Why pdfplumber is giving table as a list instead of that you can return as a dataframe or as a table at it

>>> import pdfplumber
>>> file = "/home/bharath/reco/repo/thomson_test/pdf_files/53146896-pages-7.pdf"
>>> pdf = pdfplumber.open(file)
>>> pdf
<pdfplumber.pdf.PDF object at 0x7fc440449750>
>>> page = pdf.pages[0]
>>> page.extract_table()
[['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', ''], ['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', ''], ['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', ''], ['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', ''], ['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', ''], ['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', ''], ['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', ''], ['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', ''], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]]
>>> 
>>> page.extract_table()
[['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', ''], ['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', ''], ['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', ''], ['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', ''], ['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', ''], ['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', ''], ['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', ''], ['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', ''], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]]
>>> a=page.extract_table()
>>> a
[['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', ''], ['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', ''], ['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', ''], ['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', ''], ['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', ''], ['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', ''], ['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', ''], ['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', ''], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]]
>>> type(a)
<class 'list'>
>>> len(a)
13
>>> for i in a:
...     print(i)
...     print('next')
... 
['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', '']
next
['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', '']
next
['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', '']
next
['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', '']
next
['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', '']
next
['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', '']
next
['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', '']
next
['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', '']
next
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
next
['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
next
['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
next
['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
next
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
next
>>> 
>>> for i in a:
...     print('next')
...     print(i)
...     print(type(i))
... 
next
['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', '']
<class 'list'>
next
['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', '']
<class 'list'>
next
['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', '']
<class 'list'>
next
['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', '']
<class 'list'>
next
['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', '']
<class 'list'>
next
['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', '']
<class 'list'>
next
['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', '']
<class 'list'>
next
['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', '']
<class 'list'>
next
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
next
['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
next
['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
next
['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
next
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
>>> for i in a:
...     print('next')
...     print(i)
...     print(type(i))
...     print('lenfgth',len(i))
... 
next
['Mainland China', '', '', '292,812', '', '', '', '17,987', '', '', '', '303,789', '', '', '', '33,129', '', '', '', '192,604', '', '', '', '40,610', '']
<class 'list'>
lenfgth 25
next
['Americas/Pacific', '', '', '220,216', '', '', '', '7,607', '', '', '', '248,609', '', '', '', '8,354', '', '', '', '244,467', '', '', '', '8,871', '']
<class 'list'>
lenfgth 25
next
['South Korea', '', '', '168,972', '', '', '', '7,251', '', '', '', '182,026', '', '', '', '7,565', '', '', '', '172,553', '', '', '', '8,431', '']
<class 'list'>
lenfgth 25
next
['Southeast Asia', '', '', '136,349', '', '', '', '7,480', '', '', '', '153,465', '', '', '', '8,933', '', '', '', '121,764', '', '', '', '8,020', '']
<class 'list'>
lenfgth 25
next
['Japan', '', '', '125,557', '', '', '', '5,916', '', '', '', '130,181', '', '', '', '5,916', '', '', '', '132,041', '', '', '', '6,592', '']
<class 'list'>
lenfgth 25
next
['EMEA', '', '', '153,330', '', '', '', '4,619', '', '', '', '149,085', '', '', '', '4,791', '', '', '', '135,051', '', '', '', '4,683', '']
<class 'list'>
lenfgth 25
next
['Hong Kong/Taiwan', '', '', '65,669', '', '', '', '3,900', '', '', '', '76,891', '', '', '', '4,767', '', '', '', '71,091', '', '', '', '4,671', '']
<class 'list'>
lenfgth 25
next
['Total', '', '', '1,162,905', '', '', '', '54,760', '', '', '', '1,244,046', '', '', '', '73,455', '', '', '', '1,069,571', '', '', '', '81,878', '']
<class 'list'>
lenfgth 25
next
['', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
lenfgth 25
next
['(1) Our Velocity sales compensation program enhancements were designed to drive and reward increased productivity of our Sales Leaders, with adjusted requirements for\nqualifying and maintaining “Sales Leader” status, which has impacted the number of independent distributors under our global compensation program who achieve such\nrequirements. For example, the sales volume necessary to achieve initial qualification has been increased in some markets, financial rewards have been increased for\nhigher monthly sales productivity, and qualification requirements to maintain and advance status have been modified. The enhanced program also provides some\nflexibility to remain a Sales Leader with a lower sales volume for a short time. We began introducing Velocity in the fourth quarter of 2017 and continued rolling it out\nacross our markets through the first half of 2019. We have now introduced Velocity in all of our markets other than Mainland China, which operates under a different\nbusiness model and is not impacted by these changes.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
lenfgth 25
next
['Global Direct Selling Channel\nOutside of Mainland China, individuals can elect to participate in our business as follows:', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
lenfgth 25
next
['● “Distributor-Direct Consumers”—Individuals who purchase products directly from an independent distributor at a price established by the distributor.\n● “Company-Direct Consumers”—Individuals who purchase products directly from the company. These consumers are typically referred by a distributor and may\npurchase at retail price or at a discount. These individuals do not have the right to build a Nu Skin business by reselling product or by recruiting others.\n● “Basic Distributors”—Distributors who purchase products for personal or family use or for resale to other consumers. These individuals are not eligible to receive\ncompensation on a multi-level basis unless they elect to qualify as a Sales Leader under our global sales compensation plan. We consider these individuals to be part\nof our consumer group, as we believe a significant majority of these distributors are purchasing products for personal use and not actively recruiting others, and their\npurchasing levels are similar to our “Company-Direct Consumers.”\n● “Sales Leaders and Qualifiers”—Distributors who have qualified or are trying to qualify as a Sales Leader. These distributors have elected to pursue the business\nopportunity as a Sales Leader and are actively recruiting consumers and distributors and building a sales network under our global sales compensation plan and\nconstitute our sales network.', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
<class 'list'>
lenfgth 25
next

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
That output is a list of lists, with each of the inner lists representing a row in the table. If you'd like to convert this plain-Python representation into a Pandas DataFrame, you can use `df = pd.DataFrame(page.extract_table())`.
