### ISSUE TITLE
wapped string in a cell cannot be read correctly

### ISSUE THREAD

**Issue by aaronzhengwl** [jsvine/pdfplumber#408]
## Describe the bug

*A clear and concise description of what the bug is.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots
![image](https://user-images.githubusercontent.com/38651136/114038488-7e928980-98b4-11eb-8ba8-36cff8d2afa8.png)
![image](https://user-images.githubusercontent.com/38651136/114038614-99fd9480-98b4-11eb-848c-86b3a256370b.png)

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*
[](url)

**Comment by aaronzhengwl** [comment]
this is the pdf https://pdf.dfcfw.com/pdf/H2_AN202010291424595445_1.pdf?1604005808000.pdf
You can check its first table

**Comment by jsvine** [comment]
Hi @aaronzhengwl, and thanks for your interest in this library. So that we can efficiently examine your case and for the benefit of other people reading it, please complete the information requested in the issue template.

**Comment by jsvine** [comment]
Closing this issue due to lack of necessary information / code. Feel free reopen.
