### ISSUE TITLE
conflict with pdfmine3k in installing with pip3

### ISSUE THREAD

**Issue by aaronzhengwl** [jsvine/pdfplumber#409]
## Describe the bug

*A clear and concise description of what the bug is.*
It looks this tool needs packet pdfmine, if I have installed pdfmine3k which is named pdfmine in python lib.
Then pdfplumer cannot work. Vice Versa.

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots
![image](https://user-images.githubusercontent.com/38651136/114039619-7be46400-98b5-11eb-97a9-a9ad5d2ce0fb.png)

![image](https://user-images.githubusercontent.com/38651136/114040955-af73be00-98b6-11eb-8d76-28af5199ea31.png)

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
This tool does not use `pdfminer3k`, but rather `pdfminer.six`. Installing `pdfplumber` automatically installs a compatible verison of `pdfminer.six`. If you have already installed `pdfminer3k`, you will need to uninstall it. I recommend:

```sh
pip uninstall pdfminer3k
pip uninstall pdfminer.six
pip install pdfplumber
```
