### ISSUE TITLE
Decode text issue - (cid:49)(cid:52)(cid:56)(cid:44)(cid:56) instead of text

### ISSUE THREAD

**Issue by areqq** [jsvine/pdfplumber#424]
## Describe the bug

I have got (cid:87) instead od char.

## PDF file

[wfirma_Faktura_FV_1_2021.pdf](https://github.com/jsvine/pdfplumber/files/6377365/wfirma_Faktura_FV_1_2021.pdf)

## Screenshots

>  pdfplumber wfirma_Faktura_FV_1_2021.pdf 
object_type,page_number,x0,x1,y0,y1,doctop,top,bottom,width,height,adv,bits,colorspace,evenodd,fill,fontname,imagemask,linewidth,name,non_stroking_color,pts,size,srcsize,stream,stroke,stroking_color,text,upright
char,1,243.88,249.544,19.808,25.808,816.082,816.082,822.082,5.664,6.0,5.664,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:87),1
char,1,249.544,252.544,19.808,25.808,816.082,816.082,822.082,3.0,6.0,3.0,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:121),1
char,1,252.544,255.88,19.808,25.808,816.082,816.082,822.082,3.336,6.0,3.336,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:100),1
char,1,255.88,257.878,19.808,25.808,816.082,816.082,822.082,1.998,6.0,1.998,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:114),1
char,1,257.878,261.214,19.808,25.808,816.082,816.082,822.082,3.336,6.0,3.336,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:117),1
char,1,261.214,264.214,19.808,25.808,816.082,816.082,822.082,3.0,6.0,3.0,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:107),1
char,1,264.214,265.882,19.808,25.808,816.082,816.082,822.082,1.668,6.0,1.668,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:32),1
char,1,265.882,269.218,19.808,25.808,816.082,816.082,822.082,3.336,6.0,3.336,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:112),1
char,1,269.218,272.554,19.808,25.808,816.082,816.082,822.082,3.336,6.0,3.336,,,,,LiberationSans,,,,"(0.0, 0.0, 0.0)",,6.0,,,,0,(cid:111),1

## Environment

- pdfplumber version: 0.5.27
- Python version: 3.9.2
- OS: Mac

## Additional context
A  example of problematic pdf attached.

**Comment by jsvine** [comment]
Hi @areqq, text conversion is handled by [pdfminer.six](https://github.com/pdfminer/pdfminer.six). In that repo's issues, you can see similar issues raised by other people and how they have (or have not) been resolved: https://github.com/pdfminer/pdfminer.six/issues?q=is%3Aissue+%22cid%3A%22
