### ISSUE TITLE
 to_image function does not include symbols like "+","=" etc

### ISSUE THREAD

**Issue by safwanolaimat** [jsvine/pdfplumber#427]
## Describe the bug

*I have used this library to create images of pdf pages
the pdf pages contains equations

and the image produced didn't contains symbols*

## Environment

- pdfplumber version: pdfplumber==0.5.27
- Python version: Python 3.8.5
- OS: Linux

**Comment by AliHaider20** [comment]
Can you share the output?

**Comment by jsvine** [comment]
Closing this issue due to lack of example and details. Feel free to reopen with more information.
