### ISSUE TITLE
 Requested setting PDF_MINER_IS_STRICT

### ISSUE THREAD

**Issue by pku-wuwei** [jsvine/pdfplumber#46]
When I used the module in python 3.6, an error occured:
ImproperlyConfigured: Requested setting PDF_MINER_IS_STRICT, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by jsfenfen** [comment]
Hi @pku-wuwei, are you running this in a django context?  Can you say more about how and where this error occurs? 

Have to ask: have you tried setting the variable PDF_MINER_IS_STRICT to True or False in your settings.py file? Also, have you followed the error message's suggestion to " either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings"?

If you've done all that, could this be related, it looks like they changed the name that settings were imported with in pdfminer.six--from __django_settings__ to settings--is this relevant? Sorry if this is a lengthy red herring.
 
https://github.com/pdfminer/pdfminer.six/commit/6cc4abbaa81e188cb1d8484df1d5763913a395ba#diff-c87a640b063fa06cac57f7b9e921022a

Hmm, I wonder why they didn't [use](https://github.com/pdfminer/pdfminer.six/commit/6cc4abbaa81e188cb1d8484df1d5763913a395ba#diff-c87a640b063fa06cac57f7b9e921022aR4):
 
`from django.conf import settings as django_settings`

[Also, hmm](https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/settings.py) I guess there's some sorta django settings checking built in to *pdfminer.six* ? But it's letting that error pass there?

If the error is coming from your code, what if you try: 

`from django.conf import settings as django_settings`

and changing references to django_settings where used?

**Comment by dankeemahill** [comment]
I also got this error using pdfplumber with a jupyter notebook in a conda [environment](https://conda.io/docs/user-guide/tasks/manage-environments.html).

I wasn't using django, but `Django==1.9` was in my conda environment. (I probably should have used [`--no-default-packages`](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) when creating the env 😐 )

I ran `pip uninstall Django` because I didn't need django, and I stopped getting the `ImproperlyConfigured` error.

I used this same environment in December and wasn't getting the `ImproperlyConfigured` error until activating the environment again this week. I don't _thiiiink_ I made any changes to the environment between then and now, but I suppose it's possible I updated something.

@pku-wuwei are you using a conda environment?

**Comment by jsfenfen** [comment]
Hey @dankeemahill that's interesting... Do you have the full error that you could post somewhere? I'm still really interested in where this is coming from. It's interesting that pdfminer.six has a specific except clause to *[allow](https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/settings.py)* that setting to be missing (and a recent [commit](https://github.com/pdfminer/pdfminer.six/commit/6cc4abbaa81e188cb1d8484df1d5763913a395ba#diff-c87a640b063fa06cac57f7b9e921022a) changing the name). Do you know the version of pdfminer and pdfminer.six you're running?

Also, if you run `conda list` is Django there now? (I dunno much about conda; maybe also try `conda env export` ?)

**Comment by dankeemahill** [comment]
@jsfenfen I put all that output in a gist https://gist.github.com/dankeemahill/edcf3031068c0ad7d3d64516a047347d

`pip freeze` shows:

`pdfplumber==0.5.6`
`pdfminer.six==20151013`
`Django==1.9`

`conda list` and `conda env export` don't show pdfminer or pdfplumber, looks like those only return what the env had at the very beginning.

These were my steps to get this env in this state:

```
conda create --name pdf # note I didn't specify packages here, so I get all the defaults
source activate pdf
pip install pdfplumber
python -c "import pdfplumber"
```

**Comment by dankeemahill** [comment]
It also might be the case that at some point my conda env defaults differed from conda's factory defaults 🙈 

However it is still the case that I can uninstall Django in my conda env and have no errors

```
conda create --name pdf
source activate pdf
pip install pdfplumber
pip uninstall Django
python -c "import pdfplumber"
```
⬇️ 
no errors

Sorry, I don't mean to make this issue all about conda 😬

**Comment by jsfenfen** [comment]
Hey @dankeemahill and @pku-wuwei I was able to recreate this error using python 2.7 and version 20151013 of pdfminer.six. But upgrading to any current pdfminer.six [release](https://github.com/pdfminer/pdfminer.six/releases) fixed this on my rig.

You could probably fix this by reinstalling the current release of pdfminer, which pins pdfminer.six at 20170720, so something like:

`pip install pdfplumber==0.5.7`

If there's dependency issues you could also just upgrade pdfminer.six
`pip install pdfminer.six==20170720`
assuming that works within conda? Or just install to a release that's  >=20160614. 

Running the upgrade allowed this to work even if Django (1.11 b.c. python2) is installed on my setup, btw, though can't guarantee that'll hold true for anyone else.

FWIW, if you *absolutely can't upgrade* I noticed that the error also went away by downgrading to pdfminer.six 20140915 as well. As near as I can tell, it's only 20151013 that causes this problem.

**Comment by dankeemahill** [comment]
Yes @jsfenfen updating the pdfs fixed this error for me, even when Django was also present in the env
```
pdfminer.six==20170720
pdfplumber==0.5.7
Django==1.9
```
👍
