### ISSUE TITLE
i  find a bug when use dedupe_chars()

### ISSUE THREAD

**Issue by 2212168851** [jsvine/pdfplumber#461]
## Describe the bug

*A clear and concise description of what the bug is.*
this is my code:
#!/usr/bin/env python3
import pdfplumber
import base64
import re
from io import BytesIO

class PDF_Extract(object):
    def __init__(self, base64_data):
        self.base64_pdf = base64_data
        self.pdf_bytes = self.load()

    def load(self):
        content = re.sub(r'^data[^,]*?base64,', '', self.base64_pdf)
        #import ipdb;ipdb.set_trace()
        data = base64.b64decode(content)
        bytes_file = BytesIO()
        bytes_file.write(data)

        return bytes_file

    def words_extract(self):
        pdf_data = []
        pdf_obj = pdfplumber.open(self.pdf_bytes)
        for page in pdf_obj.pages:
            page_data = []
            import ipdb;ipdb.set_trace()
            words_list = page.dedupe_chars().extract_words()
            #https://github.com/jsvine/pdfplumber/issues/71
            for node in words_list:    
                item = [
                    float(node['x0']),
                    float(node['top']),
                    float(node['x1'] - node['x0']),
                    float(node['bottom'] - node['top']), node['text']
                ]
                page_data.append(item)
            pdf_data.append(page_data)
            page.close()
        return pdf_data

when i use pdf in attach，it trigger an error "TypeError: '<' not supported between instances of 'bytes' and 'str'"  at code "words_list = page.dedupe_chars().extract_words()"

please help me fix it
thank you very much

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs [necessary]([患者B.pdf](https://github.com/jsvine/pdfplumber/files/6754122/B.pdf)) to reproduce the problem.*
[
[患者B.pdf](https://github.com/jsvine/pdfplumber/files/6754126/B.pdf)
](url)
*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*
![9D90A4B9-1698-4103-B2B1-7EC84F951242](https://user-images.githubusercontent.com/36918188/124265461-48d60780-db68-11eb-9b80-a59614b33d95.png)

## Environment

- pdfplumber version: [e.g., 0.5.22]    0.5.28 
- Python version: [e.g., 3.8.1] python3
- OS: [e.g., Mac, Linux, etc.]  linux

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hi @2212168851 — thank you for your interest in `pdfplumber` and thank you for filing this issue. @samkit-jain and I have identified the problem, which revolves around one character in the PDF that uses a font whose `FontDescriptor`'s `FontName` is encoded in an unusual manner. You can read more about the diagnosis [here](https://github.com/jsvine/pdfplumber/pull/462#issuecomment-873410317). To resolve your problem, you can add these two lines at the beginning of your `for page` loop:

```python
for char in page.objects["char"]:
    char["fontname"] = str(char["fontname"])
```
