### ISSUE TITLE
pdfplumber relies on dead dependency pycrypto

### ISSUE THREAD

**Issue by paalped** [jsvine/pdfplumber#47]
Hi,
I am really interested in trying out this pdfplumber on my windows machine, but I can not install it with pip, cause it fails when trying to install dependency pycrypto. As from what I have found this project is dead, and should be switched to pycryptodome. 
Hope this will be fixed.

**Comment by jsvine** [comment]
Thank you for flagging. Should now be fixed, thanks to https://github.com/jsvine/pdfplumber/pull/48, and available in `v0.5.7`.
