### ISSUE TITLE
Vertical text in tables

### ISSUE THREAD

**Issue by cveaux** [jsvine/pdfplumber#50]
Hi, thanks for this project, it's very useful.  

One question, can pdfplumber deal with vertical text in headers or data cells?  pdfminer has an object LTTextLineVertical but I cannot see the equivalent in pdfplumber. This lead me to a second question, why did you get rid of the LTTextLine objects of pdfminer and just kept the characters objects?  I guess it's because the LTTextLine objects can span several cells? (pdfminer seems to lack word objects which would be the right level to use for table extraction).

Thanks.

**Comment by jsfenfen** [comment]
Hey @cveaux, are you able to extract the vertical text, and if not, do you think you could share the pdf file where it isn't working? 
FWIW, I think there's some explanation about LTTextLine in https://github.com/jsvine/pdfplumber/issues/1 (so agree that it's a relevant question!)

**Comment by cveaux** [comment]
Hi, I cannot share the pdf document unfortunately as it is covered by NDA. The extract_words() function managed to extract some vertical words but not all of them (some vertical words are split into their individual characters). I think it's just a question of parameters settings. I'll try to tweak them and go back later to you if it isn't working. Thanks!

**Comment by jsvine** [comment]
Hi @cveaux. Really interesting question. As @jsfenfen noted (thanks!), there's some explanation of this in #1. 

Speaking more generally, pdfplumber does not implement any of pdfminer's aggregated-character layout types, of which LTTextLine and LTTextLineVertical are examples. Those types aren't necessarily representative of the actual layout of the PDF, but instead the result of (clever and at times definitely useful) inference by pdfminer. 

That said, I think that extending `.extract_words()` to optionally look for vertical words would be a worthwhile feature for pdfplumber. I'll add it to my todo list.

**Comment by jsvine** [comment]
A belated update: [As of v0.5.17](https://github.com/jsvine/pdfplumber/blob/master/CHANGELOG.md#0517--2020-04-01), `.extract_words()` handles vertical text.
