### ISSUE TITLE
读取pdf出现：struct.error: unpack requires a bytes object of length 26 错误

### ISSUE THREAD

**Issue by xiaoranli1991** [jsvine/pdfplumber#505]
## Describe the bug

*A clear and concise description of what the bug is.*

## Code to reproduce the problem

*Paste it here, or attach a Python file.*

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*

## Actual behavior

*What actually happened, instead?*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by samkit-jain** [comment]
Hi @xiaoranli1991 Appreciate your interest in the library. Could you please update your issue comment to fill out the missing details?

**Comment by jsvine** [comment]
Judging by the type of error cited, this appears most likely to be an issue with either a corrupted PDF or with a bug in `pdfminer.six` (rather than `pdfplumber`). Closing the issue for now.
