### ISSUE TITLE
Flexibility x and y axis for snap tolerance.

### ISSUE THREAD

**Issue by dustindall** [jsvine/pdfplumber#52]
Hi @jsvine ,

I was working with a table where i needed to additional snap_tolerance flexibility on the y-axis relative to the x-axis. Therefore, I added a snap_x_tolerance and snap_y_tolerance parameters in the same fashion as text_tolerance and intersection_tolerance. I went ahead and submitted a pull request. 

Thanks,
Dustin

**Comment by jsvine** [comment]
Done! Cf.: https://github.com/jsvine/pdfplumber/pull/51
