### ISSUE TITLE
extracting table from multiple pages at time.

### ISSUE THREAD

**Issue by Harshit-tech9** [jsvine/pdfplumber#549]
Please describe, in as much detail as possible, your proposal and how it would improve your experience with pdfplumber.

Hey! Thanks for developing such good library. Currently I am working on project where I need to extract table from Bank account  Statement. In this library we can extract table from one page at a time and we cannot iterate over multiple pages. Its an humble request to you folks to add this feature in your library.

**Comment by samkit-jain** [comment]
Hi @Harshit-tech9 Appreciate your interest in the library. Could you please add even more details? A minimum reproducible code example will be good as well.

I'm not exactly sure what you mean by support for multiple pages. You can extract tables from multiple pages by 

```python
for page in pdf.pages:
    page.extract_tables()
```

Is that what you meant?

**Comment by Harshit-tech9** [comment]
Hey! yes that's what I mean.
But when I save it to CSV using pandas only last page table gets converted.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by samkit-jain** [comment]
Could you please share the code that you are using so that I can debug further?

**Comment by Harshit-tech9** [comment]
Hey! Sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jsvine** [comment]
Hi @Harshit-tech9 and thanks @samkit-jain! Given that this seems to be a Python coding question rather than a `pdfplumber`-specific concern, I'm closing this issue. But feel free to continue troubleshooting here!
