### ISSUE TITLE
Units for x, y, top, bottom etc?

### ISSUE THREAD

**Issue by daudk** [jsvine/pdfplumber#55]
Thanks so much for this project, I can't for the life of me find another library in python that had anything similar to your crop within_bbox feature.

My question is, what are the units on the values of x0, y0, top and bottom? The "boxes" in pdfs like CropBox, MediaBox, TrimBox are all measured from the bottom left of the page and in the standard units of 1 inch=72 points.

I'm trying to use the CropBox  of a pdf with the within_bbox feature but can't seem to find any correlation between the units. I realize that pdfplumber has origin (0,0) set to top left but I still can't figure out the size of the units.

Thanks.

**Comment by jsvine** [comment]
Hi, @daudk. As far as I'm aware, `within_bbox` uses the same units as `CropBox`, `MediaBox`, et cetera. Do you have an example PDF and code that demonstrates the problem you're encountering?

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
