### ISSUE TITLE
Issue to reading data from the pdf

### ISSUE THREAD

**Issue by sravanikothakota** [jsvine/pdfplumber#567]
## Describe the bug

I am reading data of a PDF through a Pdfplumber which was working as expected in python 3.9 version but same when i am testing in 3.7 version it extracted only 2 words and total data is missing.

## PDF file
I could not attach the pdf as it is having sensitive information
*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*
it should read total data from the file as the pdf is text based.

## Actual behavior
*What actually happened, instead?*
it is working in python 3.9 version but unable to get data in 3.7 version

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.5.22] 0.5.28
- Python version: [e.g., 3.8.1]3.7 & 3.9
- OS: [e.g., Mac, Linux, etc.] windows

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hi @sravanikothakota, and thanks for your interest in this library. That's a very strange phenomenon you are reporting — I don't think I've heard of that happening before. Without the PDF, code, or other details, however, it's very difficult to determine what might be happening. Closing this issue for now, but feel free to reopen with more information.
