### ISSUE TITLE
v0.6.0 issue divide by 0 when cropping page

### ISSUE THREAD

**Issue by dustindall** [jsvine/pdfplumber#58]
I ran into an issue of divide by 0 when using crop with v0.6.0 (see snippet below).

![image](https://user-images.githubusercontent.com/8218382/38769611-86b2876a-3fba-11e8-9e17-4a4b1fc215f0.png)

It was caused by a 'char' object having either orig['height'] = 0 or orig['width'] = 0.

I was able fix the issue on my end. See PR.

Thanks,
Dustin

**Comment by jsvine** [comment]
Cleaning up old issues. This looks like it was discussed via the aforementioned PR.
