### ISSUE TITLE
ModuleNotFoundError: No module named 'pdfplumber'

### ISSUE THREAD

**Issue by sollama** [jsvine/pdfplumber#597]
## Describe the bug

I'm working in jupyter notebook. I'm unable to import pdfplumber for some reason

## Code to reproduce the problem

!pip install pdfplumber --user 
import pdfplumber

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

For the import cell to run through

## Actual behavior

*What actually happened, instead?*
Screenshot shows that pdfplumber was installed successfully, but I received a ModuleNotFoundError: No module named 'pdfplumber'.

## Screenshots

*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/40960146/152403875-9a6d487e-1c20-4213-bde2-6a296c500c38.png)

## Environment

- pdfplumber version: [e.g., 0.5.22]
- Python version: [e.g., 3.8.1]
- OS: [e.g., Mac, Linux, etc.]

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hi @sollama, and thanks for your interest in this library. Usually when I see errors like that, it's unrelated to `pdfplumber` but rather more generally related to the Python environment. One way to test this: What happens if you try doing the same thing, but instead of `pdfplumber` you try installing and importing any other external Python library, e.g., `requests`?

**Comment by jsvine** [comment]
Looking more closely at the error messages, it appears that you may be using `pip` in an Anaconda environment. What if you try replacing `!pip install pdfplumber` with `!conda install pdfplumber`?

**Comment by sollama** [comment]
Hi,

Thanks for getting back so quickly.

1. Installing and importing requests has no error
2. I tried using !conda install pdfplumber. I received this error:
![image](https://user-images.githubusercontent.com/40960146/152442430-f1895be8-a7e9-48e1-afd5-8eb1f31bf880.png)

Like they suggested, I went on the anaconda site to find the package
and tried this next. I still got an error, error message pasted below.

![image](https://user-images.githubusercontent.com/40960146/152442468-9de86d0c-767b-4cd6-84cc-586393685f1d.png)

**Comment by jsvine** [comment]
Thanks for sharing that. And, hmmm, I'm not very familiar with Anaconda/conda debugging, so I'm not quite sure what's going on there. As an alternative, perhaps create a new, pure-pip environment, and retry there? Something like:

```sh
cd path/to/my/project
python -m venv venv  # create the virtual environment
source venv/bin/activate # activate it
pip install jupyter pdfplumber # install the libraries
jupyter notebook # launch a Jupyter notebook from within the environment
```

**Comment by samkit-jain** [comment]
@sollama Have you tried installing pdfplumber without `--user`? Using `--user` is not required when you are running inside a virtual environment. I tested this on [Google Colaborator](https://colab.research.google.com/) and if I install via `--user`, I can't import the package but if I install without it, I am able to use just fine.

**Comment by sollama** [comment]
It worked when I installed without the - - user. Thank you all for your
help :)
