### ISSUE TITLE
Unable to recognize lines of PDF

### ISSUE THREAD

**Issue by diorw** [jsvine/pdfplumber#607]
## Describe the bug

*A clear and concise description of what the bug is.*

I want to identify the lines of the invoice PDF. I find that even for very similar invoices, some of the lines of the invoice are empty or few I want to ask why

## Code to reproduce the problem
            pdf = pb.open(self.file)
            page = pdf.pages[0]
            lines = page.lines
            # lines = []

*Paste it here, or attach a Python file.*

## PDF file

[电子发票.pdf](https://github.com/jsvine/pdfplumber/files/8087618/default.pdf)

## Environment

- pdfplumber version: 0.6.0
- Python version: 3.8
- OS: Linux centos

**Comment by jsvine** [comment]
Hi @diorw, and thanks for your interest in this library. For the example PDF you've provided, the "lines" are actually represented as rectangles, and can be retrieved via `page.rects`.

If you want to "decompose" the rectangles into the lines they contain, you can use `page.edges`.
