### ISSUE TITLE
Link to ghostscript installation

### ISSUE THREAD

**Issue by vmgottin** [jsvine/pdfplumber#608]
Hi, folks. Very minor issue. 
The link to the ghostcript installation is currently 404'ing- in the README, "Visual Debugging" section. 
I think that
https://www.ghostscript.com/doc/9.21/Install.htm
should be
https://www.ghostscript.com/doc/current/Install.htm

**Comment by jsvine** [comment]
Thank you, @vmgottin! Now fixed 👍
