### ISSUE TITLE
pdfminer extracting text incorrectly

### ISSUE THREAD

**Issue by IrinaMax** [jsvine/pdfplumber#611]

**Comment by IrinaMax** [comment]
![image](https://user-images.githubusercontent.com/16123495/155099817-4aa2c5a4-d069-4a75-a54b-61a7c83415f6.png)

**Comment by jsvine** [comment]
Unfortunately, I see no information in this issue, so will be closing it. Feel free to follow up with details.

<img width="630" alt="Screen Shot 2022-03-02 at 7 54 01 PM" src="https://user-images.githubusercontent.com/534702/156481221-b911e554-e8c0-4f3a-82e9-2d0367a3dbd6.png">
