### ISSUE TITLE
write cropped document to separate pdf

### ISSUE THREAD

**Issue by suyogchadawar** [jsvine/pdfplumber#62]
Hi thanks for the project,
This is the best library so far while working with pdfs, but i couldn't find anything to write a cropped pdf document to another pdf.  How can I write cropped pdf to new document? and is scale for CropBox or crop same as that of doctop,x0,bottom of a char extracted from pdf (i.e. ".char" of pdfplumber.Page class)?

**Comment by jsvine** [comment]
Hi @suyogchadawar! Regarding your questions:

>  i couldn't find anything to write a cropped pdf document to another pdf. How can I write cropped pdf to new document? 

`pdfplumber` only reads and extracts information from PDFs, but (currently) does not write them. If you're just looking to write cropped PDFs, you may have more luck with CPDF or other similar tools: http://community.coherentpdf.com/

> is scale for CropBox or crop same as that of doctop,x0,bottom of a char extracted from pdf (i.e. ".char" of pdfplumber.Page class)?

I don't quite understand this question. Could you restate it, or provide an example?

**Comment by awa5114** [comment]
@suyogchadawar Are there any future plans to add this sort of functionality to `pdfplumber`? It would be extremely useful.

I had a look at CPDF, but what I'm trying to achieve is not only crop the pdf but also the underlying text content. For instance, suppose my pdf contains the text "Hello world" (pseudocode):

```
import pdfplumber
from decimal import Decimal

crop_ratio = Decimal(0.5)
source_file = 'file_containing_hello_world.pdf'
with pdfplumber.open(source_file) as pdf:
    page = pdf.pages[0]
    # print(page.extract_text()) => "Hello world"
    x0, top, x1, bottom = page.bbox
    height = top-bottom
    bottom = top-crop_ratio*height
    cropped_page = page.within_bbox((x0, top, x1, bottom))
```

Now suppose I would like to write this cropped page to a called  `file_containing_only_hello.pdf`. Reading this new file would go like this:

```
import PyPDF2
from decimal import Decimal

source_file = 'file_containing_only_hello.pdf'
with pdfplumber.open(source_file) as pdf:
    page = pdf.pages[0]

print(page.extract_text()) # => "Hello"
```

Can I do the above with cpdf? Or is that not possible at this time?
