### ISSUE TITLE
Character merged incorrectly when using extract_words()

### ISSUE THREAD

**Issue by datdao1998** [jsvine/pdfplumber#627]
When using function extract_words(), some words are merged into one word, like image  bellow (with to_image method)
![image](https://user-images.githubusercontent.com/42546396/158922930-16c73d6d-6587-4b00-be4d-efd767e7b2d3.png)

I think the reason is in that code in **pdfplumber/utils.py**
![image](https://user-images.githubusercontent.com/42546396/158923177-22ad68de-7485-444f-b0bc-3fe2ca9d4a3a.png)

In that code, we will check if next character is belong to current bounding box or not, but in my example case (**bbox.xmin = next_char.xmin** and **bbox.bottom ~ next_char.top**) , the boolean result is False, so **the first character of second word is extend to the first word** (and we get "firsts"), and the next character is extend too, so on...
![image](https://user-images.githubusercontent.com/42546396/158927894-447381ca-68b3-4ee8-95fb-361bc782f157.png)

I think we need to improve the condition to catch this case.

**Comment by jsvine** [comment]
Hi @datdao1998, have you tried adjusting the `x_tolerance` and `y_tolerance` parameters in `extract_words(...)`? In your case, it looks like setting both to 0 (or even something like -3) may get you what your looking for.

If that doesn't work, or you have questions about how to use the parameters, please attach the PDF you're working with. Without a specific PDF, it is difficult to provide much additional advice or to debug.

**Comment by datdao1998** [comment]
@jsvine  Thanks for your advice. I tried with **y_tolerance=-3** and it works ! I will test with other PDFs in my dataset, and if I have other problem I will reopen my issue later.
