### ISSUE TITLE
Font size of the char given by pdfplumber is diffrent from the actual font size.

### ISSUE THREAD

**Issue by suyogchadawar** [jsvine/pdfplumber#63]
Hi, the font size given by pdfplumber does not match with the font size given by adobe acrobat dc pro. Is there any correlation between them?
Can we get font color from pdfplumber?

**Comment by jsvine** [comment]
> the font size given by pdfplumber does not match with the font size given by adobe acrobat dc pro. 

Can you provide the following?:

- An example of a PDF that displays this behavior
- The output you get
- The font size that Adobe Acrobat indicates

> Can we get font color from pdfplumber?

In `pdfplumber` output for the text/characters of interest, do you see the `fill` and `stroke` attributes? If not, can you paste the `pdfplumber` object-representation for a character that you believe should have color information but doesn't?

**Comment by suyogchadawar** [comment]
> In pdfplumber output for the text/characters of interest, do you see the fill and stroke attributes? If not, can you paste the pdfplumber object-representation for a character that you believe should have color information but doesn't

`{'adv': Decimal('0.507'), 'fontname': 'QYZTAI+Calibri-Light', 'doctop': Decimal('83.708'), 'y1': Decimal('708.292'), 'bottom': Decimal('100.704'), 'text': u'1', 'top': Decimal('83.708'), 'object_type': 'char', 'height': Decimal('16.996'), 'width': Decimal('7.057'), 'page_number': 1, 'upright': True, 'y0': Decimal('691.296'), 'x0': Decimal('72.000'), 'x1': Decimal('79.057'), 'size': Decimal('16.996')}
`

i got this output by using following code:

` file_read=pdfplumber.open(in_file)

for temp in file_read.pages:

    dict_char = temp.chars

    for t in dict_char:

        print(t) `

**Comment by suyogchadawar** [comment]
> An example of a PDF that displays this behavior
The output you get
The font size that Adobe Acrobat indicates

1
[splited0.pdf](https://github.com/jsvine/pdfplumber/files/2039614/splited0.pdf)

2
`{'adv': Decimal('0.507'), 'fontname': 'QYZTAI+Calibri-Light', 'doctop': Decimal('83.708'), 'y1': Decimal('708.292'), 'bottom': Decimal('100.704'), 'text': u'1', 'top': Decimal('83.708'), 'object_type': 'char', 'height': Decimal('16.996'), 'width': Decimal('7.057'), 'page_number': 1, 'upright': True, 'y0': Decimal('691.296'), 'x0': Decimal('72.000'), 'x1': Decimal('79.057'), 'size': Decimal('16.996')}`

3
13.92
![capture](https://user-images.githubusercontent.com/11314425/40548799-54d8260a-6053-11e8-9987-c54d03f7ddfc.PNG)

**Comment by suyogchadawar** [comment]
hi @jsvine , did you get the chance to look into this?

**Comment by jsvine** [comment]
Hi, @suyogchadawar. I don't know exactly what's causing this issue; pdfplumber depends on [pdfminer.six](https://github.com/pdfminer/pdfminer.six) for text extraction. It does seem, though, that you can arrive at the Adobe-determined font size by dividing `width` by `adv`. In your example, that'd be: `7.057 / 0.507 = 13.919`. 

See here for the computation of the `adv` attribute: https://github.com/euske/pdfminer/blob/master/pdfminer/layout.py#L230

**Comment by suyogchadawar** [comment]
Thanks this worked for me

> It does seem, though, that you can arrive at the Adobe-determined font size by dividing width by adv. 



but still I am not able to find color of the character  from pdfplumber.

**Comment by suyogchadawar** [comment]
ok sure thanks
