### ISSUE TITLE
我想把pdf中的表单独剪裁成单独的图片保存,能否告诉下怎么操作???

### ISSUE THREAD

**Issue by zhangchangrui** [jsvine/pdfplumber#64]

**Comment by jsvine** [comment]
不幸的是，我不明白这个问题。 你能否更详细地解释你的问题，并提供一个例子？

（我正在通过Google翻译进行撰写。）

**Comment by wanghaisheng** [comment]
you can use **pdfplumber.Page.find_tables(table_settings={})** to get a table object ,and then get   "bbox" from these table object,at last **pdfplumber.Page.crop(bounding_box) .to_image(**conversion_kwargs)**

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
