### ISSUE TITLE
page to_image() get stuck in ProcessPoolExecutor

### ISSUE THREAD

**Issue by qyhou** [jsvine/pdfplumber#643]
## Code to reproduce the problem

```
from concurrent import futures

import pdfplumber


def page0_to_image(pdf_path):
    with pdfplumber.open(pdf_path) as pdf:
        page0 = pdf.pages[0]
        print('{} start'.format(pdf_path))
        page0_image = page0.to_image(resolution=300)
        print('{} end'.format(pdf_path))
        page0_image.save('{}.png'.format(pdf_path))
    return True


def run_with_multiprocess(executor, pdf_path_list):
    for pdf_path in pdf_path_list:
        yield executor.submit(
            page0_to_image,
            pdf_path,
        )


def main():
    results = []

    pdf_path_1 = '1.pdf'
    result_1 = page0_to_image(pdf_path_1)
    results.append(result_1)

    pdf_path_list = ['2.pdf', '3.pdf']
    with futures.ProcessPoolExecutor(max_workers=2) as executor:
        for future in futures.as_completed(
                run_with_multiprocess(executor, pdf_path_list)):
            results.append(future.result())


if __name__ == '__main__':
    main()
```

## Describe the bug

As shown in the code, the program get stuck at page.to_image() in ProcessPoolExecutor.
It will be successful if only running multi process code as shown below.

```
def main():
    results = []

    # pdf_path_1 = '1.pdf'
    # result_1 = page0_to_image(pdf_path_1)
    # results.append(result_1)

    pdf_path_list = ['2.pdf', '3.pdf']
    with futures.ProcessPoolExecutor(max_workers=2) as executor:
        for future in futures.as_completed(
                run_with_multiprocess(executor, pdf_path_list)):
            results.append(future.result())
```

From my point of view, the two parts of the code shouldn't affect each other, is right?
What could be the cause of this problem?

## Screenshots

<img width="673" alt="image" src="https://user-images.githubusercontent.com/23006446/163977761-384f4e0c-cf2a-4ac5-a66b-95091252b345.png">

## Environment

- pdfplumber version: 0.6.0
- Python version: 3.7.9
- OS: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic x86_64)

**Comment by jsvine** [comment]
Hi @qiyuhou and thanks for your interest in this library. I'm not very familiar with `ProcessPoolExecutor`, so this might take me a little while to investigate. In the meantime, if anyone in the community has a suggestion, I welcome your input.

**Comment by jsvine** [comment]
Hi @qiyuhou, and thanks again for sharing this snippet. I have now tested your code with three semi-randomly selected PDFs. It seems to work just fine for me, using pdfplumber v0.7.3 on a Mac. Perhaps try upgrading `pdfplumber` and see if you're still having the same problem? And you're right about this:

> From my point of view, the two parts of the code shouldn't affect each other, is right?

Given my inability to reproduce the problem you're encountering, and the lack of specific information pointing to a bug in `pdfplumber`, I'm closing this issue for now. But feel free to continue the discussion and/or provide additional information that could help with debugging.
