### ISSUE TITLE
Is there a way that I can get the colour info of the character/line?

### ISSUE THREAD

**Issue by aidsj** [jsvine/pdfplumber#65]

**Comment by jsvine** [comment]
Not currently, but it looks like we might be able to add that, thanks to https://github.com/pdfminer/pdfminer.six/pull/129. I'll look into it.

**Comment by mvanaltvorst** [comment]
Any updates on this?

**Comment by Mahendra114027** [comment]
I know its kinda long but you can check out this thread [here](https://github.com/jsvine/pdfplumber/issues/148).

**Comment by jsvine** [comment]
Thanks, @Mahendra114027. And, yes, some basic color info is indeed available in `pdfplumber` objects, thanks to `pdfminer.six`.

**Comment by ek-ok** [comment]
> Thanks, @Mahendra114027. And, yes, some basic color info is indeed available in `pdfplumber` objects, thanks to `pdfminer.six`.

Is there any documentation to extract the color info using `pdfplumber`?

**Comment by jsvine** [comment]
Currently there is not, but it is worth adding. In the meantime, color information should be available simply by examining the object dictionaries `pdfplumber` produces. For instance :`print(my_page.chars[0])`. (Look for `'stroking_color'` and `'non_stroking_color'`.)

**Comment by ek-ok** [comment]
Thanks for your answer. Looks great, for my data `my_page.chars[0]['stroking_color']` shows `(0.31, 0.506, 0.741)`. I am guessing this is r,g,b? What is the difference between `stroking_color` and `non_stroking_color`? For my case, they show the same values for all characters.

**Comment by jsvine** [comment]
PDFs have the ability to specify colors in many ways. RGB is common, and that does look like what you have here. But for a fuller understanding of the possibilities, see Section 4.5 of the [official PDF reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf). I'm not sure whether `pdfminer.six` provides access to enough detail for `pdfplumber` to determine the particular "color space," but I'll try to look into it.

You can think of `stroking_color` as the outline of a shape (the "stroke"), and `non_stroking_color` as the body of the shape (sometimes called the "fill").

**Comment by ek-ok** [comment]
> PDFs have the ability to specify colors in many ways. RGB is common, and that does look like what you have here. But for a fuller understanding of the possibilities, see Section 4.5 of the [official PDF reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf). I'm not sure whether `pdfminer.six` provides access to enough detail for `pdfplumber` to determine the particular "color space," but I'll try to look into it.
> 
> You can think of `stroking_color` as the outline of a shape (the "stroke"), and `non_stroking_color` as the body of the shape (sometimes called the "fill").

This is very helpful. Thank you!
