### ISSUE TITLE
ValueError when using debug_tablefinder

### ISSUE THREAD

**Issue by rneumann7** [jsvine/pdfplumber#659]
## Describe the bug

Tried the extract-table-ca-warn-report.pynb example and got an ValueError when trying to call debug_tablefinder on PageImage.

## Code to reproduce the problem

See extract-table-ca-warn-report.ipynb from examples/notebooks/extract-table-ca-warn-report.ipynb, last section (12)

## Screenshots
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/104763879/171131095-42028d43-1ebb-4178-a833-ae4dc29e1617.png">

## Environment

- pdfplumber version: [0.6.2]

**Comment by jsvine** [comment]
Thank you for flagging this @rneumann7! Have now squashed that bug and pushed the fix to this repository and a new version, v0.7.1.
