### ISSUE TITLE
Space character missing when using extract_tables()

### ISSUE THREAD

**Issue by samkit-jain** [jsvine/pdfplumber#66]
I am using the following settings when extracting tables from PDF
```
'table_settings': {
    "vertical_strategy": "lines",
    "horizontal_strategy": "text",
    "intersection_x_tolerance": 15,
}
```

When using `extract_text(x_tolerance=0, y_tolerance=0)` on the `Page` object it preserves the spacing in the PDF file. But, when using `extract_tables()` with the `table_settings` mentioned above, no spacing is preserved. It is able to correctly extract the table but there are no spaces in any of the row's text.

Example, output of `extract_text`,
```PAYPAL POS DEBIT``` (Correct)

output of `extract_tables`,
```PAYPALPOSDEBIT``` (Incorrect)

**Comment by samkit-jain** [comment]
Thanks for sharing the workaround @jsvine Yes, the workaround works. Is the bug being worked upon?

**Comment by jsvine** [comment]
It will be fixed in the next release, though the parameters will change slightly. (See https://github.com/jsvine/pdfplumber/blob/v0.6.0/pdfplumber/table.py#L350 for a preview; the new approach lets you pass a sub-dict of `text_kwargs`.) Unfortunately, due to time constraints, I don't know exactly when that will be.

**Comment by Yashs744** [comment]
I'm facing a similar issue. I tried this code to solve the issue
```
tables = my_page.find_tables(my_table_settings)
extracted = [ t.extract(x_tolerance=0, y_tolerance=0) for t in tables ]
```
It did solve the problem for the targeting pdf but it adds extract spaces in other pdf. for example 
`mcdonalds` become `m cdonals`.

Is there a more generic way to solve this problem?

**Comment by shrijit04** [comment]
is this resolved or is there any table setting that remedies this issue?
