### ISSUE TITLE
Identify contiguous rectangles with different fill colors (e.g. formatted table) as one Rectangle object

### ISSUE THREAD

**Issue by moreproblems** [jsvine/pdfplumber#668]
When finding rectangles on a page, the package seems to mess up the bounding box when there is more than one fill color. Taking the example of the attached image, the bounding box will be that of the first row filled in grey (and the rest of the table will be ignored.

![image](https://user-images.githubusercontent.com/105331056/173364932-e39e92fb-336b-468a-af8d-1b7d5aa6b002.png)

**Comment by jsvine** [comment]
Hi @moreproblems, and thanks for your interest in this library. Unfortunately, I'm having some trouble understanding the query here. Could you share the PDF itself and code that demonstrates your situation?

Closing this for now, as it's not clear there's a bug or practical feature request here, but we can continue the conversation.
