### ISSUE TITLE
Cannot get metadata nor pages from a scanned pdf without text

### ISSUE THREAD

**Issue by BryanKoo** [jsvine/pdfplumber#669]
## Describe the bug

Cannot get metadata nor pages from a single page pdf without text

## Code to reproduce the problem

```
with pdfplumber.open("invoice.pdf") as pdf:
    print(pdf.metadata)
    print(len(pdf.pages))
```

## PDF file

[invoice.pdf](https://github.com/jsvine/pdfplumber/files/8894882/invoice.pdf)

## Expected behavior

pdf.metadata should be a non-empty dictionary
len(pdf.pages) should be 5

## Actual behavior

pdf.metadata is an empty dictionary
len(pdf.pages) is 0

## Environment

- pdfplumber version: 0.6.1 - 0.7.1
- Python version: 3.8.0
- OS: linux and mac

**Comment by jsvine** [comment]
Hi @BryanKoo, and thanks for your interest in this library. It seems that this PDF is malformed. Here's the relevant output from `cpdf -info invoice.pdf`:

```
cpdf encountered an error. Technical details follow:

No or malformed /Pages

Encryption: Not encrypted
Permissions: 
Linearized: false
Version: 1.3
```

... and from `gs invoice.pdf`: 

```
The following errors were encountered at least once while processing this file:
        object lacks an endobj
``` 

You can repair the PDF by running `gs   -o repaired.pdf   -sDEVICE=pdfwrite   -dPDFSETTINGS=/prepress    invoice.pdf`, after which your code above should work as expected.

**Comment by BryanKoo** [comment]
Thanks a lot for addressing this issue. I understood your answer.

Just want to inform you that this malformed PDF is from a public site. https://publicfiles.fcc.gov/
(https://publicfiles.fcc.gov/find/invoice/page-offset-0/order-best-match/filter-none/#files if you want to search invoices)
And I expect that there exist more sources of malformed PDFs other than this site.

I know that PDF format is so complex and this issue would/should be addressed by **pdfminer.six**, if needed.
Thanks again for the kind explanation on how to repair malformed PDFs.
