### ISSUE TITLE
Can I submit a Chinese document translated from README.md

### ISSUE THREAD

**Issue by hbh112233abc** [jsvine/pdfplumber#674]
Hi, pdfplumber is very good library for extract table from PDF.
[README-CN.md](https://github.com/jsvine/pdfplumber/files/9007924/README-CN.md)

Can I submit a Chinese document translated from README.md.
I think it will helpful for chinese developer.

**Comment by jsvine** [comment]
Hi @hbh112233abc, and thank you for this contribution! I think adding translations is a great idea. The easiest approach, I think, would be for you to host `README-CN.md` in your own repository (perhaps `hbh112233abc/pdfplumber-README-CN`) and then I could link to your repository from the main README.md. That way, you can easily make additions/changes without having to submit PRs/etc. here. What do you think about this option?

**Comment by hbh112233abc** [comment]
Good idea! I fork `pdfplumber` and add `README-CN.md`, it's link is `https://github.com/hbh112233abc/pdfplumber/blob/stable/README-CN.md`.

**Comment by jsvine** [comment]
Thank you! I will aim to add a link soon.

**Comment by hbh112233abc** [comment]
> Thank you! I will aim to add a link soon.

Thanks!
