### ISSUE TITLE
Is there a way to extract the second table on the same page?

### ISSUE THREAD

**Issue by guoxinrun** [jsvine/pdfplumber#68]

**Comment by guoxinrun** [comment]
Page.extract_table() method can only find a table on a page.
Page.find_tables() method return tables objects but not content.
But I want to extract the second table on page, is there a way?

**Comment by jsvine** [comment]
From a table object, you should be able to call `table_obj.extract(...)`. (Relevant code [here](https://github.com/jsvine/pdfplumber/blob/v0.5.9/pdfplumber/table.py#L351).) So, for instance:

```python
tables = my_page.find_tables()
t2_content = tables[1].extract(x_tolerance = 5)
```

Does that work for you?

**Comment by jsvine** [comment]
Great, and congrats! If you publish the code you used for the competition, or write a blog post about using `pdfplumber`, I'd be very interested to read it.

**Comment by RashmiPareek** [comment]
@jsvine Thanks :) It helped me today as well for multiple PDF :))

**Comment by imadhaj** [comment]
To extract two tables from the same pages i use this code


import pdfplumber

with pdfplumber.open("file.pdf") as pdf:
    first_page = pdf.pages[0].find_tables()
    t1_content = first_page[0].extract(x_tolerance = 5)
    t2_content = first_page[1].extract(x_tolerance = 5)
    print(t1_content, '\n' ,t2_content)

**Comment by imadhaj** [comment]
To extract two tables from the same pages i use this code
```
import pdfplumber

with pdfplumber.open("file.pdf") as pdf:
    first_page = pdf.pages[0].find_tables()
    t1_content = first_page[0].extract(x_tolerance = 5)
    t2_content = first_page[1].extract(x_tolerance = 5)
    print(t1_content, '\n' ,t2_content)

```
