### ISSUE TITLE
pdfplumber will be hung up when open pdf which is damaged

### ISSUE THREAD

**Issue by Gadil-1987** [jsvine/pdfplumber#681]
## Describe the bug

pdfplumber will be hung up when open pdf which is damaged

## Code to reproduce the problem

import pdfplumber
pdf = pdfplumber.open("C:/Users/admin/Desktop/AN202103291477905709.pdf")
print(len(pdf.pages))

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Environment

- pdfplumber version: [e.g., 0.7.0]
- Python version: [e.g., 3.8.2]
- OS: [WIN10]

**Comment by Gadil-1987** [comment]
Sorry，I don't know how to upload my tested pdf file to github，if anyone knows，please tell me

**Comment by jsvine** [comment]
Hi @Gadil-1987, in the comment box on GitHub, you should see something that says: "Attach files by dragging & dropping, selecting or pasting them."

<img width="447" alt="Screen Shot 2022-07-05 at 5 10 38 PM" src="https://user-images.githubusercontent.com/534702/177436662-9ba9b3b0-e18b-4f28-970c-7a38f449bb5e.png">

Does that work for you?

**Comment by Gadil-1987** [comment]
I see, 3ks.

**Comment by Gadil-1987** [comment]
[AN202002141375118541.pdf](https://github.com/jsvine/pdfplumber/files/9051297/AN202002141375118541.pdf)
[AN202103291477905709.pdf](https://github.com/jsvine/pdfplumber/files/9051298/AN202103291477905709.pdf)

these two pdf files could make pdfplumbe to be hung up.
maybe i need to try other ways to make sure current pdf file is ok

**Comment by Gadil-1987** [comment]
![image](https://user-images.githubusercontent.com/108721053/177678740-aa279db5-fdad-4516-94f8-f370c4fed583.png)
To fix this issue, I had to use PyPDF2

**Comment by Gadil-1987** [comment]
![image](https://user-images.githubusercontent.com/108721053/177678740-aa279db5-fdad-4516-94f8-f370c4fed583.png)
To fix this issue, I had to use PyPDF2

**Comment by jsvine** [comment]
Hi @Gadil-1987, and thanks for your interest in this library. Given that these PDFs are pretty badly corrupted (neither CPDF or GhostScript were able to repair them), and because the root issue seems to come from [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six), this project's main dependency, I'm going to close this issue. Still, it's good to know about and I appreciate you pointing it out.

**Comment by Gadil-1987** [comment]
Thanks, This libray helps me a lot
