### ISSUE TITLE
AttributeError: 'LTChar' object has no attribute 'graphicstate' trying to use the table function

### ISSUE THREAD

**Issue by Da-vid21** [jsvine/pdfplumber#692]
So I was running this code `bool(double_column.pages[2].extract_table(dict(vertical_strategy='text', text_tolerance=12)))` it worked fine last week, but now it's giving me this  error, ![image](https://user-images.githubusercontent.com/82111747/180072731-62daf76c-ff2d-4e17-aaa3-24dbfce06499.png) Can someone help me out? Thanks

# [My code](https://github.com/Da-vid21/tosth/blob/main/pdftotext1.py)

**Comment by jsvine** [comment]
Hi @Da-vid21, my hunch is that you might have a different version of `pdfminer.six` (this library's main dependency) installed — or possibly `pdfminer` installed instead of `pdfminer.six`. The latest/pinned version is `20220524`. Which do you get when you run `pip freeze`?

**Comment by Da-vid21** [comment]
Yes, I had other scripts that depended on pdfminer, so I removed pdfminer, pdfminer.six, and
pdflumber and installed pdfplumber again that fixed it. Thanks

**Comment by Da-vid21** [comment]
Yes, I had other scripts that depended on pdfminer, so I removed pdfminer, pdfminer.six, and
pdflumber and installed pdfplumber again that fixed it. Thanks
