### ISSUE TITLE
Extracting Z-Value of Rects/Items

### ISSUE THREAD

**Issue by JosefJoubert** [jsvine/pdfplumber#700]
Hi,

First off, thanks for your work. This library greatly useful to me.

I am importing a PDF which represents a floorplan for a building, which contains a lot of graphical objects.
Some of these objects are filled rectangles/curves.
When I view the PDF in other software, it consistently draws some rectangles over others, so I assume there is some data concerning the Z-value/draw-order of the rectangles.
However, I have not found a way to extract this data with pdfplumber. 

Is this functionality available and I'm just missing it? If not, could it be added?

Thank you for your time.

**Comment by jsvine** [comment]
Hi @JosefJoubert, and glad to hear that this library has been helpful. To answer your question: Unlike some other layout systems (e.g., that used by CSS),  PDFs don't have a concept of z-index. Instead, graphical elements appear bottom-to-top in the order they are generated in the file. For more information on this, and advice on how to determine the relative order, see this discussion: https://github.com/jsvine/pdfplumber/discussions/694
