### ISSUE TITLE
Text Box object

### ISSUE THREAD

**Issue by dufferzafar** [jsvine/pdfplumber#73]
pdfplumber has character level information.

But I'm more interested in a text box - essentially a word - that also has font information.

How can that be achieved?

**Comment by jsvine** [comment]
This functionality has been added in [v0.6.0-alpha](https://github.com/jsvine/pdfplumber/blob/v0.6.0/CHANGELOG.md#added). It won't be merged into `master` until v0.6.0 is stable/complete, on which I unfortunately have not made as much progress as I would like. In the meantime, though, you can install the alpha via `pip install -e git+https://github.com/jsvine/pdfplumber@v0.6.0-alpha#egg=pdfplumber`
