### ISSUE TITLE
How to get information of superscript and subscript text in the pdf

### ISSUE THREAD

**Issue by sarveshkrg** [jsvine/pdfplumber#731]
Hi, anyone please help to get superscript subscript text identification from normal text in the pdf so that I can save the chemical formula and other constant values present in the pdf as it is into the excel. Thanks in advance.
Input
![image](https://user-images.githubusercontent.com/46168717/190211058-ab209236-6449-4fc8-94f0-b4b8cd23a441.png)
Output
![image](https://user-images.githubusercontent.com/46168717/190211121-f634a5f1-fd90-40ae-87e7-845920b98d9a.png)

**Comment by jsvine** [comment]
Closing as duplicate of #730
