### ISSUE TITLE
Heuristic based title detection

### ISSUE THREAD

**Issue by dufferzafar** [jsvine/pdfplumber#74]
Hi, I saw that you perform PDF table detection using an algorithm from the Nuriminen thesis.

Just like tables, one of the things that you can extract from a PDF is its title.

Some PDFs have the "title" metadata file, but more often than not, they contain wrong text.

KDEFileMetadata (written in C++) is one of the projects that used some heuristics to guess the title. [You can have a look at the code here.](https://github.com/KDE/kfilemetadata/commit/1491c4a2d9fd7adb075258d7eb65f4ae1d7169f4#diff-ec6bd17e68486d574e420abfcfffbc88)

A feature like this is useful in detecting title from research papers - which could further be used to rename the PDF files! 

So from a filename like `gfs-sosp2003.pdf` you can get `Google File System - 2003.pdf`

**Comment by jsvine** [comment]
Interesting, and thanks for sharing! I think this is a bit outside the scope of `pdfplumber`'s core functionality, but seems like a worthwhile extension. If anyone wants to build such an extension/library, I'd happily link to it from `pdfplumber`'s documentation.

**Comment by dufferzafar** [comment]
I'll probably write a script myself. I'll either use pdfplumber or some
python poppler bindings.

Since you feel this is out of scope, feel free to close the issue :)

**Comment by jsvine** [comment]
👍
