### ISSUE TITLE
Reding different words as continuous one word.

### ISSUE THREAD

**Issue by ameymn** [jsvine/pdfplumber#752]
## Describe the bug

When we read the pdf using pdfplumber the bug is it is reading some  individual words together as single long word

## Code to reproduce the problem

<img width="470" alt="image" src="https://user-images.githubusercontent.com/84408423/199755425-22349a4a-c9b7-4ed0-82c6-1f968ce7a994.png">

## PDF file

[pdfplumber bug.pdf](https://github.com/jsvine/pdfplumber/files/9930314/pdfplumber.bug.pdf)

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

I was expecting the words to be read individually as they has space between them.

## Actual behavior

It is ignoring space between word and many individual word as continuous long word .

## Screenshots

<img width="603" alt="image" src="https://user-images.githubusercontent.com/84408423/199751180-0ff07b97-b730-453d-939c-245087223355.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/84408423/199753214-176ac17b-7b81-4db8-bfb8-38c13134e71b.png">

## Environment

- pdfplumber version: [0.7.5]
- Python version: [3.9.7]
- OS: [Windows]

**Comment by jsvine** [comment]
Hi @ameymn, have you tried using the `x_tolerance=` parameter of `.extract_text(...)`?:

<img width="838" alt="Screen Shot 2022-11-03 at 4 34 25 PM" src="https://user-images.githubusercontent.com/534702/199828507-0baf0745-2794-490f-80d6-4e9da268e689.png">

**Comment by jsvine** [comment]
Closing this issue due to likely resolution posted, lack of response, and lack of original PDF to test against. Feel free, however, to continue the discussion.
