### ISSUE TITLE
Inclusion of a CITATION.cff file

### ISSUE THREAD

**Issue by joaoccruz** [jsvine/pdfplumber#755]
```CITATION.cff``` files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software. [cff](https://citation-file-format.github.io/) documentation.

The inclusion of this file would be greatly appreciated

**Comment by jsvine** [comment]
Hi @joaoccruz, and thanks for the suggestion. Although I'm generally wary of bloating the root-level directory with a ton of niche files, CITATION.cff seems like a reasonable one. A couple of questions that will help with implementation:

- Is there another repository that you think publishes a particularly useful CITATION.cff file?

- Do you have an opinion on providing a CITATION.cff file *without* assigning the repository/release a DOI?

**Comment by joaoccruz** [comment]
Hi @jsvine thanks for the follow up!

Regarding your first question: I'd recommend checking out [NLTK](https://github.com/nltk/nltk/blob/develop/CITATION.cff), they have a very good CITATION.cff

As for the second question, I do not find a DOI required. To my knowledge, it is most often (if not exclusively) used in scientific publications such as journals or conference papers. NLTK, for instance, did not include one, despite requesting citations on their book.

Thanks for your time,
João Cruz

**Comment by jsvine** [comment]
Thanks, that's very helpful. How does this look to you?: https://github.com/jsvine/pdfplumber/blob/develop/CITATION.cff

**Comment by jsvine** [comment]
Closing this belatedly, as the CITATION.cff file has been added in https://github.com/jsvine/pdfplumber/commit/6af87abe6ca0d82a897f56a5a1912f20a67319ca and merged. Thanks again @joaoccruz.
