### ISSUE TITLE
Getting 'pdfplumber' has no attribute 'open' Error in latest version.

### ISSUE THREAD

**Issue by Mayank-21** [jsvine/pdfplumber#765]
## Describe the bug

Getting 'pdfplumber' has no attribute 'open' error. I am using latest version of pdfplumber

## Code to reproduce the problem

import pdfplumber
with pdfplumber.open('eng_cr_2022.pdf') as pdfplum:
    first_page = pdfplum.pages[0]
    print(first_page.chars[0])

## Expected behavior

it should run and give me extracted text.

## Actual behavior

Getting Error: AttributeError: partially initialized module 'pdfplumber' has no attribute 'open' (most likely due to a circular import)

## Screenshots

[*If applicable, add screenshots to help explain your problem.*
](https://prnt.sc/IoWcFJ52EU4g)

## Environment

- pdfplumber version: 0.7.6
- Python version: 3.8.0
- OS: windows10

**Comment by samkit-jain** [comment]
Hi @Mayank-21 Could you please share how you installed pdfplumber? And is the error happening when you try reinstalling as well? Or maybe downgrading a version?

**Comment by jsvine** [comment]
Closing stale issue, and because probably not a pdfplumber bug. Feel free to reopen with further documentation 👍
