### ISSUE TITLE
It might be character set problem 

### ISSUE THREAD

**Issue by Gadil-1987** [jsvine/pdfplumber#766]
## Describe the bug

*I used pdfplumber to read pdf file, the result was not the same thing as my expected.
I also tried to copy the chars from the pdf, and i pasted the chars to anywhere,the result were wrong.
But, I used the office-word to open the pdf，the result was ok*

## Code to reproduce the problem

![image](https://user-images.githubusercontent.com/108721053/203488666-bf8eee6d-d402-43c6-9bd7-677656cb69ce.png)

## PDF file

*
[600278  东方创业2012年度股东大会的法律意见书_600278_20130423_2.pdf](https://github.com/jsvine/pdfplumber/files/10073454/600278.2012._600278_20130423_2.pdf)

*

## Expected behavior

*key part in PAGE-4（本页无正文，为《金茂凯德律师事务所关于东方国际创业股份有限公司2012 年度股东大会的法律意见书》之签署页）*

## Environment

- pdfplumber version: [e.g., 0.7]
- Python version: [e.g., 3.10]
- OS: [e.g., window, etc.]

**Comment by jsvine** [comment]
Hi @Gadil-1987, and thank you for filing this issue. Given that the result is the same as copy-pasting directly from the document, this seems unlikely to be something `pdfpumber` can fix. It's possible that `office-word` is doing something special that this library could learn from, but I'm not sure what that would be. Closing for now, but feel free to continue the discussion here.
