### ISSUE TITLE
Too many edges detected

### ISSUE THREAD

**Issue by shangrilar** [jsvine/pdfplumber#779]
## Describe the bug

Hi, Thanks for your amazing projects.

I tried to extract tables from pdf files. But some pdf files are detected too many edges from page(above 100,000)

## Code to reproduce the problem

def curves_to_edges(cs):
        edges = []
        for c in cs:
            edges += pdfplumber.utils.rect_to_edges(c)
        return edges

lines = curves_to_edges(page.curves + page.edges)

## PDF file

[arti_error-3.pdf](https://github.com/jsvine/pdfplumber/files/10256460/arti_error-3.pdf)

## Expected behavior

one thick line can be detected as one line

## Actual behavior

one line is detected like many lines.

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: 0.7.4
- Python version: 3.8.9
- OS: MacOS

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Thanks for your interest in this library, @shangrilar. The detection of lines and rects (the source of `.edges`) is performed by [pdfminer.six](https://github.com/pdfminer/pdfminer.six), pdfplumber's main dependency. But, in either case, that (and this) library is just reflecting how the PDF itself is constructed. For some reason, it *really is* encoding thousands of rectangles, as can be seen when [inspecting the raw PDF commands](https://brendandahl.github.io/pdf.js.utils/browser/):

<img width="512" alt="Screen Shot 2022-12-19 at 3 35 51 AM" src="https://user-images.githubusercontent.com/534702/208382578-88d02be8-340a-4862-982b-c86297fcec47.png">

[...]

<img width="312" alt="Screen Shot 2022-12-19 at 3 34 05 AM" src="https://user-images.githubusercontent.com/534702/208382262-481b57d5-c124-4b21-b96f-3645af719205.png">

[...]

Given that situation, I don't think this is a bug, so I'm closing this issue. But feel free to continue the discussion here.
