### ISSUE TITLE
Dealing with merged table cells

### ISSUE THREAD

**Issue by blmoistawinde** [jsvine/pdfplumber#79]
I'm doing table extraction on a PDF generated by Word, and there are many merged cells in the table.
![1](https://user-images.githubusercontent.com/32953014/44523677-4cd15200-a70d-11e8-9b64-8085181ec595.JPG)

Now if I use `extract_table`, I would get a table like this, with many None cells.
![2](https://user-images.githubusercontent.com/32953014/44523679-5064d900-a70d-11e8-895c-ff3568fd7f22.JPG)
I want to praise this tool for its excellent accuracy on OCR! And I would be even more grateful if there is a new, easy function that can deal with these merged cells properly.

For example, I would expect the 3rd column to be also “指标”, cell at loc[0,"项目"] to be also "项目", and cell at loc[2,None] to be also 8.0, etc. To achieve this now, I must use complex `fillna` logics considering the positions of `cells`.

Thanks a lot!

**Comment by jsvine** [comment]
Thank you, @blmoistawinde. And better handling of merged cells is a good idea. I'll consider it for a future release. In the meantime, could you provide of the following?:

- A PDF containing merged cells (such as the one you have screenshotted above)
- The code you are using to extract the table
- A screenshot or text file demonstrating how you would prefer the extracted table to appear

**Comment by blmoistawinde** [comment]
Ok, below is a similar example I've made up with Microsoft Word.
[example_merged.pdf](https://github.com/jsvine/pdfplumber/files/2373206/example_merged.pdf)
![image](https://user-images.githubusercontent.com/32953014/45396353-b1793000-b66d-11e8-954f-d97c1188e5cc.png)

The code I used:
```python3
#coding=utf-8
import pdfplumber
import pandas as pd
import numpy as np

pdf = pdfplumber.open("example_merged.pdf")
p0 = pdf.pages[0]
table2df = lambda table: pd.DataFrame(table[1:], columns=table[0])
tables = table2df(p0.extract_table())
tables
```
And I got this.
![image](https://user-images.githubusercontent.com/32953014/45396322-80006480-b66d-11e8-8959-d5d41bc483fa.png)

The expected output is:
![image](https://user-images.githubusercontent.com/32953014/45396503-7dead580-b66e-11e8-8b87-312b07e9e3a5.png)

By the way, the final structure I'd like to extract from this complex table is:
A pivot table like this:
![image](https://user-images.githubusercontent.com/32953014/45396543-bd192680-b66e-11e8-92c3-ee304fde6b62.png)
and a contingence table like this:
![image](https://user-images.githubusercontent.com/32953014/45396552-c7d3bb80-b66e-11e8-963d-5d4b8ab5547d.png)
I was wondering if there exists another elegant solution for the merged cells, but I think the above one I've presented would be a reasonable one, especially for the data[8.0].

Thanks a lot!

**Comment by jsvine** [comment]
Thanks! This will be a helpful reference when I attempt to improve the handling of merged cells.

**Comment by binzhouchn** [comment]
Hi jsvine, is there any page merge operation available?

**Comment by jsvine** [comment]
@binzhouchn No, currently there is not a page merge operation available.

**Comment by rohaan2614** [comment]
Hi, can someone please confirm the merged-cell capability has been included in the releases after July 2020?

Thanks

**Comment by jsvine** [comment]
@rohaan2614 There is no specific merged-cell capability at the moment.

**Comment by pribadihcr** [comment]
+1

**Comment by jvfd3** [comment]
+1

**Comment by Guyodub** [comment]
@jsvine is the merged capability available in 2024

**Comment by santhosh-sreshta** [comment]
@jsvine Is merged cell parsing available in 2024?

**Comment by rohaan2614** [comment]
Unsubscribe

**Comment by Ankur08kv** [comment]
What is the correct solution to extract text from tables with merged rows and columns?? 
Do we have any update on this ??
