### ISSUE TITLE
Wrong coordinates of words when using function extract_words()

### ISSUE THREAD

**Issue by datdao1998** [jsvine/pdfplumber#799]
## Description
When using function **extract_words()**, the coordinates of some extracted words are wrong, in my case  ***word['x0'] = word['x1']*** (but ***word['text']*** still correct)

## Code to reproduce the problem
```
import pdfplumber

pdf_path = 'test.pdf'

with pdfplumber.open(pdf_path) as pdf:
      pages = pdf.pages
      for page in pages:
           words = page.extract_words()
           for word in words:
                 print(word['x0'], word['x1'], word['text'])
```

## Screenshots
***Output***

<img width="386" alt="Screen Shot 2023-01-30 at 22 59 21" src="https://user-images.githubusercontent.com/42546396/215528074-61021959-aa42-48d5-893b-52f1ba7b2391.png">

***Visualize text box***

<img width="512" alt="Screen Shot 2023-01-30 at 22 58 33" src="https://user-images.githubusercontent.com/42546396/215528102-67651f3d-fbfd-4483-bbac-591b7e31b218.png">

## Environment

- pdfplumber version: 0.6.0
- Python version: 3.9.12
- OS: Linux

**Comment by jsvine** [comment]
Hi @datdao1998, could you provide the PDF that you're using? Without it, it will be very difficult to diagnose your issue.

**Comment by jsvine** [comment]
Hi @datdao1998, just checking back on this. Are you able to provide the PDF? You might also try [repairing the PDF](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) and seeing if that fixes the problem you've encountered.

**Comment by sandzone** [comment]
This is definitely happening. Its not just the extract_words() function. 

.chars itself has wrong coordinates for the characters. 

Some of the coordinates for these words are even outside the page's BoundingBox.

![image](https://user-images.githubusercontent.com/2245672/221005482-08d981da-0775-4bab-9609-f1fea4c9d2b1.png)


I can email you the PDF.

**Comment by jsvine** [comment]
Thanks, @sandzone. Please do email me the PDF; my email address is in my profile. And have you tried [repairing the PDF](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file)?

**Comment by sandzone** [comment]
Thanks. You are correct. Repairing the pdf resolved the issue. However, ghostscript couldn't repair - i had to use poppler command line utilities for that.

Is there a way to integrate pdf repair as a part of pdfplumber's extraction features?

**Comment by jsvine** [comment]
Thanks for confirming, @sandzone. And that's an interesting idea. I've opened a separate issue for that here: #824
