### ISSUE TITLE
find_tables cost several minutes for one page

### ISSUE THREAD

**Issue by buptyyf** [jsvine/pdfplumber#807]
## Describe the bug

page.find_tables() cost several minutes and use 100%cpu.

```
pdfplumber_doc = pdfplumber.open(pdf_path)
pdfplumber_pages = pdfplumber_doc.pages
tables = pdfplumber_pages[20].find_tables()

```
## PDF file
[CB_7ZM3m03nICqS6eS6cf1hxEKk.pdf](https://github.com/jsvine/pdfplumber/files/10695796/CB_7ZM3m03nICqS6eS6cf1hxEKk.pdf)

*Please attach any PDFs necessary to reproduce the problem.*

**Comment by jsvine** [comment]
Hi @buptyyf, and thanks for your interest in this library. It seems that the PDF is malformed; if you [repair it with GhostScript](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file), the code above executes nearly instantaneously.

**Comment by buptyyf** [comment]
> Hi @buptyyf, and thanks for your interest in this library. It seems that the PDF is malformed; if you [repair it with GhostScript](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file), the code above executes nearly instantaneously.

Thanks a lot. How can I check pdf is malformed before I repair it?

**Comment by jsvine** [comment]
I don't have a definitive answer, unfortunately, but a web-search (e.g., for "validate pdf ghostscript") returns some results that make me think it's possible.

**Comment by buptyyf** [comment]
> I don't have a definitive answer, unfortunately, but a web-search (e.g., for "validate pdf ghostscript") returns some results that make me think it's possible.

I also use another pdf parser lib Pymupdf to parse this pdf. Parsing is very fast, and don't show it's malformed.

**Comment by jsvine** [comment]
Yes, different PDF-parsing programs have different tolerances for malformed documents. In this case, `pdfplumber` depends on [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six) for extracting PDF text/graphics locations, and `pdfminer.six` handles malformed PDFs differently than `MyPDF` (which is what `Pymupdf` uses).
