### ISSUE TITLE
Extract tables randomly moves the bbox 20 pixels away

### ISSUE THREAD

**Issue by merionum** [jsvine/pdfplumber#810]
### Discussed in https://github.com/jsvine/pdfplumber/discussions/809

<div type='discussions-op-text'>

<sup>Originally posted by **merionum** February 10, 2023</sup>
Hi guys! Thanks for the awesome library!

I am doing a large parsing task and I noticed that for some of my documents I randomly encounter this problem where the bboxes are just moved away 20 pixels in both dimensions.

Could you help me to understand what goes wrong here please?

![image psd(1)](https://user-images.githubusercontent.com/21173351/217958635-0d3e2817-e6f1-4cdc-b915-80aaa9d364a0.png)

</div>

**Comment by jsvine** [comment]
Thanks for the kind words about `pdfplumber`, @merionum! Strange thing you're seeing. It seems the PDF is malformed. Repairing it fixes the issue:

```sh
gs -o no_codes-3-1-repaired.pdf   \
  -sDEVICE=pdfwrite   \
  -dPDFSETTINGS=/prepress    \
  no_codes-3-1.pdf;
```

```
The following errors were encountered at least once while processing this file:                               
        error reading a stream                                                                                
                                                                                                              
   **** This file had errors that were repaired or ignored.                                                   
   **** The file was produced by:                                                                             
   **** >>>> iLovePDF <<<<                                                                                    
   **** Please notify the author of the software that produced this                                           
   **** file that it does not conform to Adobe's published PDF                                                
   **** specification.                                                                                        
```

![test](https://user-images.githubusercontent.com/534702/218224870-96145e24-50e6-4da5-9fe0-8b36c569d1b6.png)
