### ISSUE TITLE
AttributeError: module 'pdfplumber' has no attribute 'load'

### ISSUE THREAD

**Issue by juzj** [jsvine/pdfplumber#821]
The current version is 0.8.0

response = requests.get(url)
pdf_data = response.content

# 使用pdfplumber打开PDF文件
with pdfplumber.load(pdf_data) as pdf:
    # 遍历PDF中的所有页面
    for page in pdf.pages:
        # 提取页面中的表格信息
        tables = page.extract_tables()
        # 打印表格内容
        for table in tables:
            print(table)

**Comment by jsvine** [comment]
Hi @juzj, `.load(...)` was deprecated in `0.5.23` and removed in `0.6.0` (see [here](https://github.com/jsvine/pdfplumber/blob/stable/CHANGELOG.md#removed-2)). You'll want to use `.open(...)` instead.
