### ISSUE TITLE
Not detecting full table

### ISSUE THREAD

**Issue by wolganens** [jsvine/pdfplumber#83]
Hi! thank you for this useful tool. I would like to ask why in the case of the table showed below the full table is not recognized. As you can see, only the left side its been marked by the bounding box of the table:
![screenshot from 2018-09-25 18-43-53](https://user-images.githubusercontent.com/7290281/46048797-a8726f00-c101-11e8-9e48-1e832d70e577.png)
The original PDF file looks like:
![screenshot from 2018-09-25 20-30-54](https://user-images.githubusercontent.com/7290281/46048859-f12a2800-c101-11e8-948c-e9eb2be886cd.png)

Thank you very much.

**Comment by jsvine** [comment]
Hello, and apologies for not seeing this issue when you first filed it. I’m cleaning up old issues and am going to close this, but feel free to reopen it if you would still like advice on this. If so, please provide the original PDF, which will help diagnose the problem.
