### ISSUE TITLE
Documentation of `close()`

### ISSUE THREAD

**Issue by sujayvadlakonda** [jsvine/pdfplumber#834]
Please describe, in as much detail as possible, your proposal and how it would improve your experience with pdfplumber.

The documentation (./README.md) suggests the `Page` class has a `close()` function.
It seems like only the `PDF` class has a `close()` function.

**Comment by samkit-jain** [comment]
Hi @sujayvadlakonda Appreciate your interest in the library and thanks for pointing this out. The `close()` method should be in the `PDF` section of the documentation.

**Comment by jsvine** [comment]
Thanks @sujayvadlakonda  and @samkit-jain!
