### ISSUE TITLE
Is there any method to remove the header and footer of a pdf?

### ISSUE THREAD

**Issue by 154192** [jsvine/pdfplumber#843]
Please describe, in as much detail as possible, your proposal and how it would improve your experience with pdfplumber.

**Comment by jsvine** [comment]
The PDF specification does not have concept of a header or footer; anything that looks like a header or footer is implemented by the particular software that is writing the PDF. For that reason, there is no generic solution for removing headers/footers (although there may be a specific solution for whatever specific PDFs you're working with).
