### ISSUE TITLE
Installation of ImageMagick should be more precise

### ISSUE THREAD

**Issue by zc910704** [jsvine/pdfplumber#85]
Thanks for you remarkable work. I search a lot of tools for my work after I found this.
But I encounter two problems when I install the ImageMagick in my win10 64bit.(already solved)
the first is ImageMagick(32bit or 64bit) must be accord with the python(32bit or 64bit), even in the 64bit OS. If not, there will be a ImageMagick not installed mistake.
The second is that it need the ghostscript otherwise ImageMagick wouldn’t work properly.
I think this may be help for some user like me and saving their time. Thanks for your works that saving my time dealing with the pdf data,Hope some day I can help :)

**Comment by jsvine** [comment]
Thanks, @zc910704. In your research, did you find any websites that explain how to ImageMagick and `wand` more precisely? If possible, I'd prefer just to link out to an authoritative resource on that.

**Comment by zc910704** [comment]
Sorry...I just found the answer in the stackoverflow. I will tell you as soon as I find one.

**Comment by ebw44** [comment]
That link was quite useful to install ImageMagick for wand https://docs.wand-py.org/en/0.6.7/guide/install.html#install-imagemagick-windows
