### ISSUE TITLE
New debian patch breaks functionality

### ISSUE THREAD

**Issue by parikls** [jsvine/pdfplumber#87]
After this patch was introduced on debian-based systems, seems like your functionality is broken

https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1796563

this code raises an exception `PolicyError`:

```
import pdfplumber

with pdfplumber.open("/home/path/to.pdf") as pdf:
    pdf.pages[0].to_image()
```

Could be fixed by editing `/etc/ImageMagick-6/policy.xml` by adding next lines:

```
<policy domain="coder" rights="read|write" pattern="PDF" />
<policy domain="coder" rights="read|write" pattern="LABEL" />
```

Readme should be updated, or maybe some other workaround?

**Comment by jsvine** [comment]
Thanks again. Now addressed here: https://github.com/jsvine/pdfplumber#troubleshooting-imagemagick-on-debian-based-systems

(With a slight tweak on the instructions, which seemed to work for me.)
