### ISSUE TITLE
When I use extract_text and extract_words the input is empty

### ISSUE THREAD

**Issue by Mankvis** [jsvine/pdfplumber#887]
## Describe the bug

When I use extract_text and extract_words the input is empty

## Code to reproduce the problem

`        
with pdfplumber.open(pdf_path) as pdf:
      first_page = pdf.pages[0]
      print(first_page.extract_text())
`

## PDF file

[demo.pdf](https://github.com/jsvine/pdfplumber/files/11513768/demo.pdf)

## Expected behavior

The Chinese text content of the pdf that should be output

## Environment

- pdfplumber version: [0.9.0]
- Python version: [3.9.5]
- OS: [Mac]

**Comment by jsvine** [comment]
Hi @Mankvis, and thanks for your interest in this library. The page you've shared is, unfortunately, an image-based PDF page, containing no digital information directly from text. You can confirm this by trying to select the text from the page and paste it into a text document.

See this comment for an example of what you could do next: https://github.com/jsvine/pdfplumber/discussions/717#discussioncomment-3476384
