### ISSUE TITLE
How to use page.filter(test_function) ?

### ISSUE THREAD

**Issue by satyaad-kore** [jsvine/pdfplumber#89]
i am trying to delete tables inside the page and I'm trying to use **page.filter** function for that, where i have table bbox and I am trying to compare if object coordinates are inside the table coordinates or not.
But I was unable to find any sample usage for **filter** function.

I tried in this way :
`def filter_func(object):
    #some logic to find the coordinates inside boundary or not`

`new_page = page.filter(lambda x: x if filter_func(x) else '')`

but this usage is not working unfortunately, please help in knowing how to use **page.filter** function

**Comment by jsvine** [comment]
Hi @satyaad-kore. `page.filter`'s argument should be a function that __accepts__ a PDF object and returns `True` or `False`. For instance, to remove characters with a size smaller than 10, you could run `page.filter(lambda obj: not (obj["object_type"] == "char" and obj["size"] < 10))`

**Comment by Vinayakshukla7** [comment]
What will be the object here i.e.. obj?

**Comment by samkit-jain** [comment]
@Vinayakshukla7 Here, `obj` is nothing but an argument to the lambda function. You don't need to explicitly declare an `obj` variable. The lambda expression will be passed the page's objects. It is documented here https://github.com/jsvine/pdfplumber#objects.
