### ISSUE TITLE
Different LAParams for different zones

### ISSUE THREAD

**Issue by QuentinAndre11** [jsvine/pdfplumber#893]
If I read correctly, PDFPlumber will extract the pages then crop or filter elements. Is there a way to crop before extracting or, even better, to be able to extract different zones of the PDF with different LAParams ? I'd like to avoid extracting multiple times my PDF with different parameters.

**Comment by jsvine** [comment]
Hi @QuentinAndre11, and thanks for the interesting proposal. Unfortunately, I don't think this will be possible (although I'm open to other people suggesting solutions that I may have overlooked). The LAParams are passed to `pdfminer.six` when `pdfplumber`  requests the layout for a page:

https://github.com/jsvine/pdfplumber/blob/ae676aeacd958e7b1572f35568e612314d611eff/pdfplumber/page.py#L152-L163

I don't believe that `pdfminer.six` can apply its layout analysis to _just_ one zone (or cropped section) of a page. (Moreover, the cropping/filtering itself actually _depends_ on the results of the layout analysis.)
