### ISSUE TITLE
Options to export table to different formats?

### ISSUE THREAD

**Issue by PinkFloyded** [jsvine/pdfplumber#92]
They could be methods that work on the Table class. Could add options to export to:

* Dataframe
* html
* csv
* excel

**Comment by jsvine** [comment]
Hello, and apologies for not responding to this suggestion when you first made it. I think, however, that those export options are best handled outside of `pdfplumber`, which I would like to focus just on the pdf-extracting tasks. But thank you for the suggestion, regardless.
