### ISSUE TITLE
extract table cross two pages

### ISSUE THREAD

**Issue by tujinshu** [jsvine/pdfplumber#922]
It is very common for tables to span two pages in a PDF document, but pdfplumber can only handle tables that are on a single page. Is it possible for pdfplumber to support tables that span multiple pages?

for example:
this table cross the page 165 and the page 166，can it be exacted ? 
<img width="655" alt="企业微信截图_91f5411e-7cbf-4b9e-aa51-410e88765cb3" src="https://github.com/jsvine/pdfplumber/assets/7986082/bc652836-4808-4d34-8ffc-2ce46b761014">

[wps.pdf](https://github.com/jsvine/pdfplumber/files/11943527/wps.pdf)

**Comment by jsvine** [comment]
Hi @tujinshu, and thanks for your interest in `pdfplumber`. Because of the wide variety of ways that PDFs can represent tables, and the wide variety of ways that they can be split across pages, I currently do not think I'll be able to add such a feature to the library.

**Comment by roki1031** [comment]
> Hi @tujinshu, and thanks for your interest in `pdfplumber`. Because of the wide variety of ways that PDFs can represent tables, and the wide variety of ways that they can be split across pages, I currently do not think I'll be able to add such a feature to the library.您好，感谢您对 `pdfplumber` 的关注。由于 PDF 表示表格的方式多种多样，并且跨页面分割的方式也多种多样，因此我目前认为无法将这样的功能添加到库中。

This feature is very much needed, please.
