### ISSUE TITLE
ImportError: cannot import name 'PDFObjectNotFound'

### ISSUE THREAD

**Issue by chizhu** [jsvine/pdfplumber#93]
mac pure python3.6 . after pip3 install pdfplumber .  import pdfplumber meet this error:  import pdfplumber
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/__init__.py", line 1, in <module>
    from pdfplumber.pdf import PDF
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/pdf.py", line 6, in <module>
    from pdfminer.pdfdocument import PDFDocument
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdfdocument.py", line 26, in <module>
    from .pdftypes import PDFObjectNotFound
ImportError: cannot import name 'PDFObjectNotFound'

**Comment by jsvine** [comment]
I can't seem to replicate this error. If you run `pip3 install -U pdfplumber`, do you still have the same problem? If so, could you paste the results of `pip3 freeze | grep pdf`?

**Comment by chizhu** [comment]
I try  pip3 install -U pdfplumber and  still  meet this error .use pip3 freeze | grep pdf,it shows:
pdfminer.six==20181108
pdfminer3k==1.3.1
pdfplumber==0.5.11
pdftabextract==0.3.0

**Comment by corelli359** [comment]
@chizhu i have the same error and i have fixed it , you can try to remove pdfminer.six and install it again (pip install pdfminer.six==20181108). maybe it can help you.

**Comment by gupeng1208** [comment]
think you！！

**Comment by Ashu-jun** [comment]
from .pdftypes import PDFObjectNotFound
ImportError: cannot import name 'PDFObjectNotFound' from 'pdfminer.pdftypes'

I have installed pdfminer.six and pdfminer3k both
using python 3.7,anaconda spyder 3.2
please help me to resolve this

**Comment by mdrijwan123** [comment]
Just install pdfminer.six for python 3.7 and remove pdfminer3k if installed. This solved my case

**Comment by qishuaiwang** [comment]
> @chizhu i have the same error and i have fixed it , you can try to remove pdfminer.six and install it again (pip install pdfminer.six==20181108). maybe it can help you.

I solved flow your commit,thanks.
