### ISSUE TITLE
 char' top and bottom attributes exceed page's bbox

### ISSUE THREAD

**Issue by kalelsun** [jsvine/pdfplumber#932]
## Describe the bug
When using pdfplumber to read a PDF, I encountered an issue where the top and bottom attributes of chars on certain pages **exceed** the bbox (bounding box) of the page.

## Code to reproduce the problem

```python
import pdfplumber

pdf = pdfplumber.open('./the_page.pdf')
first_page = pdf.pages[0]
print('page bbox:\n', first_page.bbox)
print('chars bbox:')
for char in first_page.chars:
    print(char['text'], 'x0:', char['x0'], 'top:', char['top'], 'x1:', char['x1'], 'bottom:', char['bottom'], sep='\t')

# page bbox:
#  (0, 0, 631.08, 841.68)
# chars bbox:
# 2	x0:	384.74115	top:	1330.5039889999998	x1:	390.74115	bottom:	1342.5039889999998
# 0	x0:	390.74115	top:	1330.5039889999998	x1:	396.74115	bottom:	1342.5039889999998
# 2	x0:	396.74115	top:	1330.5039889999998	x1:	402.74115	bottom:	1342.5039889999998
# 1	x0:	402.74115	top:	1330.5039889999998	x1:	408.74115	bottom:	1342.5039889999998
# 3	x0:	437.268646	top:	1330.5039889999998	x1:	443.268646	bottom:	1342.5039889999998
# 3	x0:	474.7883	top:	1330.5039889999998	x1:	480.7883	bottom:	1342.5039889999998
# 1	x0:	480.7883	top:	1330.5039889999998	x1:	486.7883	bottom:	1342.5039889999998
```
## PDF file

[the_page.pdf](https://github.com/jsvine/pdfplumber/files/12013238/the_page.pdf)

## Expected behavior

 the top and bottom attributes of chars should be **within** the bbox of the page.

## Actual behavior

 the top and bottom attributes of characters **exceed** the bbox of the page.

## Screenshots

<img width="650" alt="page" src="https://github.com/jsvine/pdfplumber/assets/29829913/c1bd6673-30b8-47a5-b8ce-11bb8d807142">

Only the areas enclosed by the blue boxes contain characters, the rest are images.

## Environment

- pdfplumber version: 0.9.0
- Python version: 3.10.12
- OS: Linux

## Additional context

[colab](https://colab.research.google.com/drive/1ffJjPZA0fRRNpm4l9acCbZWgf-OxUtHK?usp=sharing)

**Comment by jsvine** [comment]
Hi @kalelsun, and thanks for your interest in this library. Have you tried [repairing](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) the PDF? Does that change the results? When I've seen issues like these in the past, they often are caused by malformed documents.

**Comment by kalelsun** [comment]
> Hi @kalelsun, and thanks for your interest in this library. Have you tried [repairing](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) the PDF? Does that change the results? When I've seen issues like these in the past, they often are caused by malformed documents.

Yes, you are absolutely right! I have achieved the desired result by fixing the PDF.

**Comment by dhdaines** [comment]
Hi, the actual problem here is that `pdfminer.six` isn't normalizing the MediaBox.  In the file we see this:

```
/MediaBox [ 0 841.68 631.08 0 ] 
```

As noted elsewhere in the code (and in the PDF standard) PDF allows a rectangle to be specified by any two opposing corners, so this is the same MediaBox as `0 0 631.08 841.68`, and indeed we see that the `CropBox` is normalized:

```
/CropBox [ 0 0 631.08 841.68 ]
```

This is fixed in PLAYA now 😉
