### ISSUE TITLE
Get the Text associated with the hyperlinks - PdfPlumber

### ISSUE THREAD

**Issue by mukundhareddy1996** [jsvine/pdfplumber#940]
## I am not able to get the text associated with the hyperlinks.

We all know, that after loading the document. Using _page.annots_ or _page.hyperlinks_. we are able to get the links and also their rect boxes. But I don't see any text associated with it. 

_In simple words:_
I want to extract the [hyperlink ](https://google.com)from here. 

_And rephrase the extracted link as below:_
I want to extract the hyperlink: https://google.com from here. 

To do the above scenario. I need to **get the text associated with the hyperlink**. But I don't see any option to get the text. Getting just the link with out the associated text does not make any scense.

## I have tried to intersect the rect of hyperlinks (URI) with the char, but nothing was matching

```
import pdfplumber 
pdf = pdfplumber.open("Any file with hyperlinks in it")
page = pdf.pages[0] 
for char in page.objects["char"]: 
    if char["x0"] in ["258.11","121.35","82.2"]:
        print("identified the character of hyperlink")
```

## Environment

- pdfplumber version: [ 0.10.1]
- Python version: [3.11.0]
- OS: [windows.]

**Comment by jsvine** [comment]
Hi @mukundhareddy1996, and thanks for your interest in this library. Unfortunately, hyperlinks in PDFs do not automatically come associated with text. Your instinct to find the text overlapping with the hyperlink is correct, although I don't quite understand the code example you've shared. But doing something like this this (using a PDF available in this repository's `tests/pdfs` directory) seems to work fine:
 
```python
import pdfplumber
pdf = pdfplumber.open("tests/pdfs/pdffill-demo.pdf")
page = pdf.pages[0]
link = page.hyperlinks[0]

text = page.crop((
    link["x0"],
    link["top"],
    link["x1"],
    link["bottom"],
)).extract_text()

print(text)
```

... printing:

```
Online Help
```

**Comment by mukundhareddy1996** [comment]
thanks @jsvine. Your understanding is correct. I require the text associated with the hyperlinks. Thanks for your logic. I have done a basic test with the above logic and it is working. Thank you😊
