### ISSUE TITLE
Getting delegate error while using to_image method

### ISSUE THREAD

**Issue by satyaaditya** [jsvine/pdfplumber#95]
I am using to_image with following code 
` def get_row_image(self, page, row_bbox):`
 `         try:`
`              row_bbox = list(row_bbox)`
`              row_bbox[0] -= 110`
`              row_bbox[2] += 50`
`              im = page.crop(tuple(row_bbox))`
`              img = im.to_image()`
`              return self.save_image(img)`
       ` except Exception:`
            `logger.error('Error in getting row as image')`
            `logger.debug(traceback.format_exc())`

And while executing this, the following exception is being raised 
`DelegateError: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dFirstPage=1 -dLastPage=1 '-sOutputFile=/tmp/magick-306986vwsCznMqaRS%d' '-f/tmp/magick-30698YyK46C6YgeLw' '-f/tmp/magick-30698MvDuyWjhTnFa'' (-1) @ error/delegate.c/ExternalDelegateCommand/462
`
reference pdf : https://drive.google.com/open?id=1mezw2bqFY6LaK27awSZq2p85vX_5hpqF

its raising exception for some particular pdfs, i have some pdfs for which it's working fine

**Comment by satyaad-kore** [comment]
I had Ghostscript already installed

**Comment by satyaaditya** [comment]
i have got  ghostscript already installed

**Comment by satyaaditya** [comment]
resolved it myself, ghostscript is the culprit. It was upgraded to 9.26, i downgraded to 9.25 and everything is fine now.
