### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vinayak-mehta** [jsvine/pdfplumber#96]
I'm trying to extract tables from the following PDFs: [[1]](https://github.com/socialcopsdev/camelot/blob/master/docs/benchmark/stream/budget/budget.pdf) and [[2]](https://github.com/socialcopsdev/camelot/blob/master/docs/benchmark/stream/mexican_towns/mexican_towns.pdf) using the code in this [gist](https://gist.github.com/vinayak-mehta/8a3bf37350b241b966483d202a5109b9). The code fails with the following traceback:

<pre>
Traceback (most recent call last):
  File "plumb.py", line 10, in <module>
    table = p0.extract_table()
  File "/home/vinayak/.local/share/virtualenvs/camelot-pdfplumber/local/lib/python2.7/site-packages/pdfplumber/page.py", line 185, in extract_table
    largest = list(sorted(tables, key=sorter))[0]
IndexError: list index out of range
</pre>

I'm on Python 2.7 and pdfplumber 0.5.11. Any pointers on how I can solve this?

**Comment by jsvine** [comment]
Hi @vinayak-mehta, and my apologies for the slowness in responding. It appears that `pdfplumber`'s default table-extraction settings don't identify a table in the on the first page of that PDF, and so the list of tables is empty, triggering that IndexError. It's worth taking a look at the library's [table-extraction options](https://github.com/jsvine/pdfplumber#table-extraction-settings). In this case, it looks like you'd want to change `vertical_strategy` and `horizontal_strategy`.
