### ISSUE TITLE
help！解析文件会出现重复的文本

### ISSUE THREAD

**Issue by PeifengRen** [jsvine/pdfplumber#992]
<img width="478" alt="源文件" src="https://github.com/jsvine/pdfplumber/assets/50514566/a0f9c858-607c-44c2-8809-1a582a7c76a7">
the output:
![输出结果](https://github.com/jsvine/pdfplumber/assets/50514566/37f2c755-9176-4588-8401-d1cb4fb86c59)

**Comment by PeifengRen** [comment]
![输出结果](https://github.com/jsvine/pdfplumber/assets/50514566/45a4401c-f689-4a9b-85e1-82acf2133b83)

**Comment by PeifengRen** [comment]
Parsing PDF files may result in duplicate content. For example, **How are you?** After parsing,  **How How are are  you you??** Or **How are you? How are you?**. I don't know if you have ever encountered such a situation. Thank you very much indeed

**Comment by wind-chh** [comment]
the PDF file renders the same character twice instead of using bold font to achieve a bold effect, so you get duplicate texts.

You may need rewrite  `

> https://github.com/jsvine/pdfplumber/blob/94da66c1b32954d02ef03a5a9b30d0177d27af84/pdfplumber/utils/text.py#L562

`  function to fit your situation.

**Comment by jsvine** [comment]
Thanks @wind-chh; to clarify: @PeifengRen, please try running `page.dedupe_chars().extract_text()`.

**Comment by PeifengRen** [comment]
Thanks very much!!!
